export type InputSource='keyboard'|'midi'|'vocal';
export interface VocalSettings {mode:'hum'|'sing';advanced:boolean;deviceId:string;gain:number;gateDb:number;clarity:number;stabilityMs:number;minimumMs:number;releaseMs:number;range:'auto'|'low'|'middle'|'high';minMidi:number;maxMidi:number;pitchMode:'raw'|'stabilized'|'musical';correctionCents:number;echoCancellation:boolean;noiseSuppression:boolean;autoGainControl:boolean;saveAudio:boolean;maxMinutes:number}
export interface PitchFrame {time:number;hz:number|null;midi:number|null;confidence:number;rms:number;voiced:boolean;wave:number[];delayMs?:number}
export interface VocalSegment {pitch:number;startTime:number;endTime:number;confidence:number;meanMidi:number;spread:number;uncertain:boolean;suggestedPitch?:number}
export interface VocalDraft {pitch:number;startTime:number;lastTime:number;confidence:number}
export interface VocalDiagnostic {source:'vocal';confidence:number;meanMidi:number;spread:number;uncertain:boolean;audioStartTime:number;audioEndTime:number;suggestedPitch?:number;reviewed?:boolean}
export interface TakeAudio {id:string;mime:string;bytes:number;duration:number;offset:number;length:number;capturedAt:string}
export const DEFAULT_VOCAL:VocalSettings={mode:'hum',advanced:false,deviceId:'',gain:1,gateDb:-48,clarity:.82,stabilityMs:65,minimumMs:90,releaseMs:65,range:'auto',minMidi:32,maxMidi:96,pitchMode:'stabilized',correctionCents:25,echoCancellation:false,noiseSuppression:false,autoGainControl:false,saveAudio:false,maxMinutes:3};
export function vocalSettings(value?:Partial<VocalSettings>):VocalSettings{return {...DEFAULT_VOCAL,...value};}
export const VOCAL_RANGES={auto:[32,96],low:[36,64],middle:[48,79],high:[60,96]} as const;
export function validateVocal(v:VocalSettings){if(!v||typeof v!=='object')throw new Error('Réglages vocaux invalides.');for(const [key,min,max] of [['gain',.1,4],['gateDb',-80,-10],['clarity',.5,1],['stabilityMs',20,300],['minimumMs',40,500],['releaseMs',20,300],['minMidi',0,126],['maxMidi',1,127],['correctionCents',0,60],['maxMinutes',1,10]] as const){const x=v[key];if(!Number.isFinite(x)||x<min||x>max)throw new Error('Réglage vocal invalide : '+key);}if(v.maxMidi<=v.minMidi||!['hum','sing'].includes(v.mode)||!['raw','stabilized','musical'].includes(v.pitchMode)||!['auto','low','middle','high'].includes(v.range)||typeof v.deviceId!=='string'||v.deviceId.length>400)throw new Error('Mode vocal invalide.');for(const k of ['advanced','echoCancellation','noiseSuppression','autoGainControl','saveAudio'] as const)if(typeof v[k]!=='boolean')throw new Error('Option vocale invalide.');}
