import {type Project} from '../music/model.ts';
import {cleanLyrics,removeRange} from '../music/editing.ts';
export function chooseTake(p:Project,takeId:string){const take=p.takes.find(t=>t.id===takeId);if(!take)throw new Error('Prise introuvable.');const track=p.tracks.find(t=>t.id===take.trackId);if(!track)throw new Error('Voix introuvable.');const previous=p.takes.filter(t=>t.selected&&t.trackId===take.trackId&&t.startBeat===take.startBeat&&t.endBeat===take.endBeat);const priorIds=new Set(previous.flatMap(t=>t.events.map(n=>n.id)));track.events=track.events.filter(n=>!priorIds.has(n.id));
 if(take.mode==='replace'){const backed=new Set(take.replacedEvents?.map(n=>n.id));take.replacementFragments=[...new Set([...take.replacementFragments??[],...previous.flatMap(t=>t.replacementFragments??[])])];track.events=track.events.flatMap(n=>{const parts=removeRange([n],take.startBeat,take.endBeat);if(backed.has(n.id))take.replacementFragments!.push(...parts.map(n=>n.id));return parts;});}
 const existing=new Set(track.events.map(n=>n.id));track.events.push(...structuredClone(take.events).filter(n=>!existing.has(n.id)));previous.forEach(t=>t.selected=false);take.selected=true;cleanLyrics(p);
}
export function deleteTake(p:Project,takeId:string){const take=p.takes.find(t=>t.id===takeId);if(!take)return;if(take.selected){const ids=new Set(take.events.map(n=>n.id));const track=p.tracks.find(t=>t.id===take.trackId);if(track)track.events=track.events.filter(n=>!ids.has(n.id));}p.takes=p.takes.filter(t=>t.id!==takeId);cleanLyrics(p);}
/** Restore the recorded layer's previous zone, including split notes and their lyric/link associations. */
export function restoreBeforeTake(p:Project,takeId:string){const take=p.takes.find(t=>t.id===takeId);if(!take||!take.selected)return;const track=p.tracks.find(t=>t.id===take.trackId)!;const ids=new Set(take.events.map(n=>n.id));track.events=track.events.filter(n=>!ids.has(n.id));
 if(take.mode==='replace'&&take.replacedEvents){const fragments=new Set(take.replacementFragments??[]),originalIds=new Set(take.replacedEvents.map(n=>n.id));track.events=removeRange(track.events,take.startBeat,take.endBeat).filter(n=>!fragments.has(n.id)&&!originalIds.has(n.id));track.events.push(...structuredClone(take.replacedEvents));
  for(const original of take.replacedLyrics??[]){const current=p.lyrics.find(l=>l.id===original.id);if(!current){p.lyrics.push(structuredClone(original));continue;}for(let i=0;i<original.syllables.length;i++){const s=original.syllables[i];if(!(s.noteIds??(s.noteId?[s.noteId]:[])).some(id=>originalIds.has(id)))continue;const index=s.id?current.syllables.findIndex(c=>c.id===s.id):i;if(index>=0&&index<current.syllables.length)current.syllables[index]={...current.syllables[index],noteId:s.noteId,noteIds:structuredClone(s.noteIds),startBeat:s.startBeat,endBeat:s.endBeat};}}
  const links=take.replacedLinks??[];p.links=[...(p.links??[]).filter(l=>!links.some(s=>s.id===l.id)),...structuredClone(links)];
 }
 take.selected=false;cleanLyrics(p);
}
