import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createProject,makeNote} from '../../src/music/model';
import {loadScore,currentProject} from './helpers';
function fixture(bars=7){const p=createProject({title:'Sept mesures · SORATRO 0.6',timeSignature:'4/4',tonic:'C'});p.settings.measureCount=bars;p.tracks.forEach(t=>t.events=Array.from({length:bars*4},(_,i)=>makeNote(t.id,[60,62,64,65][i%4],i,1,p.tempo)));return p;}
async function layout(page:Page){await page.getByRole('button',{name:'Partition',exact:true}).click();await page.getByRole('tab',{name:'Mise en page de la partition'}).click();return page.locator('dialog');}
const sizes=[{width:360,height:640},{width:390,height:844},{width:412,height:915},{width:740,height:390},{width:800,height:1280},{width:1366,height:768},{width:1440,height:900},{width:1920,height:1080}];
for(const viewport of sizes)test(`Composition, staged layout, export and menus fit ${viewport.width}×${viewport.height}`,async({browser},info)=>{
 const mobile=viewport.width<=800,context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile}),page=await context.newPage();const p=fixture();await loadScore(page,p);
 await page.getByRole('tab',{name:'Piano Roll',exact:true}).click();const roll=page.locator('.roll-viewport');expect((await roll.boundingBox())!.height).toBeGreaterThan(viewport.height<500?70:140);
 await page.getByRole('button',{name:'État du panneau des pistes'}).click();await page.getByRole('button',{name:'Masquer le clavier piano'}).click();expect((await roll.boundingBox())!.height).toBeGreaterThan(viewport.height<500?120:200);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(viewport.width+1);
 const rb=(await roll.boundingBox())!;await roll.locator('svg').dispatchEvent('contextmenu',{clientX:rb.x+rb.width-4,clientY:rb.y+rb.height-4});const menu=page.getByRole('menu',{name:'Actions des notes'});await expect(menu).toBeVisible();const mb=(await menu.boundingBox())!;expect(mb.x).toBeGreaterThanOrEqual(0);expect(mb.y).toBeGreaterThanOrEqual(0);expect(mb.x+mb.width).toBeLessThanOrEqual(viewport.width);expect(mb.y+mb.height).toBeLessThanOrEqual(viewport.height);await page.locator('.context-dismiss').dispatchEvent('pointerdown');
 await page.getByRole('button',{name:'Tap Tempo',exact:true}).click();await expect(page.getByRole('group',{name:'Réglage Tap Tempo'})).toBeInViewport();await page.getByRole('button',{name:'Fermer Tap Tempo'}).click();
 await page.getByLabel('Source d’enregistrement').selectOption('vocal');await expect(page.locator('.vocal-panel')).toBeVisible();expect((await roll.boundingBox())!.height).toBeGreaterThan(viewport.height<500?50:100);await page.screenshot({path:info.outputPath('composition-vocal.png')});await page.getByLabel('Source d’enregistrement').selectOption('keyboard');
 const d=await layout(page);await expect(d.locator('.layout-preview .score-viewport')).toBeVisible();
 if(viewport.width<=760){await expect(d.getByLabel('Mesures par ligne',{exact:true})).toBeHidden();await d.getByRole('button',{name:'Paramètres de mise en page',exact:true}).click();}
 await expect(d.getByLabel('Mesures par ligne',{exact:true})).toHaveValue('4');await d.getByLabel('Taille Solfa',{exact:true}).fill('20');await d.getByRole('button',{name:'Mesures et systèmes',exact:true}).click();await expect(d.getByLabel('Alignement des mesures')).toHaveValue('grid');
 expect(await d.getByLabel('Mesures par système').count()).toBe(0);expect(await d.getByLabel('Mesures par ligne',{exact:true}).count()).toBe(1);
 if(viewport.width<=760)await d.getByRole('button',{name:'Fermer les paramètres de mise en page'}).click();
 await expect(d.getByRole('button',{name:'Appliquer la mise en page'})).toBeInViewport();await page.screenshot({path:info.outputPath('layout.png')});
 await d.getByRole('button',{name:'Appliquer la mise en page'}).click();expect((await currentProject(page)).layout.noteSize).toBe(20);
 await page.getByRole('button',{name:'PDF / Export'}).click();const e=page.locator('dialog');await expect(e.getByRole('button',{name:'Exporter PDF'})).toBeInViewport();await expect(e.getByRole('button',{name:'Partager',exact:true})).toBeInViewport();
 if(viewport.width<=760){await e.getByRole('button',{name:'Paramètres de l’export'}).click();await expect(e.getByLabel('Mesures par ligne',{exact:true})).toHaveValue('4');await e.getByRole('button',{name:'Paramètres de l’export'}).click();}
 const waiting=page.waitForEvent('download');await e.getByRole('button',{name:'Exporter PDF'}).click();const pdf=await waiting;expect((await readFile((await pdf.path())!)).subarray(0,5).toString()).toBe('%PDF-');await pdf.saveAs(info.outputPath('seven-bars.pdf'));
 await page.screenshot({path:info.outputPath('export.png')});await context.close();
});
test('Seven bars align at 20 px; 150% screen zoom does not alter SVG/PDF/PNG or the musical project',async({page},info)=>{
 const p=fixture();await loadScore(page,p);const d=await layout(page);const size=d.getByLabel('Taille Solfa',{exact:true});await size.focus();await size.press('ControlOrMeta+A');await size.pressSequentially('20');await expect(size).toHaveValue('20');await d.getByRole('button',{name:'Appliquer la mise en page'}).click();
 const saved=await currentProject(page),notes=page.locator('.composition text[data-note-id]');await expect(notes).toHaveCount(112);expect(await notes.evaluateAll(nodes=>[...new Set(nodes.map(n=>n.getAttribute('font-size')))])).toEqual(['20']);
 const starts=await notes.evaluateAll((nodes,ids)=>ids.map(id=>+nodes.find(n=>n.getAttribute('data-note-id')===id)!.getAttribute('x')!),p.tracks[0].events.filter((_,i)=>i%4===0).map(n=>n.id));for(let i=4;i<7;i++)expect(starts[i]).toBeCloseTo(starts[i-4],8);
 const zoom=page.locator('.composition').getByLabel('Zoom de la partition (%)');await zoom.focus();await zoom.press('ControlOrMeta+A');await zoom.pressSequentially('150');await expect(zoom).toHaveValue('150');await expect(page.locator('.composition .engraved-scale').first()).toHaveCSS('transform','matrix(1.5, 0, 0, 1.5, 0, 0)');expect(await currentProject(page)).toEqual(saved);
 await page.getByRole('button',{name:'PDF / Export'}).click();const e=page.locator('dialog');
 for(const format of ['SVG','PNG','PDF']){const wait=page.waitForEvent('download');await e.getByRole('button',{name:format==='PDF'?'Exporter PDF':format,exact:true}).click();const download=await wait,bytes=await readFile((await download.path())!);if(format==='SVG'){expect(bytes.toString()).toContain('font-size="20"');expect(bytes.toString()).not.toContain('data-measure="8"');}if(format==='PNG')expect(bytes.subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a');await download.saveAs(info.outputPath('seven-bars.'+format.toLowerCase()));}
});
test('Favorites persist; a line reset stages precisely, applies atomically and is reversible with Undo',async({page})=>{
 const p=fixture(12);p.layout.systemCounts={5:3};p.layout.systemGaps={5:50,8:60};p.layout.measureWidths={6:1.1,9:1.1};await loadScore(page,p);let d=await layout(page);await d.getByRole('button',{name:'Désépingler Taille paroles'}).click();await d.getByRole('button',{name:'Mesures et systèmes',exact:true}).click();await d.getByRole('button',{name:'Épingler Justification des lignes'}).click();await d.getByText('Exceptions locales et sauts',{exact:true}).click();await d.getByLabel('Mesure à régler').fill('6');await d.getByRole('button',{name:'Réinitialiser cette ligne',exact:true}).click();await d.getByRole('button',{name:'Appliquer la mise en page'}).click();let saved=await currentProject(page);expect(saved.layout.systemCounts['5']).toBeUndefined();expect(saved.layout.systemGaps['8']).toBe(60);expect(saved.layout.measureWidths['6']).toBeUndefined();expect(saved.layout.measureWidths['9']).toBe(1.1);expect(saved.tracks).toEqual(p.tracks);
 await page.getByRole('button',{name:'Annuler',exact:true}).click();saved=await currentProject(page);expect(saved.layout.systemCounts['5']).toBe(3);expect(saved.layout.systemGaps['5']).toBe(50);await page.reload();d=await layout(page);await expect(d.getByRole('button',{name:'Désépingler Justification des lignes'})).toBeVisible();await expect(d.getByRole('button',{name:'Désépingler Taille paroles'})).toHaveCount(0);
});
test('A dense line preserves 24 px type, reports the constraint and prevents a clipped export until corrected',async({page})=>{
 const p=fixture(7);p.layout.noteSize=24;p.layout.paper='A5';p.tracks.forEach(t=>t.events=Array.from({length:224},(_,i)=>makeNote(t.id,60+i%5,i*.125,.125,p.tempo)));await loadScore(page,p);await page.getByRole('button',{name:'PDF / Export'}).click();const d=page.locator('dialog');await expect(d.getByRole('button',{name:'Exporter PDF'})).toBeDisabled();await expect(d.locator('.export-settings [role=alert]')).toContainText('taille Solfa de 24');await expect(d.locator('.engraved-content text[data-note-id]').first()).toHaveAttribute('font-size','24');await d.getByLabel('Mesures par ligne',{exact:true}).fill('1');await d.getByLabel('Papier',{exact:true}).selectOption('A4');await d.getByLabel('Orientation',{exact:true}).selectOption('landscape');await d.getByLabel('Marges (mm)',{exact:true}).fill('5');await expect(d.getByRole('button',{name:'Exporter PDF'})).toBeEnabled();
});
test('Touch pinch, double tap and rotation preserve the document, selection and preview position',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage(),p=fixture();await loadScore(page,p);await page.getByRole('button',{name:'Partition',exact:true}).click();const panel=page.locator('.composition .score-panel'),before=await currentProject(page);await panel.getByLabel('Zoom de la partition (%)').fill('100');const area=(await panel.locator('.score-viewport').boundingBox())!,x=area.x+area.width/2,y=area.y+area.height/2,cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:x-25,y},{id:2,x:x+25,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:x-50,y},{id:2,x:x+50,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect(panel.getByLabel('Zoom de la partition (%)')).toHaveValue('200');expect(await currentProject(page)).toEqual(before);
 await page.setViewportSize({width:740,height:390});await expect(panel.getByLabel('Zoom de la partition (%)')).toHaveValue('200');await page.setViewportSize({width:390,height:844});await expect(panel.getByLabel('Zoom de la partition (%)')).toHaveValue('200');
 for(let i=0;i<2;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(90);}
 await expect(panel.getByLabel('Cadrage de la partition')).toHaveValue('width');expect(await currentProject(page)).toEqual(before);await context.close();
});
test('Browser sharing uses Web Share files and downloads when unavailable',async({page})=>{
 await loadScore(page,fixture());await page.getByRole('button',{name:'PDF / Export'}).click();const d=page.locator('dialog');await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>false});});let wait=page.waitForEvent('download');await d.getByRole('button',{name:'Partager',exact:true}).click();expect((await wait).suggestedFilename()).toMatch(/\.pdf$/);
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async(data:ShareData)=>{(window as any).qaSharedName=data.files?.[0].name;}});});await d.getByRole('button',{name:'Partager',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).qaSharedName)).toMatch(/\.pdf$/);
 const before=await currentProject(page);await d.getByLabel('Orientation',{exact:true}).selectOption('landscape');await page.evaluate(()=>{Object.defineProperty(navigator,'share',{configurable:true,value:async()=>{throw new DOMException('Cancelled','AbortError');}});});await d.getByRole('button',{name:'Partager',exact:true}).click();await expect(page.locator('.toast')).toContainText('Partage annulé');expect(await currentProject(page)).toEqual(before);
});
test('Small visual viewport keeps settings and Apply visible while a numeric field is focused',async({page})=>{
 await page.setViewportSize({width:360,height:640});await page.addInitScript(()=>{const viewport=new EventTarget() as any;Object.assign(viewport,{height:640,width:360,offsetTop:0,offsetLeft:0});Object.defineProperty(window,'visualViewport',{configurable:true,value:viewport});});await loadScore(page,fixture());const d=await layout(page);await d.getByRole('button',{name:'Paramètres de mise en page',exact:true}).click();await d.getByLabel('Taille Solfa',{exact:true}).focus();await page.evaluate(()=>{(visualViewport as any).height=350;visualViewport!.dispatchEvent(new Event('resize'));});expect((await d.boundingBox())!.height).toBeLessThanOrEqual(350);await expect(d.getByRole('button',{name:'Appliquer la mise en page'})).toBeInViewport();await d.getByLabel('Taille Solfa',{exact:true}).fill('20');await d.getByRole('button',{name:'Appliquer la mise en page'}).click();expect((await currentProject(page)).layout.noteSize).toBe(20);
});

test('Page layout and export preserve the same personalized display geometry',async({page})=>{
 const p=fixture();p.tracks[0].events.push(makeNote('soprano',72,9.5,.5,p.tempo));await loadScore(page,p);await page.getByRole('button',{name:'Paramètres',exact:true}).click();let d=page.locator('dialog');await d.getByRole('combobox',{name:'Densité',exact:true}).selectOption('airy');await d.getByLabel('Espacement',{exact:true}).focus();await page.keyboard.press('End');await expect(d.getByLabel('Espacement',{exact:true})).toHaveValue('1.6');await d.getByRole('button',{name:'Fermer',exact:true}).click();
 const before=await currentProject(page);d=await layout(page);const engraved=await d.locator('[data-score-role="note"]').evaluateAll(nodes=>nodes.map(n=>({x:n.getAttribute('x'),y:n.getAttribute('y'),size:n.getAttribute('font-size'),text:n.textContent})));await d.getByRole('button',{name:'Annuler l’aperçu'}).click();await page.getByRole('button',{name:'PDF / Export',exact:true}).click();d=page.locator('dialog');expect(await d.locator('[data-score-role="note"]').evaluateAll(nodes=>nodes.map(n=>({x:n.getAttribute('x'),y:n.getAttribute('y'),size:n.getAttribute('font-size'),text:n.textContent})))).toEqual(engraved);expect(await currentProject(page)).toEqual(before);
});
