import { test,expect,type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
async function projects(page:Page){return page.evaluate(()=>new Promise<any[]>((resolve,reject)=>{const request=indexedDB.open('soratro',2);request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,read=db.transaction('projects').objectStore('projects').getAll();read.onsuccess=()=>{resolve(read.result);db.close();};read.onerror=()=>reject(read.error);};}));}
async function saved(page:Page){await expect(page.locator('.save-state')).toContainText('Sauvegardé');}
async function closeDialog(page:Page){await page.locator('dialog[open] > header button[aria-label="Fermer"]').click();}
test('Web Audio réel, métronome, transport, boucle, IndexedDB et cadres mobiles V0.1 conservés',async({page},info)=>{
  await page.goto('http://127.0.0.1:4175/tests/browser.html');await page.getByRole('button',{name:'Lancer les tests fonctionnels'}).click();await expect(page.locator('#results')).toContainText('Tests terminés.');const text=await page.locator('#results').innerText();expect(text).not.toContain('FAIL');expect(text.match(/PASS/g)?.length).toBe(7);await info.attach('Banc audio réel',{body:text,contentType:'text/plain'});
});
test('REC PC, paroles/repère, PDF/SVG/PNG, export suppression import exact et redémarrage hors ligne',async({page,context},info)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');await page.getByRole('button',{name:'Nouvelle partition',exact:true}).click();await page.getByLabel('Titre',{exact:true}).fill('QA SORATRO');await page.getByRole('button',{name:'Créer la partition'}).click();await page.getByLabel('Tempo BPM').fill('160');await page.getByLabel('Décompte avant enregistrement').selectOption('2');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.locator('.transport-state')).toContainText('Enregistrement · Soprano');await page.keyboard.down('a');await page.waitForTimeout(180);await page.keyboard.up('a');await page.getByRole('button',{name:'Stop',exact:true}).click();await saved(page);let current=(await projects(page))[0];expect(current.tracks[0].events.length).toBe(1);expect(current.tracks[0].events[0].midiPitch).toBe(60);expect(current.tracks[0].events[0].duration).toBeGreaterThan(.1);
  await page.getByRole('button',{name:'Paroles',exact:true}).click();await page.getByRole('button',{name:'+ Couplet'}).click();await page.getByLabel('Texte des paroles').fill('Ry');await page.getByRole('button',{name:'Découper',exact:true}).click();await page.getByRole('button',{name:'Aligner dès le curseur'}).click();await page.getByRole('button',{name:'Structure',exact:true}).click();await page.getByLabel('Repère',{exact:true}).fill('INTRO');await page.getByRole('button',{name:'Ajouter repère'}).click();await closeDialog(page);await saved(page);current=(await projects(page))[0];expect(current.lyrics[0].syllables[0].noteId).toBe(current.tracks[0].events[0].id);expect(current.markers[0].label).toBe('INTRO');
  await page.getByRole('button',{name:'PDF / Export'}).click();for(const [label,extension,signature] of [['Exporter PDF','pdf','%PDF-'],['SVG','svg','<svg'],['PNG','png','']] as const){const waiting=page.waitForEvent('download');await page.getByRole('button',{name:label,exact:true}).click();const download=await waiting;expect(download.suggestedFilename()).toMatch(new RegExp('\\.'+extension+'$'));const bytes=await readFile((await download.path())!);expect(bytes.length).toBeGreaterThan(1000);if(signature)expect(bytes.toString('utf8').startsWith(signature)).toBeTruthy();else expect(bytes.subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a');await download.saveAs(info.outputPath('partition.'+extension));}await closeDialog(page);await saved(page);
  const before=JSON.parse(JSON.stringify((await projects(page))[0]));const waiting=page.waitForEvent('download');await page.getByTitle('Exporter le projet complet .soratro').click();const exported=await waiting,file=info.outputPath('composition.soratro');await exported.saveAs(file);await page.getByRole('button',{name:'Mes partitions',exact:true}).click();await page.getByRole('button',{name:'Options QA SORATRO'}).click();await page.locator('.dropdown').getByRole('button',{name:'Supprimer',exact:true}).click();await page.getByRole('button',{name:'Supprimer',exact:true}).click();await expect(page.locator('.project-row')).toHaveCount(0);await page.locator('input[type=file]').setInputFiles(file);await saved(page);expect(JSON.parse(JSON.stringify((await projects(page))[0]))).toEqual(before);
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBeTruthy();await context.setOffline(true);await page.reload();await expect(page.locator('.project-title')).toContainText('QA SORATRO');await page.getByRole('button',{name:'Répétition',exact:true}).click();await expect(page.locator('.rehearsal-panel')).toBeVisible();await page.getByRole('button',{name:'PDF / Export'}).click();const offline=page.waitForEvent('download');await page.getByRole('button',{name:'Exporter PDF',exact:true}).click();expect((await offline).suggestedFilename()).toMatch(/\.pdf$/);expect(errors).toEqual([]);
});
for(const viewport of [{width:390,height:844},{width:740,height:390}])test('Pointer Events multitouch et composition '+viewport.width+'×'+viewport.height,async({browser},info)=>{
  const context=await browser.newContext({viewport,hasTouch:true,isMobile:true});const page=await context.newPage();await page.goto('http://127.0.0.1:4176/soratro/');await page.getByRole('button',{name:'Ouvrir l’étude SATB en 6/8'}).click();await page.getByRole('button',{name:'Enregistrement',exact:true}).click();await page.getByLabel('Décompte (mesures)').selectOption('0');await closeDialog(page);await page.getByRole('button',{name:'Enregistrer',exact:true}).click();const keys=[page.getByRole('button',{name:'Jouer C4',exact:true}),page.getByRole('button',{name:'Jouer D4',exact:true})];const points=[];for(let i=0;i<keys.length;i++){const box=await keys[i].boundingBox();expect(box).toBeTruthy();points.push({id:i+1,x:box!.x+box!.width/2,y:box!.y+box!.height*.8});}const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});await page.waitForTimeout(300);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.getByRole('button',{name:'Stop',exact:true}).click();await saved(page);const data=(await projects(page))[0];expect(data.tracks[0].events.length).toBe(26);expect(data.tracks[0].events.slice(-2).map((n:any)=>n.midiPitch).sort()).toEqual([60,62]);expect(await page.locator('.piano-white.pressed,.piano-black.pressed').count()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(viewport.width+1);const rec=await page.getByRole('button',{name:'Enregistrer',exact:true}).boundingBox();expect(rec!.height).toBeGreaterThanOrEqual(44);await page.screenshot({path:info.outputPath('mobile.png'),fullPage:true});await context.close();
});
