import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createProject,makeNote,noteDuration} from '../../src/music/model';
import {loadScore,currentProject} from './helpers';
test('Solfa preferences remain visual, voice colors persist, black export and print match the same preview',async({page},info)=>{
  await page.addInitScript(()=>{window.print=function(){(window as any).qaPrinted=true;};});
  const p=createProject({title:'Préférences SATB'});p.tracks[0].events=[makeNote('soprano',65,.5,.5,72)];await loadScore(page,p);await page.getByRole('button',{name:'Partition',exact:true}).click();const before=await currentProject(page);
  await expect(page.locator('.composition .engraved-content text').filter({hasText:/^0$/})).toHaveCount(0);
  await page.getByRole('button',{name:'Paramètres',exact:true}).click();await page.getByLabel('Préréglage Solfa').selectOption('Détaillé');await page.getByLabel('Synchroniser les vues').uncheck();await page.locator('dialog > header').getByRole('button',{name:'Fermer'}).click();
  expect(await page.locator('.composition .engraved-content text').filter({hasText:/^0$/}).count()).toBeGreaterThan(0);expect(await currentProject(page)).toEqual(before);
  await page.getByLabel('Couleur Soprano',{exact:true}).fill('#7c3aed');await page.getByRole('button',{name:'PDF / Export'}).click();let dialog=page.locator('dialog');await expect(dialog.getByLabel('Utiliser les couleurs des voix dans l’export')).not.toBeChecked();
  const music=dialog.locator('.engraved-content [data-note-id]');await expect(music.first()).toHaveAttribute('fill','#26232d');await dialog.getByLabel('Utiliser les couleurs des voix dans l’export').check();await expect(music.first()).toHaveAttribute('fill','#7c3aed');
  const svgDownload=page.waitForEvent('download');await dialog.getByRole('button',{name:'SVG',exact:true}).click();const svg=await svgDownload;const svgText=await readFile((await svg.path())!,'utf8');expect(svgText).toContain('fill="#7c3aed"');await svg.saveAs(info.outputPath('couleurs.svg'));
  const expectedPages=await dialog.locator('.engraved-page').count();await dialog.getByRole('button',{name:'Imprimer',exact:true}).click();const frame=page.frameLocator('.print-frame');await expect(frame.locator('.page')).toHaveCount(expectedPages);await expect(frame.locator('text').filter({hasText:'Préférences SATB'}).first()).toBeVisible();expect(await frame.locator('[data-note-id]').count()).toBe(await music.count());
  await dialog.getByRole('button',{name:'Annuler',exact:true}).click();await page.waitForTimeout(200);await page.reload();await expect(page.getByLabel('Couleur Soprano',{exact:true})).toHaveValue('#7c3aed');await page.getByRole('button',{name:'Paramètres',exact:true}).click();await expect(page.getByLabel('Afficher les silences')).toBeChecked();await expect(page.getByLabel('Synchroniser les vues')).not.toBeChecked();await page.getByLabel('Préréglage Solfa').selectOption('Épuré');await page.locator('dialog > header').getByRole('button',{name:'Fermer'}).click();await expect(page.locator('.composition .engraved-content text').filter({hasText:/^0$/})).toHaveCount(0);
  await page.getByRole('button',{name:'Couleur d’origine Soprano'}).click();await expect(page.getByLabel('Couleur Soprano',{exact:true})).toHaveValue(p.tracks[0].color);
});
test('Export errors retain settings and release busy state; retry, Escape focus and PNG/SVG/PDF scopes work',async({browser},info)=>{
  const context=await browser.newContext({serviceWorkers:'block',viewport:{width:1360,height:960}}),page=await context.newPage();const p=createProject({title:'Exports avec reprise'});p.settings.measureCount=12;p.tracks[0].events=Array.from({length:72},(_,i)=>makeNote('soprano',65+i%5,i*.5,.5,72));await loadScore(page,p);await page.getByRole('button',{name:'PDF / Export'}).click();const dialog=page.locator('dialog');await dialog.getByLabel('Papier',{exact:true}).selectOption('A5');
  await page.route('**/ScoreFont-*.ttf',route=>route.abort());await dialog.getByRole('button',{name:'Exporter PDF'}).click();await expect(dialog.getByRole('alert')).toContainText(/fetch|police|Failed/i);await expect(dialog.getByRole('button',{name:'Exporter PDF'})).toBeEnabled();await expect(dialog.getByLabel('Papier',{exact:true})).toHaveValue('A5');await page.unroute('**/ScoreFont-*.ttf');
  const pdfWait=page.waitForEvent('download');await dialog.getByRole('button',{name:'Exporter PDF'}).click();const pdf=await pdfWait;expect((await readFile((await pdf.path())!)).subarray(0,5).toString()).toBe('%PDF-');await pdf.saveAs(info.outputPath('reprise.pdf'));
  await dialog.getByLabel('Portée de l’export').selectOption('measures');await dialog.getByLabel('De la mesure').fill('2');await dialog.getByLabel('À la mesure').fill('3');expect(await dialog.locator('.engraved-content [data-note-id]').count()).toBe(12);
  for(const [format,signature] of [['PNG','89504e470d0a1a0a'],['SVG','']] as const){const waiting=page.waitForEvent('download');await dialog.getByRole('button',{name:format,exact:true}).click();const download=await waiting,bytes=await readFile((await download.path())!);if(signature)expect(bytes.subarray(0,8).toString('hex')).toBe(signature);else expect(bytes.toString()).toContain('<svg');await download.saveAs(info.outputPath('mesures.'+format.toLowerCase()));}
  await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(page.getByRole('button',{name:'PDF / Export'})).toBeFocused();await page.getByRole('button',{name:'PDF / Export'}).click();await expect(page.locator('dialog').getByLabel('Papier',{exact:true})).toHaveValue('A5');await context.close();
});
test('Cold offline restart retains composition, preferences, editing, immersion, audio and PDF export',async({page,context},info)=>{
  const p=createProject({title:'Atelier hors ligne'}),id=makeNote('soprano',65,0,1,72);p.tracks[0].events=[id];await loadScore(page,p);await page.getByRole('tab',{name:'Piano Roll',exact:true}).click();await page.getByRole('button',{name:'Masquer le clavier piano'}).click();await page.getByRole('button',{name:'État du panneau des pistes'}).click();await page.getByRole('button',{name:'Mode Immersion'}).click();await page.waitForTimeout(250);await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBeTruthy();
  await context.setOffline(true);await page.reload();await expect(page.locator('.app')).toHaveAttribute('data-immersion','true');await page.getByRole('button',{name:'Quitter Immersion'}).click();await expect(page.locator('.piano-dock')).toBeHidden();await expect(page.locator('.tracks-panel')).toHaveClass(/compact-tracks/);await page.getByRole('button',{name:'Partition',exact:true}).click();await page.locator('.composition .engraved-content [data-note-id="'+id.id+'"]').click();await page.getByLabel('Durée de la note').fill('2');expect(noteDuration((await currentProject(page)).tracks[0].events[0])).toBe(2);
  await page.getByRole('button',{name:'Lecture',exact:true}).click();await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeVisible();await page.getByRole('button',{name:'Stop',exact:true}).click();await page.getByRole('button',{name:'PDF / Export'}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exporter PDF'}).click();await (await download).saveAs(info.outputPath('offline.pdf'));await page.locator('dialog > header').getByRole('button',{name:'Fermer'}).click();await page.reload();expect(noteDuration((await currentProject(page)).tracks[0].events[0])).toBe(2);
});
