import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createProject,makeNote,id,type Project} from '../../src/music/model';
import {splitLyrics,assignSequential} from '../../src/lyrics/lyrics';
import {loadScore,currentProject} from './helpers';
function fixture():Project{const p=createProject({title:'Chœur traditionnel',timeSignature:'4/4',tonic:'Db'});p.settings.measureCount=8;for(const t of p.tracks)t.events=Array.from({length:32},(_,i)=>makeNote(t.id,61+(i%4)*2,i,1,72));const line={id:id(),trackId:'soprano',kind:'verse' as const,verse:1,text:'Ry mpa-nom-po tsa-ra',syllables:splitLyrics('Ry mpa-nom-po tsa-ra')};p.lyrics=[line];assignSequential(p,line.id);return p;}
const scoreNote=(page:any,id:string)=>page.locator('.composition .engraved-content [data-note-id="'+id+'"]');
test('Common lyrics use one text, independent voice links, reversible rhythm fallback and portable export',async({page})=>{
 const p=fixture();await loadScore(page,p);await page.getByRole('button',{name:'Partition',exact:true}).click();await page.getByRole('button',{name:'Paroles',exact:true}).first().click();await page.locator('.shared-lyrics-settings summary').click();for(const name of ['Alto','Ténor','Basse'])await page.locator('.shared-lyrics-settings').getByLabel(name,{exact:true}).check();let current=await currentProject(page);expect(current.sharedLyrics).toHaveLength(1);expect(current.lyrics).toHaveLength(4);await expect(page.locator('.composition text[data-score-role=lyric]').filter({hasText:/^mpa-$/})).toHaveCount(1);
 const links=current.lyrics.map((l:any)=>l.syllables.map((s:any)=>s.noteIds));await page.getByLabel('Syllabe suivante').click();await page.getByLabel('Corriger la syllabe').fill('fan');current=await currentProject(page);expect(current.lyrics.every((l:any)=>l.text.includes('fan-')&&l.syllables[1].text==='fan')).toBeTruthy();expect(current.lyrics.map((l:any)=>l.syllables.map((s:any)=>s.noteIds))).toEqual(links);
 await page.getByRole('button',{name:'Fermer les paroles',exact:true}).click();await scoreNote(page,p.tracks[1].events[0].id).click();await page.getByLabel('Durée de la note').fill('0.5');await expect(page.locator('.composition text[data-score-role=lyric]').filter({hasText:/^fan-$/})).toHaveCount(4);await page.getByRole('button',{name:'Annuler',exact:true}).click();await await expect(page.locator('.composition text[data-score-role=lyric]').filter({hasText:/^fan-$/})).toHaveCount(1);
 const wait=page.waitForEvent('download');await page.getByRole('button',{name:'.soratro',exact:true}).click();const saved=JSON.parse(await readFile((await (await wait).path())!,'utf8'));expect(saved.project.sharedLyrics[0].syllables[1].text).toBe('fan');expect(saved.project.lyrics).toHaveLength(4);
});
test('Page layout previews cancel cleanly; styles survive reload and apply in one undoable change',async({page},info)=>{
 const p=fixture();await loadScore(page,p);await page.getByRole('button',{name:'Partition',exact:true}).click();const before=await currentProject(page);await page.getByRole('tab',{name:'Mise en page de la partition'}).click();let dialog=page.locator('dialog');await dialog.getByLabel('Papier de mise en page').selectOption('A5');await dialog.getByLabel('Mesures par ligne',{exact:true}).fill('2');await dialog.getByRole('button',{name:'En-tête',exact:true}).click();await dialog.getByLabel('Police du champ').first().selectOption('serif');await dialog.getByLabel('Italique',{exact:true}).first().check();await dialog.getByRole('button',{name:'Styles',exact:true}).click();await dialog.getByLabel('Nom du style').fill('Chorale A5');await dialog.getByRole('button',{name:'Enregistrer un nouveau style'}).click();await dialog.getByRole('button',{name:'Annuler l’aperçu'}).click();expect(await currentProject(page)).toEqual(before);
 await page.reload();await page.getByRole('button',{name:'Réglages de mise en page'}).click();dialog=page.locator('dialog');await dialog.getByRole('button',{name:'Styles',exact:true}).click();await dialog.getByLabel('Style enregistré').selectOption({label:'Chorale A5'});await dialog.getByRole('button',{name:'Prévisualiser ce style'}).click();expect((await currentProject(page)).layout.paper).toBe('A4');await page.screenshot({path:info.outputPath('style-preview.png')});await dialog.getByRole('button',{name:'Appliquer la mise en page'}).click();const after=await currentProject(page);expect(after.layout.paper).toBe('A5');expect(after.layout.header[0].font).toBe('serif');expect(after.layout.header[0].italic).toBeTruthy();expect(after.tracks).toEqual(before.tracks);expect(after.lyrics).toEqual(before.lyrics);await page.getByRole('button',{name:'Annuler',exact:true}).click();expect((await currentProject(page)).layout).toEqual(before.layout);
});
test('Manual measure/page breaks and widths are previewed, resettable and preserve notes',async({page})=>{
 const p=fixture();await loadScore(page,p);await page.getByRole('button',{name:'Partition',exact:true}).click();await page.getByRole('tab',{name:'Mise en page de la partition'}).click();const dialog=page.locator('dialog');await dialog.getByRole('button',{name:'Mesures et systèmes',exact:true}).click();await dialog.getByText('Exceptions locales et sauts',{exact:true}).click();await dialog.getByLabel('Mesure à régler').fill('2');await dialog.getByLabel('Saut de page après cette mesure').check();await dialog.getByLabel('Largeur relative de la mesure').fill('1.5');await dialog.getByRole('button',{name:'Appliquer la mise en page'}).click();let current=await currentProject(page);expect(current.layout.pageBreaks).toEqual([2]);expect(current.layout.measureWidths['2']).toBe(1.5);expect(current.tracks).toEqual(p.tracks);await page.getByRole('button',{name:'Réglages de mise en page'}).click();await page.locator('dialog').getByRole('button',{name:'Mesures et systèmes',exact:true}).click();await page.getByRole('button',{name:'Réinitialiser les réglages manuels'}).click();await page.getByRole('button',{name:'Appliquer la mise en page'}).click();current=await currentProject(page);expect(current.layout.pageBreaks).toEqual([]);expect(current.layout.measureWidths).toEqual({});
});
test('Symbol objects validate navigation and trigger real D.C. al Fine audio playback; reader clicks do not edit',async({page})=>{
 await page.addInitScript(()=>{const create=AudioContext.prototype.createOscillator;(window as any).qaStarts=[];AudioContext.prototype.createOscillator=function(){const o=create.call(this),start=o.start.bind(o);o.start=function(...args){(window as any).qaStarts.push(o.frequency.value);return start(...args);};return o;};});
 const p=fixture();p.tempo=600;p.settings.measureCount=4;p.lyrics=[];p.tracks.forEach((t,ti)=>{t.mute=ti!==0;t.events=ti===0?[61,63,65,66].map((pitch,i)=>makeNote(t.id,pitch,i*4,1,600)):[];});await loadScore(page,p);await page.getByRole('button',{name:'Partition',exact:true}).click();await page.getByRole('button',{name:'Symboles',exact:true}).click();let dialog=page.locator('dialog');await dialog.getByLabel('Rechercher un symbole').fill('D.C. al Fine');await dialog.getByRole('button',{name:'D.C. al Fine',exact:true}).click();await dialog.getByLabel('Mesure du symbole').fill('4');await dialog.getByRole('button',{name:'Ajouter le symbole'}).click();await dialog.getByRole('button',{name:'Fermer',exact:true}).click();await page.getByRole('button',{name:'Vérifier',exact:true}).click();await await expect(page.locator('.score-issues')).toContainText('sans Fine');await page.locator('dialog').getByRole('button',{name:'Fermer',exact:true}).click();
 await page.getByRole('button',{name:'Symboles',exact:true}).click();dialog=page.locator('dialog');await dialog.getByLabel('Rechercher un symbole').fill('Fine');await dialog.getByRole('button',{name:'Fine',exact:true}).click();await dialog.getByLabel('Mesure du symbole').fill('2');await dialog.getByRole('button',{name:'Ajouter le symbole'}).click();await dialog.getByRole('button',{name:'Fermer',exact:true}).click();await page.getByRole('tab',{name:'Lecture de la partition'}).click();const before=await currentProject(page);await scoreNote(page,p.tracks[0].events[0].id).click();await page.keyboard.press('ArrowUp');expect(await currentProject(page)).toEqual(before);await await expect(page.locator('.note-inspector')).toBeHidden();await page.getByRole('button',{name:'Lecture',exact:true}).click();await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Lecture',exact:true})).toBeVisible({timeout:8000});const starts=await page.evaluate(()=>(window as any).qaStarts);expect(starts.length).toBe(12);const pitches=starts.filter((_:any,i:number)=>i%2===0);expect(pitches.map((f:number)=>Math.round(69+12*Math.log2(f/440)))).toEqual([61,63,65,66,61,63]);
});
for(const viewport of [{width:390,height:844},{width:740,height:390}])test('Traditional page editor and embedded fonts export offline at '+viewport.width+'×'+viewport.height,async({page,context},info)=>{
 await page.setViewportSize(viewport);const p=fixture();p.tracks[0].events[0].midiPitch=85;await loadScore(page,p);await page.getByRole('button',{name:'Partition',exact:true}).click();await page.getByRole('tab',{name:'Mise en page de la partition'}).click();let dialog=page.locator('dialog');await dialog.getByRole('button',{name:'Paramètres de mise en page',exact:true}).click();await dialog.getByRole('button',{name:'En-tête',exact:true}).click();await dialog.getByLabel('Police du champ').first().selectOption('serif');await dialog.getByLabel('Italique',{exact:true}).first().check();await dialog.getByRole('button',{name:'Appliquer la mise en page'}).click();await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBeTruthy();await context.setOffline(true);await page.reload();await expect(page.getByRole('button',{name:'Réglages de mise en page'})).toBeVisible();await page.getByRole('button',{name:'PDF / Export'}).click();dialog=page.locator('dialog');await expect(dialog.getByRole('button',{name:'Exporter PDF'})).toBeInViewport();const waiting=page.waitForEvent('download');await dialog.getByRole('button',{name:'Exporter PDF'}).click();const downloaded=await waiting;const bytes=await readFile((await downloaded.path())!);expect(bytes.subarray(0,5).toString()).toBe('%PDF-');await downloaded.saveAs(info.outputPath('traditional-offline.pdf'));await page.screenshot({path:info.outputPath('traditional-mobile-export.png')});expect((await currentProject(page)).layout.header[0].font).toBe('serif');
});
test('Export layout settings are staged, cancellable and explicitly applicable with Undo',async({page})=>{const p=fixture();await loadScore(page,p);const before=await currentProject(page);await page.getByRole('button',{name:'PDF / Export'}).click();let dialog=page.locator('dialog');await dialog.getByLabel('Papier',{exact:true}).selectOption('A5');await dialog.getByLabel('Mesures par ligne',{exact:true}).fill('2');expect((await currentProject(page)).layout).toEqual(before.layout);await dialog.getByRole('button',{name:'Annuler',exact:true}).click();expect(await currentProject(page)).toEqual(before);await page.getByRole('button',{name:'PDF / Export'}).click();dialog=page.locator('dialog');await expect(dialog.getByLabel('Papier',{exact:true})).toHaveValue('A4');await dialog.getByLabel('Papier',{exact:true}).selectOption('A5');await dialog.getByLabel('Mesures par ligne',{exact:true}).fill('2');await dialog.getByRole('button',{name:'Appliquer les réglages'}).click();expect((await currentProject(page)).layout.paper).toBe('A5');await dialog.getByRole('button',{name:'Annuler',exact:true}).click();await page.getByRole('button',{name:'Annuler',exact:true}).click();expect((await currentProject(page)).layout).toEqual(before.layout);});
