import { createDemo,createProject,makeNote,type TrackId } from '../src/music/model.ts';
import { pianoVoice,clickVoice } from '../src/audio/synth.ts';
import { ProjectRepository } from '../src/storage/repository.ts';
import { AudioEngine } from '../src/audio/engine.ts';
import { MidiManager } from '../src/midi/manager.ts';
const results=document.querySelector('#results')!;const lines:string[]=[];
function report(value:string){lines.push(value);results.textContent=lines.join('\n');}
function assert(condition:unknown,message:string){if(!condition)throw new Error(message);}
async function waveform(){const ctx=new OfflineAudioContext(2,48000*3,48000);const output=ctx.createGain();output.gain.value=.8;output.connect(ctx.destination);pianoVoice(ctx,output,61,100,.1,.4);pianoVoice(ctx,output,65,85,.1,.4);pianoVoice(ctx,output,68,75,.1,.4);const buffer=await ctx.startRendering(),samples=buffer.getChannelData(0);const rms=(a:number,b:number)=>Math.sqrt(samples.slice(a*48000,b*48000).reduce((sum,x)=>sum+x*x,0)/((b-a)*48000));assert(rms(.12,.3)>.01,'Le synthétiseur ne produit pas de signal');assert(rms(1,1.5)<.001,'Une note reste bloquée après sa fin');report('PASS · Synthèse piano : accord réel, signal audio présent et extinction après NOTE OFF.');}
async function metronome(){const ctx=new OfflineAudioContext(1,48000*10,48000);const output=ctx.createGain();output.connect(ctx.destination);const pulse=60/72/2;for(let i=0;i<24;i++)clickVoice(ctx,output,.1+i*pulse,i%6===0?2:i%6===3?1:0,.8);const b=await ctx.startRendering(),samples=b.getChannelData(0);const peaks:number[]=[];let sounding=false;for(let i=0;i<samples.length;i++){const above=Math.abs(samples[i])>.004;if(above&&!sounding&&(peaks.length===0||i-peaks[peaks.length-1]>4800)){peaks.push(i);sounding=true;}if(!above)sounding=false;}assert(peaks.length===24,'Nombre de clics incorrect : '+peaks.length);const error=Math.max(...peaks.slice(1).map((p,i)=>Math.abs((p-peaks[i])/48000-pulse)));assert(error<.0002,'Dérive du métronome');const peak=(i:number)=>Math.max(...samples.slice(peaks[i],peaks[i]+1500).map(Math.abs));assert(peak(0)>peak(3)&&peak(3)>peak(1),'Accents 1 / 4 incohérents');report('PASS · Métronome 6/8 : 24 clics sur 4 mesures, espacement '+pulse.toFixed(6)+' s, erreur maximale '+(error*1000).toFixed(3)+' ms, accents 1 et 4.');}
async function scheduling(){const engine=new AudioEngine();const p=createProject({tempo:240,timeSignature:'6/8'});p.tracks.forEach((t,i)=>{t.events=[makeNote(t.id,61-i*5,0,1,240),makeNote(t.id,63-i*5,1.5,.5,240)];});engine.setProject(p);engine.metronome=true;const ctx=await engine.init();const output=ctx.createAnalyser();output.fftSize=2048;ctx.destination.channelCount=2; // The synth and scheduled master continue through their real graph.
  const starts:number[]=[];let maxMeter=0;const unsub=engine.subscribe(s=>{if(s.mode==='playing')starts.push(s.rawBeat);maxMeter=Math.max(maxMeter,s.meter.filter(v=>v>0).length);});await engine.play();await new Promise(resolve=>setTimeout(resolve,330));assert(engine.status==='playing','Le transport ne joue pas');assert(engine.position()>.8,'La tête de lecture ne progresse pas');assert(maxMeter===4,'Les quatre pistes ne sont pas lues ensemble');engine.pause();const paused=engine.position();await new Promise(resolve=>setTimeout(resolve,120));assert(Math.abs(engine.position()-paused)<.001,'Pause ne fige pas la position');await engine.play();await new Promise(resolve=>setTimeout(resolve,80));engine.stop();assert(engine.position()===0&&engine.status==='idle','Stop ne revient pas au début');assert(starts.every((v,i)=>i===0||v>=starts[i-1]-.15),'Transport instable');unsub();output.disconnect();engine.dispose();report('PASS · Lecture SATB réelle : quatre pistes actives, progression, pause/reprise, Stop.');}
async function storage(){const repo=new ProjectRepository();const project=createProject({title:'QA navigateur · stockage',tonic:'Db',timeSignature:'6/8',tempo:72});project.tracks[0].events=[makeNote('soprano',61,.037,.491,72)];await repo.save(project);const fresh=new ProjectRepository();const loaded=await fresh.get(project.id);assert(JSON.stringify(loaded)===JSON.stringify(project),'Projet modifié par IndexedDB');await repo.delete(project.id);report('PASS · IndexedDB réel : écriture, nouvelle connexion, récupération intégrale des événements.');}
async function looping(){const engine=new AudioEngine();const p=createProject({tempo:240,timeSignature:'6/8'});p.settings.loopStart=0;p.settings.loopEnd=1;p.tracks[0].events=[makeNote('soprano',61,0,2,240)];engine.setProject(p);engine.loop=true;try{await engine.play();await new Promise(resolve=>setTimeout(resolve,580));assert(engine.rawBeat()>2&&engine.position()>=0&&engine.position()<1,'La boucle ne revient pas dans ses limites');const before=engine.position();engine.setProject({...p,tempo:120});assert(Math.abs(engine.position()-before)<.12,'Le tempo déplace la position de boucle');engine.pause();const paused=engine.position();await engine.play();assert(Math.abs(engine.position()-paused)<.05,'La reprise de boucle déplace la position');await new Promise(resolve=>setTimeout(resolve,150));assert(engine.status==='playing'&&engine.position()<1,'La boucle s’arrête après la reprise');report('PASS · Boucle audio réelle : répétitions, changement de tempo et pause/reprise dans les limites.');}finally{engine.dispose();}}
async function midiMessages(){const inputs=new Map();const input={id:'qa-midi',name:'Clavier MIDI de test',state:'connected',onmidimessage:null as any};inputs.set(input.id,input);const access={inputs,onstatechange:null};const previous=Object.getOwnPropertyDescriptor(navigator,'requestMIDIAccess');Object.defineProperty(navigator,'requestMIDIAccess',{configurable:true,value:async()=>access});try{const manager=new MidiManager();const notes:number[]=[];let off=0;manager.onNoteOn=(_key,pitch)=>notes.push(pitch);manager.onNoteOff=()=>off++;await manager.connect();input.onmidimessage({data:new Uint8Array([0x90,61,100])});input.onmidimessage({data:new Uint8Array([0x90,65,90])});input.onmidimessage({data:new Uint8Array([0x80,61,0])});input.onmidimessage({data:new Uint8Array([0x90,65,0])});assert(notes.join(',')==='61,65'&&off===2,'Interprétation MIDI incorrecte');report('PASS · Messages MIDI : NOTE ON, NOTE OFF et vélocité zéro. Périphérique physique non présent.');}finally{if(previous)Object.defineProperty(navigator,'requestMIDIAccess',previous);else delete (navigator as any).requestMIDIAccess;}}
async function frames(){const repo=new ProjectRepository();const p=createDemo();p.title='QA mobile · étude SATB';await repo.save(p);for(const key of ['portrait','landscape']){const iframe=document.querySelector('#'+key) as HTMLIFrameElement;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Chargement mobile interrompu')),6000);iframe.onload=()=>{clearTimeout(timer);resolve();};iframe.src='/?qa='+p.id+'#project='+p.id;});const deadline=performance.now()+6000;while(!iframe.contentDocument?.querySelector('.piano-keybed')&&performance.now()<deadline)await new Promise(resolve=>setTimeout(resolve,50));const doc=iframe.contentDocument!;assert(doc.querySelector('.piano-keybed'),'Clavier absent dans '+key);assert(doc.documentElement.scrollWidth<=iframe.clientWidth+1,'Débordement horizontal dans '+key);assert(doc.querySelector('button[aria-label="Enregistrer"]'),'REC absent sur mobile');}report('PASS · Cadres mobiles 390×844 et 740×390 : interface réelle, clavier, REC et absence de débordement horizontal.');report('NOTE · Le navigateur de prévisualisation utilise HTTP. L’installation PWA et le redémarrage hors ligne demandent une origine sécurisée.');}
document.querySelector('#run')!.addEventListener('click',async()=>{lines.length=0;report('Tests en cours…');for(const test of [waveform,metronome,scheduling,looping,storage,midiMessages,frames]){try{await test();}catch(error){report('FAIL · '+(error instanceof Error?error.message:String(error)));}}report('Tests terminés.');});
