import test from 'node:test';import assert from 'node:assert/strict';
import { createProject,makeNote,noteStart,noteDuration } from '../src/music/model.ts';
import { copyMeasures,editMeasures,pasteBlock,transpose } from '../src/music/editing.ts';
import { measures,measureAt,measureForBeat,secondsBetween,beatAfterSeconds,transportBeat,transportSeconds,displayedTempo } from '../src/music/timeline.ts';
import { validateProject } from '../src/storage/migrations.ts';
import { quantize,quantizeForProject,snapForProject,gridStep,restoreOriginal } from '../src/quantization/quantizer.ts';
import { estimateLatency } from '../src/recording/calibration.ts';
test('Compound tempo units change the expression, not beat positions or speed',()=>{const p=createProject({tempo:108});const before=secondsBetween(p,0,3);p.settings.tempoUnit='dotted-quarter';assert.equal(displayedTempo(p),72);assert.equal(secondsBetween(p,0,3),before);assert.equal(measures(p,3)[2].start,6);});
test('Pickup and signature changes share a measure map, including custom 7/8 grouping',()=>{const p=createProject({timeSignature:'4/4'});p.settings.pickupBeats=1;p.signatureMap=[{measure:3,signature:'7/8',groups:[2,2,3]}];const rows=measures(p,4);assert.deepEqual(rows.map(m=>[m.start,m.end]),[[0,1],[1,5],[5,8.5],[8.5,12]]);assert.deepEqual(rows[2].groups,[2,2,3]);assert.equal(measureForBeat(p,5).number,3);});
test('Tempo-map beat/time transforms and repeated-loop clock remain inverse',()=>{const p=createProject({tempo:60,timeSignature:'4/4'});p.tempoMap=[{measure:2,bpm:120}];assert.equal(secondsBetween(p,0,8),6);assert.equal(beatAfterSeconds(p,0,6),8);const loop={start:2,end:8};for(const raw of [0,3,8,10,20,100])assert.ok(Math.abs(transportBeat(p,0,transportSeconds(p,0,raw,loop),loop)-raw)<1e-8);});
test('Multi-voice measure copying creates unique notes and remaps syllables without touching raw timing',()=>{const p=createProject({timeSignature:'4/4'});p.tracks.forEach(t=>t.events=[makeNote(t.id,60,4,1,72)]);p.lyrics=[{id:'lyrics',trackId:'soprano',text:'Ry',syllables:[{text:'Ry',noteId:p.tracks[0].events[0].id}]}];const raw=p.tracks[0].events[0].startTime;const block=copyMeasures(p,2,2,'all');pasteBlock(p,block,4,'all');assert.equal(p.tracks[0].events.length,2);assert.equal(noteStart(p.tracks[0].events[1]),16);assert.equal(p.tracks[0].events[1].startTime,raw);assert.notEqual(p.tracks[0].events[0].id,p.tracks[0].events[1].id);assert.equal(p.lyrics[0].syllables[1].noteId,p.tracks[0].events[1].id);});
test('Delete and move a block preserve outside passages and all voices consistently',()=>{const p=createProject({timeSignature:'4/4'});p.tracks.forEach(t=>t.events=[0,4,8,12,16].map((b,i)=>makeNote(t.id,60+i,b,1,72)));editMeasures(p,'move',2,3,'all',5);assert.deepEqual(p.tracks[0].events.map(n=>[noteStart(n),n.midiPitch]).sort((a,b)=>a[0]-b[0]),[[0,60],[4,63],[8,64],[12,61],[16,62]]);editMeasures(p,'clear',1,1,'soprano');assert.equal(p.tracks[0].events.length,4);assert.equal(p.tracks[1].events.length,5);});
test('Clipping a sustained note preserves both outside fragments and transposition refuses overflow atomically',()=>{const p=createProject({timeSignature:'4/4'});p.tracks[0].events=[makeNote('soprano',126,0,12,72)];editMeasures(p,'clear',2,2,'all');assert.deepEqual(p.tracks[0].events.map(n=>[noteStart(n),noteDuration(n)]),[[0,4],[8,4]]);assert.throws(()=>transpose(p,2),/dépasser/);assert.ok(p.tracks[0].events.every(n=>n.midiPitch===126));});
test('Auto quantize chooses a credible coarse grid, triplets work, and edits survive restoration',()=>{const notes=[0,1,2,3].map(b=>makeNote('soprano',60,b+.03,.95,72));assert.equal(gridStep('auto',notes),1);const triplets=[0,1/3,2/3].map(b=>makeNote('soprano',60,b+.015,.30,72));assert.equal(gridStep('auto',triplets),1/3);assert.ok(Math.abs(quantize(triplets,'triplet-eighth',100)[1].quantizedStart!-1/3)<1e-8);notes[0].editStart=8;assert.equal(noteStart(restoreOriginal(quantize(notes,'1/8',100))[0]),8);});
test('Quarter quantization respects a half-beat pickup and the off-center downbeats of 7/8',()=>{const p=createProject({timeSignature:'7/8'});p.settings.pickupBeats=.5;const notes=[.52,1.51,2.53,4.02,5.01].map(b=>makeNote('soprano',60,b,.96,72));const result=quantizeForProject(p,notes,'1/4',100);assert.deepEqual(result.map(noteStart),[.5,1.5,2.5,4,5]);assert.deepEqual(restoreOriginal(result),notes);});
test('Latency calibration rejects erratic taps and robustly compensates regular delayed taps',()=>{const good=estimateLatency([99,90,40,45,42,41,43,42,44,40,200]);assert.equal(good.valid,true);assert.ok(Math.abs(good.compensationMs+42)<=2);assert.ok(good.spreadMs<5);assert.equal(estimateLatency([0,0,170,-180,200,-190,150,-140,120,-130]).valid,false);assert.equal(estimateLatency([42,42]).valid,false);});
test('Moving a passage preserves changing signatures, tempos, markers, endings and take selection',()=>{const p=createProject({timeSignature:'4/4',tempo:60});p.settings.measureCount=8;p.signatureMap=[{measure:3,signature:'6/8'},{measure:4,signature:'2/4'},{measure:5,signature:'4/4'}];p.tempoMap=[{measure:2,bpm:90},{measure:4,bpm:120},{measure:5,bpm:60}];p.markers=[{id:'marker',measure:3,label:'PONT'}];p.repeats=[{id:'repeat',startMeasure:2,endMeasure:3,times:2,firstEndingStart:3,secondEndingEnd:4}];p.tracks.forEach(t=>t.events=[1,2,3,4,5,6,7,8].map(m=>makeNote(t.id,60+m,measureAt(p,m).start,1,60)));const selected=p.tracks[0].events.slice(1,4);p.takes=[{id:'take',name:'Take 1',trackId:'soprano',startBeat:4,endBeat:13,createdAt:p.createdAt,events:structuredClone(selected),selected:true,mode:'overdub'}];editMeasures(p,'move',2,4,'all',7);assert.deepEqual(measures(p,8).map(m=>m.signature),['4/4','4/4','4/4','4/4','4/4','6/8','2/4','4/4']);assert.deepEqual(p.tracks[0].events.map(n=>[measureForBeat(p,noteStart(n)).number,n.midiPitch]).sort((a,b)=>a[0]-b[0]),[[1,61],[2,65],[3,66],[4,67],[5,62],[6,63],[7,64],[8,68]]);assert.equal(p.markers[0].measure,6);assert.equal(p.repeats[0].startMeasure,5);assert.equal(p.repeats[0].firstEndingStart,6);assert.equal(p.repeats[0].secondEndingEnd,7);assert.equal(p.takes.length,1);assert.deepEqual(p.takes[0].events.map(n=>n.id),p.tracks[0].events.filter(n=>[62,63,64].includes(n.midiPitch)).map(n=>n.id));assert.equal(secondsBetween(p,measureAt(p,7).start,measureAt(p,7).end),1);validateProject(p);});

test('A coarse grid retains pickup and irregular final downbeats instead of snapping across the bar',()=>{const p=createProject({timeSignature:'7/8'});p.settings.pickupBeats=.5;assert.equal(snapForProject(p,.48,1),.5);assert.equal(snapForProject(p,3.95,1),4);assert.equal(snapForProject(p,4.02,1),4);const note=makeNote('soprano',60,3.95,.96,72);assert.equal(noteStart(quantizeForProject(p,[note],'1/4',100)[0]),4);assert.equal(noteStart(quantizeForProject(p,[note],'1/4',50)[0]),3.975);assert.equal(note.originalStart,3.95);});
