import test from 'node:test';import assert from 'node:assert/strict';import { readFileSync,mkdirSync,writeFileSync } from 'node:fs';
import { createDemo,createProject,makeNote,id } from '../src/music/model.ts';
import { assignSequential,splitLyrics } from '../src/lyrics/lyrics.ts';
import { engraveProject,pageSVG,systemPage,paperSize } from '../src/score/engraving.ts';
import { textWidth } from '../src/score/font-metrics.ts';
import { pdfBytes } from '../src/score/export.ts';
import { durationValue } from '../src/music/durations.ts';
test('Solfa pages share vertical anchors, aligned verses, melismas, dynamic widths and forced system breaks',()=>{const p=createDemo();p.lyrics[0].syllables=splitLyrics(p.lyrics[0].text);assignSequential(p,p.lyrics[0].id);p.lyrics[0].syllables[0].noteIds=p.tracks[0].events.slice(0,3).map(n=>n.id);p.layout.systemBreaks=[2];p.markers=[{id:id(),measure:1,label:'INTRO'}];const doc=engraveProject(p);assert.equal(doc.systems[0].last,2);assert.equal(doc.systems[1].first,3);assert.equal(doc.pages[0].widthMm,210);const svg=pageSVG(doc.pages[0]);assert.match(svg,/Ry/);assert.match(svg,/INTRO/);assert.match(svg,/data-note-id=/);assert.match(svg,/stroke-width="0.65"/);assert.ok(doc.pages[0].ops.some(op=>op.kind==='text'&&op.text==='S'));assert.ok(doc.pages[0].ops.some(op=>op.kind==='text'&&op.text==='A'));const crop=systemPage(doc.pages[0],doc.systems[0]);assert.ok(crop.height<doc.pages[0].height);});
test('A4/A5/Letter orientations use physical dimensions, SVG escapes text, and duration semantics are independent',()=>{const p=createProject();p.layout.paper='A5';p.layout.orientation='landscape';assert.equal(paperSize(p).widthMm,210);assert.equal(paperSize(p).heightMm,148);p.layout.paper='Letter';assert.equal(paperSize(p).heightMm,215.9);p.title='<script>alert("x")</script>';assert.match(pageSVG(engraveProject(p).pages[0]),/&lt;script&gt;/);assert.ok(!pageSVG(engraveProject(p).pages[0]).includes('<script>'));assert.deepEqual(durationValue(1.5),{name:'quarter',beats:1.5,dots:1});assert.equal(durationValue(1/3)!.tuplet,3);});
test('100-measure SATB composition paginates without missing measures and produces a real Unicode vector PDF',async()=>{const p=createProject({title:'SORATRO — Étude chorale',composer:'Composition de vérification',tempo:108});p.settings.tempoUnit='dotted-quarter';p.settings.measureCount=100;for(const [ti,t] of p.tracks.entries())t.events=Array.from({length:600},(_,i)=>makeNote(t.id,[61,63,65,66,68,70][i%6]-ti*5,i*.5,.5,108));p.lyrics=[1,2].map(verse=>({id:id(),trackId:'soprano',verse,kind:'verse' as const,text:'Ry mpa-nom-po tsa-ra',syllables:splitLyrics(Array.from({length:100},()=>verse===1?'Ry mpa-nom-po tsa-ra':'A-me-na ho a-nao').join(' '))}));p.lyrics.forEach(l=>assignSequential(p,l.id));p.markers=[{id:id(),measure:1,label:'INTRO'},{id:id(),measure:25,label:'COUPLET'},{id:id(),measure:65,label:'REFRAIN'}];p.repeats=[{id:id(),startMeasure:25,endMeasure:28,times:2}];const before=process.memoryUsage().heapUsed,start=performance.now(),doc=engraveProject(p);assert.ok(performance.now()-start<4000,'Long-score engraving took more than four seconds');assert.ok(process.memoryUsage().heapUsed-before<150*1024*1024);assert.equal(doc.measureCount,100);assert.equal(doc.systems.flatMap(s=>s.measures).length,100);assert.ok(doc.pages.length>1);for(const page of doc.pages)for(const op of page.ops){assert.ok(op.x>=0&&op.y>=0&&op.y<=page.height,JSON.stringify(op));if(op.kind==='text')assert.ok(op.x+textWidth(op.text,op.size)<=page.width+1,'Clipped text: '+op.text);if(op.kind==='line')assert.ok(op.x2<=page.width&&op.y2<=page.height);}
 const font=readFileSync('src/assets/ScoreFont.ttf').toString('base64');const bytes=await pdfBytes(doc,font,p);assert.equal(Buffer.from(bytes).subarray(0,5).toString(),'%PDF-');assert.ok(bytes.byteLength>10000);mkdirSync('tmp/pdfs',{recursive:true});writeFileSync('tmp/pdfs/soratro-validation.pdf',Buffer.from(bytes));writeFileSync('tmp/pdfs/page.svg',pageSVG(doc.pages[0],font));});
