import test from 'node:test';
import assert from 'node:assert/strict';
import { createDemo,id,makeNote } from '../src/music/model.ts';
import { encodeProject,decodeProject } from '../src/storage/project-file.ts';
import { migrateProject } from '../src/storage/migrations.ts';
function legacy(){const p:any=createDemo();for(const key of ['markers','takes','tempoMap','signatureMap','repeats','indications','layout'])delete p[key];p.schemaVersion=1;p.settings={countIn:2,quantization:'1/8',quantizationStrength:75,loopStart:3,loopEnd:9};return p;}
test('A portable .soratro preserves voices, raw and quantized data, linked lyrics, loop, markers, takes and layout',async()=>{const p=createDemo();p.tracks[0].events[0].quantizedStart=.125;p.tracks[0].events[0].quantizedDuration=.375;p.lyrics[0].syllables=[{id:id(),text:'Ry',noteIds:[p.tracks[0].events[0].id,p.tracks[0].events[1].id]}];p.markers=[{id:id(),measure:3,label:'REFRAIN'}];p.takes=[{id:id(),name:'Take 1',trackId:'alto',startBeat:3,endBeat:9,createdAt:p.createdAt,events:[makeNote('alto',58,3,1,72)],selected:false}];p.layout.paper='A5';const encoded=await encodeProject(p);assert.deepEqual(await decodeProject(encoded),p);const changed=JSON.parse(encoded);changed.project.title='Damaged';await assert.rejects(decodeProject(JSON.stringify(changed)),/checksum/);});
test('V0.1 migration preserves exact performances and quarter BPM while adding schema defaults',async()=>{const old=legacy(),before=structuredClone(old);const p=migrateProject(old);assert.equal(p.schemaVersion,2);assert.deepEqual(p.tracks,before.tracks);assert.deepEqual(p.lyrics,before.lyrics);assert.equal(p.settings.countIn,2);assert.equal(p.settings.tempoUnit,'quarter');assert.equal(p.tempo,72);assert.deepEqual(old,before);assert.deepEqual(await decodeProject(JSON.stringify(old)),p);});
test('Future schemas, non-finite values, duplicate notes and broken syllable links are refused before import',async()=>{assert.throws(()=>migrateProject({...createDemo(),schemaVersion:999}),/plus récente/);const p=createDemo();p.tracks[0].events[0].originalStart=NaN;assert.throws(()=>migrateProject(p),/Début/);p.tracks[0].events[0].originalStart=0;p.tracks[0].events.push({...p.tracks[0].events[0]});assert.throws(()=>migrateProject(p),/double/);p.tracks[0].events.pop();p.lyrics[0].syllables=[{text:'lost',noteId:'absent'}];assert.throws(()=>migrateProject(p),/absente/);await assert.rejects(decodeProject('{'),/JSON/);});
