import test from 'node:test';import assert from 'node:assert/strict';import 'fake-indexeddb/auto';
import { createProject,makeNote,noteStart,noteDuration } from '../src/music/model.ts';
import { Recorder } from '../src/recording/recorder.ts';
import { RecordingSession } from '../src/recording/session.ts';
import { chooseTake } from '../src/recording/takes.ts';
import { ProjectStore } from '../src/storage/store.ts';
import { AudioEngine } from '../src/audio/engine.ts';
import { beatAfterSeconds,secondsBetween } from '../src/music/timeline.ts';
Object.assign(globalThis,{location:{hash:'',pathname:'/'},history:{replaceState(){}}});
test('A held attack crosses a loop before NOTE OFF without waiting for the next scheduler tick',async()=>{const projects=new ProjectStore(),p=createProject({tempo:120});p.settings.loopRecording=true;p.settings.loopStart=3;p.settings.loopEnd=6;await projects.add(p);const engine=new AudioEngine(),internal=engine as any;internal.context={currentTime:10};internal.project=p;internal.mode='recording';internal.originBeat=3;internal.startBeat=3;internal.playbackStart=3;internal.originTime=10;internal.recordOptions={start:3,end:6,preRollStart:3,loop:true,trackId:'soprano'};engine.init=async()=>engine.context!;engine.noteOn=()=>{};engine.noteOff=()=>{};engine.allNotesOff=()=>{};const s=new RecordingSession(engine,projects);Object.assign(s,{baseline:p,armed:true,start:3,end:6});engine.onRecordingStart();internal.context.currentTime=11.25;await s.noteOn('held',65);internal.context.currentTime=11.75;s.noteOff('held');const takes=projects.getSnapshot().project!.takes;assert.equal(takes.length,2);assert.equal(noteStart(takes[0].events[0]),5.5);assert.equal(noteDuration(takes[0].events[0]),.5);assert.equal(noteStart(takes[1].events[0]),3);assert.equal(noteDuration(takes[1].events[0]),.5);assert.equal(takes[0].events[0].rawDurationBeats,.5);assert.equal(takes[1].events[0].startTime,0);await projects.flush();});
test('Negative latency compensation crosses a tempo change using seconds, while diagnostic beats stay untouched',()=>{const p=createProject({tempo:60,timeSignature:'4/4'});p.tempoMap=[{measure:2,bpm:120}];assert.ok(Math.abs(beatAfterSeconds(p,4.04,-.05)-3.97)<1e-8);const notes:any[]=[];const recorder=new Recorder(n=>notes.push(n));recorder.begin('soprano',60,0,-50,{start:0,end:12},beat=>beatAfterSeconds(p,beat,-.05));recorder.on('key',60,90,4.04,secondsBetween(p,0,4.04));recorder.off('key',4.4,secondsBetween(p,0,4.4));assert.ok(Math.abs(notes[0].originalStart-3.97)<1e-8);assert.ok(Math.abs(notes[0].originalStart+notes[0].originalDuration-4.3)<1e-8);assert.equal(notes[0].rawStartBeat,4.04);});
function fakeEngine(){return {now:10,status:'idle',beat:0,recordingOriginTime:10,options:null as any,onStop:()=>{},onRecordingStart:()=>{},onRecordLoop:(_b:number,_t:number)=>{},async init(){},position(){return this.beat;},async record(_from:number,count:number,options:any){this.options=options;this.beat=options.preRollStart;this.status=count?'countin':'preroll';},noteOn(){},noteOff(){},allNotesOff(){},start(){this.beat=this.options.start;this.status='recording';this.onRecordingStart();},stop(){this.onStop();this.status='idle';}};}
test('Latency shifts musical positions, preserves raw timestamps, and clips only at the recording gate',()=>{const notes:any[]=[];const recorder=new Recorder(n=>notes.push(n));recorder.begin('soprano',120,10,-42,{start:4,end:8});recorder.on('key',61,100,4.2,10.1);recorder.off('key',8.2,12.1);const n=notes[0];assert.ok(Math.abs(n.originalStart-4.116)<1e-8);assert.ok(Math.abs(n.originalStart+n.originalDuration-8)<1e-8);assert.equal(n.rawStartBeat,4.2);assert.ok(Math.abs(n.rawDurationBeats-4)<1e-8);assert.ok(Math.abs(n.startTime-.1)<1e-8);assert.ok(Math.abs(n.endTime-2.1)<1e-8);});
test('Punch pre-roll ignores early attacks and REPLACE preserves both outside passages and other voices',async()=>{const projects=new ProjectStore(),p=createProject({timeSignature:'4/4',tempo:120});p.settings.punchEnabled=true;p.settings.punchStart=8;p.settings.punchEnd=16;p.settings.preRoll=2;p.settings.recordMode='replace';p.tracks[0].events=[0,8,12,16].map(b=>makeNote('soprano',60,b,1,120));p.tracks[1].events=[makeNote('alto',53,8,2,120)];await projects.add(p);const engine=fakeEngine(),s=new RecordingSession(engine as any,projects);await s.record(2);assert.equal(engine.options.preRollStart,0);engine.beat=4;await s.noteOn('early',65);s.noteOff('early');engine.start();engine.beat=9;engine.now=10.5;await s.noteOn('new',67);engine.beat=10;engine.now=11;s.noteOff('new');engine.beat=16;engine.stop();const result=projects.getSnapshot().project!;assert.deepEqual(result.tracks[0].events.map(n=>noteStart(n)).sort((a,b)=>a-b),[0,9,16]);assert.equal(result.tracks[1].events.length,1);projects.undo();assert.deepEqual(projects.getSnapshot().project!.tracks[0].events,p.tracks[0].events);await projects.flush();});
test('Three loop passages remain separate, choose another take replaces the selected layer, and held notes are split at boundaries',async()=>{const projects=new ProjectStore(),p=createProject({tempo:120});p.settings.loopRecording=true;p.settings.loopStart=3;p.settings.loopEnd=6;p.settings.recordMode='overdub';p.tracks[0].events=[makeNote('soprano',60,3,.5,120)];await projects.add(p);const engine=fakeEngine(),s=new RecordingSession(engine as any,projects);await s.record(0);engine.start();for(let cycle=0;cycle<3;cycle++){engine.beat=3.5;engine.now=10+cycle*1.5;await s.noteOn('new',64+cycle);engine.beat=4.5;engine.now+=.5;s.noteOff('new');if(cycle<2){engine.beat=6;engine.onRecordLoop(6+cycle*3,11.5+cycle*1.5);}}engine.beat=5;engine.stop();const result=projects.getSnapshot().project!;assert.equal(result.takes.length,3);assert.deepEqual(result.takes.map(t=>t.events[0].midiPitch),[64,65,66]);assert.equal(result.tracks[0].events.length,2);projects.update(p=>chooseTake(p,p.takes[2].id));assert.deepEqual(projects.getSnapshot().project!.tracks[0].events.map(n=>n.midiPitch).sort(),[60,66]);assert.equal(projects.getSnapshot().project!.takes.filter(t=>t.selected).length,1);await projects.flush();});
