import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import { createProject,makeNote } from '../src/music/model.ts';
const taskLocation={hash:'',pathname:'/'};
Object.assign(globalThis,{location:taskLocation,history:{replaceState(_a:unknown,_b:unknown,path:string){taskLocation.hash=path.startsWith('#')?path:'';}}});
const {ProjectStore}=await import('../src/storage/store.ts');
test('J / K — add, edit, undo/redo, recording take and new repository session round trip',async()=>{const s=new ProjectStore();await s.init();const p=await s.create({title:'Storage QA',tonic:'Db',timeSignature:'6/8',tempo:72});s.update(p=>{p.tracks[0].events.push(makeNote('soprano',61,0,.5,72));});const noteId=s.getSnapshot().project!.tracks[0].events[0].id;s.update(p=>{const n=p.tracks[0].events[0];n.midiPitch=65;n.quantizedStart=1;n.quantizedDuration=1.5;});assert.equal(s.getSnapshot().project!.tracks[0].events[0].midiPitch,65);s.undo();assert.equal(s.getSnapshot().project!.tracks[0].events[0].midiPitch,61);s.redo();assert.equal(s.getSnapshot().project!.tracks[0].events[0].quantizedDuration,1.5);s.update(p=>{p.tracks[0].events=[];});s.undo();assert.equal(s.getSnapshot().project!.tracks[0].events[0].id,noteId);s.beginTake();s.update(p=>{p.tracks[1].events.push(makeNote('alto',53,0,1,72));},false);s.update(p=>{p.tracks[1].events.push(makeNote('alto',56,1,1,72));},false);s.endTake();s.undo();assert.equal(s.getSnapshot().project!.tracks[1].events.length,0);s.redo();assert.equal(s.getSnapshot().project!.tracks[1].events.length,2);await s.flush();const fresh=new ProjectStore();await fresh.init();await fresh.open(p.id);assert.deepEqual(fresh.getSnapshot().project,s.getSnapshot().project);assert.equal(fresh.getSnapshot().project!.tracks[1].events.length,2);await s.close();await s.duplicate(p.id);assert.ok(s.getSnapshot().projects.some(x=>x.title==='Storage QA — copie'));await s.rename(p.id,'Renamed QA');assert.ok(s.getSnapshot().projects.some(x=>x.title==='Renamed QA'));await s.remove(p.id);assert.equal(await s.repository.get(p.id),undefined);});
test('Preferences are durable in IndexedDB',async()=>{const s=new ProjectStore();await s.repository.setPreference('theme','light');const fresh=new ProjectStore();assert.equal(await fresh.repository.preference('theme'),'light');});
