import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createProject,createDemo,makeNote,id,noteStart,noteDuration,type Project,type Signature,type NavigationSymbol} from '../src/music/model.ts';
import {measureAt} from '../src/music/timeline.ts';
import {rhythmBoundaries,principalPulses} from '../src/solfa/rhythm.ts';
import {engraveProject,pageSVG,systemPage} from '../src/score/engraving.ts';
import {DEFAULT_SOLFA} from '../src/score/display.ts';
import {splitLyrics,assignSequential,linkSyllable} from '../src/lyrics/lyrics.ts';
import {shareLyrics,correctSharedSyllable,setLyricText,splitSharedLyrics,compatibleLyricAlignment,lyricPlacements} from '../src/lyrics/shared.ts';
import {addMusicLink,playbackNotes} from '../src/music/links.ts';
import {playbackMeasureOrder,playbackChunks,playbackSongBeat,playbackSeconds,playbackBeat} from '../src/music/repeats.ts';
import {navigationProblems} from '../src/music/navigation.ts';
import {checkScore} from '../src/score/checker.ts';
import {createScoreStyle,applyScoreStyle,automaticLayout} from '../src/score/styles.ts';
import {defaultHeader,defaultFooter,decoration} from '../src/score/decorations.ts';
import {validateProject} from '../src/storage/migrations.ts';
import {encodeProject,decodeProject} from '../src/storage/project-file.ts';
import {copyMeasures,pasteBlock,editMeasures,cleanLyrics} from '../src/music/editing.ts';
import {pdfBytes,scoreFonts} from '../src/score/export.ts';
function fixture(signature:Signature='4/4'):Project {const p=createProject({tonic:'Db',timeSignature:signature,title:'Chœur — l’espérance'});p.settings.measureCount=4;return p;}
function notes(p:Project,step:number,duration=step,total=measureAt(p,1).barBeats){for(const t of p.tracks)t.events=Array.from({length:Math.ceil(total/step)},(_,i)=>makeNote(t.id,61,i*step,duration,72));return p;}
function lyricFixture(){const p=notes(fixture(),1,1,16),line={id:id(),trackId:'soprano',text:'Ry mpa-nom-po tsa-ra',syllables:splitLyrics('Ry mpa-nom-po tsa-ra'),verse:1,kind:'verse' as const};p.lyrics.push(line);assignSequential(p,line.id);shareLyrics(p,line.id,p.tracks.map(t=>t.id));return p;}
function nav(p:Project,symbol:NavigationSymbol,measure:number,targetId?:string){const sign={id:id(),kind:'navigation' as const,symbol,measure,...(targetId?{targetId}:{}),text:symbol};p.indications.push(sign);return sign.id;}
for(const [signature,pulses] of [['4/4',4],['3/4',3],['2/4',2],['6/8',2],['9/8',3],['12/8',4]] as const)test('Traditional principal pulses and exact colon count in '+signature,()=>{const p=fixture(signature),boundaries=rhythmBoundaries(p,1);assert.equal(principalPulses(measureAt(p,1)).length,pulses);assert.equal(boundaries.filter(b=>b.kind==='pulse').length,pulses-1);const doc=engraveProject(p);assert.equal(doc.systems[0].ops.filter(op=>op.role==='rhythm'&&op.measure===1&&op.trackId==='soprano'&&op.kind==='text'&&op.text===':').length,pulses-1);});
test('Compound secondary pulses, custom 3+2 and a pickup retain quarter-note timing',()=>{const p=fixture('6/8');p.layout.compoundPulse=false;assert.equal(rhythmBoundaries(p,1).filter(r=>r.kind==='pulse').length,5);p.timeSignature='5/8';p.settings.beatGroups=[3,2];p.layout.compoundPulse=true;assert.deepEqual(principalPulses(measureAt({...p},1)),[0,1.5]);const pickup=fixture('4/4');pickup.settings.pickupBeats=1;assert.equal(measureAt(pickup,1).barBeats,1);assert.equal(rhythmBoundaries(pickup,1).filter(b=>b.kind==='pulse').length,0);});
test('Halves, quarters and thirds use distinct centered separators across SATB',()=>{for(const [step,kinds] of [[.5,['half']],[.25,['quarter','half','quarter']],[1/3,['third','third']]] as const){const p=notes(fixture(),step);const actual=rhythmBoundaries(p,1).filter(r=>r.beat<1).map(r=>r.kind);assert.deepEqual(actual,kinds);const doc=engraveProject(p),ops=doc.systems[0].ops.filter(op=>op.role==='rhythm'&&op.measure===1&&op.beat!<1);const soprano=ops.filter(op=>op.trackId==='soprano');assert.equal(soprano.length,kinds.length);for(const op of soprano){for(const track of p.tracks)assert.ok(ops.some(other=>other.trackId===track.id&&other.beat===op.beat&&Math.abs(other.x-op.x)<1e-5));if(step===1/3)assert.equal(op.kind,'curve');}}});
test('Mixed syncopation, holds, rests, sixteenths and triplets keep a shared temporal grid',()=>{const p=fixture();p.tracks[0].events=[makeNote('soprano',61,0,2,72)];p.tracks[1].events=[makeNote('alto',65,.25,.25,72),makeNote('alto',66,1/3,1/3,72),makeNote('alto',68,2.5,.25,72)];const doc=engraveProject(p,undefined,{...DEFAULT_SOLFA,rests:true}),bar=doc.systems[0].measures[0];assert.ok(bar.geometry.anchors.some(a=>Math.abs(a.beat-.25)<1e-4));assert.ok(doc.systems[0].ops.some(op=>op.kind==='text'&&op.text==='-'&&op.trackId==='soprano'));assert.ok(doc.systems[0].ops.some(op=>op.kind==='text'&&op.text==='0'&&op.trackId==='bass'));const before=structuredClone(p.tracks);engraveProject(p);assert.deepEqual(p.tracks,before);});
test('Octaves stay attached as one or two apostrophes/commas; they cannot become rhythm separators',()=>{const p=fixture();p.tracks[0].events=[61,73,85,49,37].map((pitch,i)=>makeNote('soprano',pitch,i*.5,.5,72));const doc=engraveProject(p),ops=doc.pages[0].ops.filter(op=>op.kind==='text'&&op.noteIds?.length);assert.deepEqual(ops.map(op=>op.kind==='text'?op.text:''),['d',"d'","d''",'d,','d,,']);const svg=pageSVG(doc.pages[0],undefined,true);assert.match(svg,/<tspan font-size="11.9" dy="-6.46">&apos;&apos;<\/tspan>/);assert.match(svg,/<tspan font-size="11.9" dy="3.06">,,<\/tspan>/);assert.equal((svg.match(/data-note-id=/g)??[]).length,5);});
test('Regular justification is proportional and equal for comparable bars; manual widths and breaks remain musical',()=>{const p=notes(fixture(),.5,.5,16),doc=engraveProject(p);const widths=doc.systems[0].measures.map(m=>m.width);assert.ok(widths.every(w=>Math.abs(w-widths[0])<1e-5));const g=doc.systems[0].measures[0].geometry;assert.ok(Math.abs(g.anchors[1].x/g.anchors[2].x-.5)<1e-5);p.layout.systemBreaks=[2];p.layout.pageBreaks=[2];p.layout.measureWidths={1:1.5};const changed=engraveProject(p);assert.equal(changed.systems[0].last,2);assert.equal(changed.systems[1].page,1);assert.ok(changed.systems[0].measures[0].width>changed.systems[0].measures[1].width);const tracks=structuredClone(p.tracks);p.layout=automaticLayout(p.layout);assert.equal(engraveProject(p).pages.length,1);assert.deepEqual(p.tracks,tracks);});
test('SATB labels appear only once by default, with first-per-page, always and never alternatives',()=>{const p=fixture();p.layout.measuresPerSystem=1;p.layout.pageBreaks=[2];let doc=engraveProject(p);assert.equal(doc.pages.flatMap(p=>p.ops).filter(op=>op.role==='voice').length,4);p.layout.voiceLabels='page';doc=engraveProject(p);assert.equal(doc.pages.flatMap(p=>p.ops).filter(op=>op.role==='voice').length,8);p.layout.voiceLabels='always';assert.equal(engraveProject(p).pages.flatMap(p=>p.ops).filter(op=>op.role==='voice').length,16);p.layout.voiceLabels='never';assert.equal(engraveProject(p).pages.flatMap(p=>p.ops).filter(op=>op.role==='voice').length,0);});
test('Common SATB lyrics print once; editing from Alto updates canonical text without losing note links',()=>{const p=lyricFixture();validateProject(p);assert.equal(lyricPlacements(p).length,1);const line=p.lyrics.find(l=>l.trackId==='alto')!,ids=p.lyrics.map(l=>l.syllables.map(s=>s.noteIds));correctSharedSyllable(p,line.id,1,'fan');assert.ok(p.lyrics.every(l=>l.syllables[1].text==='fan'&&l.text.includes('fan-')));assert.equal(p.sharedLyrics![0].syllables[1].text,'fan');assert.deepEqual(p.lyrics.map(l=>l.syllables.map(s=>s.noteIds)),ids);const doc=engraveProject(p);assert.equal(doc.pages.flatMap(p=>p.ops).filter(op=>op.kind==='text'&&op.role==='lyric'&&op.text==='fan-').length,1);validateProject(p);});
test('Different rhythms preserve links per voice and fall back to separate rows; text insertions retain existing melismas',()=>{const p=lyricFixture();p.tracks[1].events[0].editDuration=.5;assert.equal(compatibleLyricAlignment(p,p.lyrics),false);assert.equal(lyricPlacements(p).length,4);const line=p.lyrics[0];linkSyllable(p,line.id,2,p.tracks[0].events.slice(2,4).map(n=>n.id));const previous=line.syllables.map(s=>s.noteIds);setLyricText(p,line.id,'Ry vaovao mpa-nom-po tsa-ra');splitSharedLyrics(p,line.id);assert.deepEqual(line.syllables[0].noteIds,previous[0]);assert.deepEqual(line.syllables[2].noteIds,previous[1]);assert.deepEqual(line.syllables[3].noteIds,previous[2]);assert.equal(line.syllables[1].noteIds,undefined);validateProject(p);});
test('A shared SA group, refrains and verses coexist; deletion cleans links while duplication retains canonical texts',()=>{const p=lyricFixture();const common=p.sharedLyrics![0];shareLyrics(p,p.lyrics[0].id,['soprano','alto'],'SA');assert.deepEqual(common.trackIds,['soprano','alto']);p.lyrics.push({id:id(),trackId:'bass',kind:'refrain',verse:1,text:'A-me-na',syllables:splitLyrics('A-me-na')});assignSequential(p,p.lyrics.at(-1)!.id);const original=structuredClone(p),block=copyMeasures(p,1,1,'all');pasteBlock(p,block,2,'all');validateProject(p);assert.equal(p.sharedLyrics!.length,2);assert.ok(p.sharedLyrics![1].trackIds.includes('alto'));assert.deepEqual(p.lyrics.find(l=>l.id===original.lyrics[0].id)!.syllables.map(s=>s.text),original.lyrics[0].syllables.map(s=>s.text));editMeasures(p,'clear',1,1,'all');validateProject(p);assert.ok(p.lyrics[0].syllables[0].noteIds!.length===0);});
test('Duration, phrase and melisma links are distinct and ties suppress a second audio attack without altering recorded events',()=>{const p=notes(fixture(),1,1,4),raw=structuredClone(p.tracks);addMusicLink(p,'tie',p.tracks[0].events.slice(0,2).map(n=>n.id));addMusicLink(p,'phrase',p.tracks[1].events.slice(0,3).map(n=>n.id));addMusicLink(p,'melisma',p.tracks[2].events.slice(0,3).map(n=>n.id));assert.equal(playbackNotes(p,'soprano').length,3);assert.equal(noteDuration(playbackNotes(p,'soprano')[0]),2);assert.equal(playbackNotes(p,'alto').length,4);assert.deepEqual(p.tracks,raw);assert.equal(engraveProject(p).pages.flatMap(p=>p.ops).filter(op=>op.role==='link'&&op.kind==='curve').length,3);const other=fixture();other.tracks[0].events=[makeNote('soprano',61,0,1,72),makeNote('soprano',65,1,1,72)];assert.throws(()=>addMusicLink(other,'tie',other.tracks[0].events.map(n=>n.id)),/même hauteur/);});
test('D.C., D.C. al Fine, D.S. and D.S. al Coda resolve exact paths and playback clocks',()=>{let p=fixture();nav(p,'dc',4);assert.deepEqual(playbackMeasureOrder(p),[1,2,3,4,1,2,3,4]);p=fixture();nav(p,'fine',2);nav(p,'dc-fine',4);assert.deepEqual(playbackMeasureOrder(p),[1,2,3,4,1,2]);p=fixture();const segno=nav(p,'segno',2);nav(p,'ds',4,segno);assert.deepEqual(playbackMeasureOrder(p),[1,2,3,4,2,3,4]);p=fixture();p.settings.measureCount=6;const s=nav(p,'segno',2),c=nav(p,'coda',5);nav(p,'to-coda',3,c);nav(p,'ds-coda',4,s);assert.deepEqual(playbackMeasureOrder(p),[1,2,3,4,2,3,5,6]);const chunks=playbackChunks(p);assert.equal(playbackSongBeat(p,chunks[1].rawStart),4);const seconds=playbackSeconds(p,0,16);assert.ok(Math.abs(playbackBeat(p,0,seconds)-16)<1e-7);});
test('Navigation with repeats, standalone Fine and invalid destinations cannot create an endless loop',()=>{const p=fixture();p.repeats=[{id:id(),startMeasure:1,endMeasure:2,times:2}];nav(p,'fine',2);nav(p,'dc-fine',4);assert.deepEqual(playbackMeasureOrder(p),[1,2,1,2,3,4,1,2]);const bad=fixture();nav(bad,'ds-fine',4,'missing');assert.ok(navigationProblems(bad).length>=2);assert.throws(()=>playbackMeasureOrder(bad),/sans/);const coda=nav(bad,'coda',1);nav(bad,'to-coda',2,coda);assert.ok(navigationProblems(bad).some(i=>i.message.includes('suivre')));const fine=fixture();nav(fine,'fine',2);assert.deepEqual(playbackMeasureOrder(fine),[1,2]);});
test('Breaths are beat-positioned for one or all voices; Segno/Coda are vectors and uninterpreted expression is explicitly reported',()=>{const p=fixture();p.indications=[{id:id(),kind:'breath',text:'Respiration',measure:1,beat:1.5,trackIds:['soprano','alto']},{id:id(),kind:'fermata',text:'Point d’orgue',measure:1,beat:2},{id:id(),kind:'tempo',text:'rit.',measure:2}];nav(p,'segno',1);nav(p,'coda',3);const doc=engraveProject(p),breath=doc.pages[0].ops.filter(op=>op.objectId===p.indications[0].id);assert.equal(breath.length,2);assert.ok(breath.every(op=>op.kind==='curve'&&op.beat===1.5));assert.ok(doc.pages[0].ops.some(op=>op.kind==='circle'&&op.outline));assert.ok(checkScore(p,doc).some(i=>i.message.includes('sans interprétation audio : rit.')));});
for(const pages of [1,5,10])test('Page count '+pages+', centered title, numbered footer and stable SVG/PDF decorations',async()=>{const p=fixture();p.settings.measureCount=Math.max(4,pages);p.layout.measuresPerSystem=1;p.layout.pageBreaks=pages===1?[]:Array.from({length:pages-1},(_,i)=>i+1);p.layout.header=defaultHeader(p);p.layout.footer=defaultFooter(p);p.layout.headerOn='all';p.layout.header[0].font='serif';p.layout.header[0].italic=true;p.layout.footer.push({...decoration('custom','center',1,'© Chœur — {page}/{pages}',10),bold:true});const doc=engraveProject(p);assert.equal(doc.pages.length,pages);assert.equal(doc.pages.at(-1)!.ops.filter(op=>op.kind==='text'&&op.role==='footer').some(op=>op.kind==='text'&&op.text===`${pages} / ${pages}`),true);const fonts=await scoreFonts(doc,readFileSync('src/assets/ScoreFont.ttf').toString('base64')),svg=pageSVG(doc.pages[0],fonts);assert.ok(!svg.includes('src/url'));assert.ok(!svg.includes('file:'));assert.ok(svg.includes('Soratroserifbolditalic'));const bytes=await pdfBytes(doc,fonts,p);assert.equal(Buffer.from(bytes).subarray(0,5).toString(),'%PDF-');if(pages===5){mkdirSync('tmp/pdfs',{recursive:true});writeFileSync('tmp/pdfs/v04-decorations.pdf',Buffer.from(bytes));writeFileSync('tmp/pdfs/v04-decorations.svg',svg);}const crop=systemPage(doc.pages[0],doc.systems[0]);assert.ok(crop.ops.every(op=>op.role!=='header'&&op.role!=='footer'));});
test('Styles copy layout only, preview and cancellation are pure; old/new project export retains all fields',async()=>{const p=lyricFixture();p.layout.header=defaultHeader(p);p.layout.systemCounts={1:2};addMusicLink(p,'tie',p.tracks[0].events.slice(0,2).map(n=>n.id));nav(p,'fine',4);const style=createScoreStyle('Chorale',p.layout),other=createDemo(),before=structuredClone(other);applyScoreStyle(other,style);assert.deepEqual(other.tracks,before.tracks);assert.deepEqual(other.lyrics,before.lyrics);assert.equal(other.title,before.title);assert.notEqual(other.layout,style.layout);const restored=await decodeProject(await encodeProject(p));assert.deepEqual(restored,p);const corrupt=structuredClone(p);corrupt.layout.header![0].font='bad' as any;assert.throws(()=>validateProject(corrupt),/Décoration incompatible/);});
test('Verifier reports position, orphan lyrics, bad ties and collisions without automatic correction',()=>{const p=lyricFixture();nav(p,'ds',4,'missing');p.lyrics[0].syllables[0].noteIds=[];delete p.lyrics[0].syllables[0].noteId;p.indications.push({id:id(),kind:'breath',measure:1,text:'Respiration',beat:9});addMusicLink(p,'tie',p.tracks[0].events.slice(1,3).map(n=>n.id));p.tracks[0].events[2].midiPitch=65;const before=structuredClone(p),issues=checkScore(p);assert.ok(issues.some(i=>i.severity==='error'&&i.measure===4));assert.ok(issues.some(i=>i.message.includes('Syllabe sans note')));assert.ok(issues.some(i=>i.message.includes('après la fin')));assert.ok(issues.some(i=>i.message.includes('hauteurs différentes')));assert.deepEqual(p,before);p.tracks[0].events=[];cleanLyrics(p);assert.equal(p.links?.length,0);});
test('D.S. al Fine and D.C. al Coda respect their destinations and reject an unreachable To Coda',()=>{let p=fixture();nav(p,'segno',2);nav(p,'fine',3);nav(p,'ds-fine',4);assert.deepEqual(playbackMeasureOrder(p),[1,2,3,4,2,3]);p=fixture();p.settings.measureCount=6;const c=nav(p,'coda',5);nav(p,'to-coda',2,c);nav(p,'dc-coda',4);assert.deepEqual(playbackMeasureOrder(p),[1,2,3,4,1,2,5,6]);const bad=fixture();const segno=nav(bad,'segno',2),coda=nav(bad,'coda',4);nav(bad,'to-coda',1,coda);nav(bad,'ds-coda',3,segno);assert.ok(navigationProblems(bad).some(i=>i.message.includes('manquant')));});
test('Spanning hairpins use selected voices, continue over a system break and keep their full extent',()=>{const p=notes(fixture(),1,1,16);p.layout.systemBreaks=[1];p.indications=[{id:id(),kind:'crescendo',measure:1,beat:2,endBeat:6,text:'Crescendo',trackIds:['alto']}];const doc=engraveProject(p),ops=doc.systems.flatMap(s=>s.ops).filter(op=>op.objectId===p.indications[0].id);assert.equal(ops.length,4);assert.ok(ops.every(op=>op.kind==='line'&&op.trackId==='alto'));assert.equal(doc.systems[0].ops.filter(op=>op.objectId===p.indications[0].id).length,2);assert.equal(doc.systems[1].ops.filter(op=>op.objectId===p.indications[0].id).length,2);});
test('Removing a voice cleans its group membership, music links and scoped symbols while keeping remaining voices intact',()=>{const p=lyricFixture();p.indications=[{id:id(),kind:'breath',text:'Respiration',measure:1,trackIds:['soprano','alto']},{id:id(),kind:'dynamic',text:'mf',measure:1,trackIds:['alto']}];addMusicLink(p,'tie',p.tracks[1].events.slice(0,2).map(n=>n.id));const remaining=structuredClone(p.tracks.filter(t=>t.id!=='alto'));p.tracks=remaining;p.lyrics=p.lyrics.filter(l=>l.trackId!=='alto');cleanLyrics(p);validateProject(p);assert.deepEqual(p.sharedLyrics![0].trackIds,['soprano','tenor','bass']);assert.equal(p.links!.length,0);assert.equal(p.indications.length,1);assert.deepEqual(p.indications[0].trackIds,['soprano']);assert.deepEqual(p.tracks,remaining);});
