import test from 'node:test';import assert from 'node:assert/strict';import { JSDOM } from 'jsdom';import 'fake-indexeddb/auto';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://example.test/soratro/',pretendToBeVisual:true});
Object.assign(globalThis,{FormData:dom.window.FormData,window:dom.window,document:dom.window.document,location:dom.window.location,history:dom.window.history,HTMLElement:dom.window.HTMLElement,HTMLDialogElement:dom.window.HTMLDialogElement,Element:dom.window.Element,Node:dom.window.Node,MutationObserver:dom.window.MutationObserver,requestAnimationFrame:dom.window.requestAnimationFrame.bind(dom.window),cancelAnimationFrame:dom.window.cancelAnimationFrame.bind(dom.window),IS_REACT_ACT_ENVIRONMENT:true});
Object.defineProperty(globalThis,'navigator',{configurable:true,value:dom.window.navigator});
Object.defineProperty(dom.window.HTMLDialogElement.prototype,'showModal',{value:function(){this.setAttribute('open','');}});Object.defineProperty(dom.window.HTMLDialogElement.prototype,'close',{value:function(){this.removeAttribute('open');}});Object.defineProperty(dom.window.HTMLElement.prototype,'setPointerCapture',{value(){}});Object.defineProperty(dom.window.HTMLElement.prototype,'releasePointerCapture',{value(){}});Object.defineProperty(dom.window.HTMLElement.prototype,'scrollTo',{value:function(options:any){this.scrollTop=options.top??this.scrollTop;this.scrollLeft=options.left??this.scrollLeft;}});Object.defineProperty(dom.window.HTMLElement.prototype,'scrollIntoView',{value(){}});
Object.defineProperty(dom.window.HTMLElement.prototype,'clientHeight',{get(){return this.classList.contains('piano-white')?135:30;}});
Object.defineProperty(dom.window.HTMLElement.prototype,'getBoundingClientRect',{value(){return {x:0,y:0,left:0,top:0,right:40,bottom:135,width:40,height:135,toJSON(){return {};}};}});
class AudioParamMock {value=0;setTargetAtTime(value:number){this.value=value;}setValueAtTime(value:number){this.value=value;}linearRampToValueAtTime(value:number){this.value=value;}exponentialRampToValueAtTime(value:number){this.value=value;}cancelAndHoldAtTime(){} }
class AudioNodeMock {gain=new AudioParamMock();pan=new AudioParamMock();frequency=new AudioParamMock();threshold=new AudioParamMock();knee=new AudioParamMock();ratio=new AudioParamMock();onended:((event:unknown)=>void)|null=null;type='sine';connect(node:AudioNodeMock){return node;}disconnect(){}start(){}stop(){} }
class AudioContextMock {state='running';started=performance.now();destination=new AudioNodeMock();baseLatency=.01;outputLatency=.01;get currentTime(){return (performance.now()-this.started)/1000;}createGain(){return new AudioNodeMock();}createStereoPanner(){return new AudioNodeMock();}createDynamicsCompressor(){return new AudioNodeMock();}createOscillator(){return new AudioNodeMock();}async resume(){this.state='running';}async close(){this.state='closed';}}
Object.assign(globalThis,{AudioContext:AudioContextMock});
const React=await import('react'),{render,screen,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');const {App}=await import('../src/ui/App');const {store}=await import('../src/storage/store');const {audio}=await import('../src/audio/engine');const {encodeProject}=await import('../src/storage/project-file');
async function ready(){render(<App/>);await waitFor(()=>assert.ok(screen.getByText('Mes partitions',{exact:false})));}
async function close(){await act(async()=>{audio.stop();await store.close();});cleanup();}
test('UI: new Solo score stores dotted-quarter BPM, flexible voices, lyrics links, layout and durable save',async()=>{
 await ready();fireEvent.click(screen.getByRole('button',{name:'Nouvelle partition'}));fireEvent.change(screen.getByLabelText('Titre'),{target:{value:'UI QA Solo'}});fireEvent.change(screen.getByLabelText('Formation'),{target:{value:'Solo'}});fireEvent.click(screen.getByRole('button',{name:'Créer la partition'}));await waitFor(()=>assert.equal(store.getSnapshot().project?.title,'UI QA Solo'));await act(async()=>{await store.flush();});assert.equal(store.getSnapshot().project!.tracks.length,1);assert.equal(store.getSnapshot().project!.tempo,108);assert.equal(store.getSnapshot().project!.settings.tempoUnit,'dotted-quarter');assert.equal((screen.getByLabelText('Tempo BPM') as HTMLInputElement).value,'72');assert.ok(screen.getByText('Solo',{exact:true}));
 fireEvent.click(document.querySelector('.project-title')!);fireEvent.change(document.querySelector('dialog select[name=tempoUnit]')!,{target:{value:'quarter'}});assert.equal((document.querySelector('dialog input[name=tempo]') as HTMLInputElement).value,'108');fireEvent.click(document.querySelector('dialog .primary-button')!);assert.equal(store.getSnapshot().project!.tempo,108);assert.equal(store.getSnapshot().project!.settings.tempoUnit,'quarter');
 fireEvent.click(screen.getByRole('button',{name:'Paroles'}));fireEvent.click(screen.getByRole('button',{name:'+ Couplet'}));fireEvent.change(screen.getByLabelText('Texte des paroles'),{target:{value:'Ry mpa-nom-po tsa-ra'}});fireEvent.click(screen.getByRole('button',{name:'Découper'}));assert.equal(store.getSnapshot().project!.lyrics[0].syllables.length,6);
 fireEvent.click(screen.getByRole('button',{name:'PDF / Export'}));assert.ok(screen.getByRole('heading',{name:'Exporter la partition'}));assert.ok(document.querySelector('.engraved-content svg'));fireEvent.change(screen.getByLabelText('Papier'),{target:{value:'A5'}});assert.equal(store.getSnapshot().project!.layout.paper,'A5');fireEvent.click(screen.getByRole('button',{name:'Fermer',exact:true}));await act(async()=>{await store.saveNow();});assert.equal((await store.repository.get(store.getSnapshot().project!.id))!.layout.paper,'A5');await close();
});
test('UI: existing study opens, virtual piano releases, multi-note clipboard shortcuts work, history previews and restore',async()=>{
 await ready();fireEvent.click(screen.getByRole('button',{name:'Ouvrir l’étude SATB en 6/8'}));await waitFor(()=>assert.equal(store.getSnapshot().project?.title,'Étude SATB'));assert.equal(store.getSnapshot().project!.tracks[0].events.length,24);
 const piano=screen.getByRole('button',{name:'Jouer C4',exact:true});fireEvent.pointerDown(piano,{pointerId:1,clientY:50});await act(async()=>{await new Promise(resolve=>setTimeout(resolve,30));});fireEvent.pointerUp(piano,{pointerId:1});assert.equal((audio as any).live.size,0);
 const roll=document.querySelector('.roll-panel')!;fireEvent.keyDown(roll,{code:'KeyA',ctrlKey:true});fireEvent.keyDown(roll,{code:'KeyD',ctrlKey:true});assert.equal(store.getSnapshot().project!.tracks[0].events.length,48);fireEvent.keyDown(roll,{code:'Delete'});assert.equal(store.getSnapshot().project!.tracks[0].events.length,24);await act(async()=>{await store.flush();});
 fireEvent.click(screen.getByRole('button',{name:'Historique'}));await waitFor(()=>assert.ok(screen.getByRole('heading',{name:'Historique du projet'})),{timeout:5000});assert.ok(document.querySelector('.version-history .engraved-content svg'));fireEvent.click(document.querySelectorAll('.version-history aside button')[1]);fireEvent.click(screen.getByRole('button',{name:'Restaurer cette version'}));await waitFor(()=>assert.equal(document.querySelectorAll('.version-history').length,0));assert.ok(store.getSnapshot().projects.some(p=>p.title==='Étude SATB — copie'));await close();
});
test('UI: .soratro import validates before writing and never overwrites an existing composition',async()=>{
 await ready();const source=store.getSnapshot().projects.find(p=>p.title==='UI QA Solo')!;const input=document.querySelector('input[type=file]')!;const content=await encodeProject(source);const file={name:'score.soratro',size:content.length,text:async()=>content};const imported=new Promise<void>(resolve=>{const off=store.subscribe(()=>{if(store.getSnapshot().project?.title==='UI QA Solo — import'){off();resolve();}});});await act(async()=>{fireEvent.change(input,{target:{files:[file]}});await imported;await store.flush();});assert.notEqual(store.getSnapshot().project!.id,source.id);assert.deepEqual(store.getSnapshot().project!.tracks,source.tracks);await close();
});
test('UI: selected notes retain their intervals at timeline boundaries and rehearsal starts at the chosen measure',async()=>{
 await ready();fireEvent.click(screen.getByRole('button',{name:'Ouvrir l’étude SATB en 6/8'}));await waitFor(()=>assert.equal(store.getSnapshot().project?.title,'Étude SATB'));
 const before=structuredClone(store.getSnapshot().project!.tracks[0].events),roll=document.querySelector('.roll-panel')!;fireEvent.keyDown(roll,{code:'KeyA',ctrlKey:true});fireEvent.keyDown(roll,{code:'ArrowLeft'});assert.deepEqual(store.getSnapshot().project!.tracks[0].events.map(n=>n.quantizedStart??n.editStart??n.originalStart),before.map(n=>n.originalStart));fireEvent.keyDown(roll,{code:'ArrowUp',shiftKey:true});assert.deepEqual(store.getSnapshot().project!.tracks[0].events.map(n=>n.midiPitch),before.map(n=>n.midiPitch+12));
 fireEvent.click(screen.getByRole('button',{name:'Répétition',exact:true}));fireEvent.change(screen.getByLabelText('De la mesure'),{target:{value:'3'}});fireEvent.click(screen.getByRole('button',{name:'Répéter la zone'}));assert.equal(audio.position(),6);assert.ok(screen.getByText('Boucle activée'));await close();
});
test.afterEach(async()=>{await close();});
test.after(async()=>{audio.dispose();await store.repository.close();dom.window.close();});
