import test from 'node:test';import assert from 'node:assert/strict';import 'fake-indexeddb/auto';
import {LocalPitchDetector} from '../src/vocal/pitch.ts';
import {VocalSegmenter} from '../src/vocal/segmenter.ts';
import {vocalSettings,validateVocal,type PitchFrame,type VocalSegment} from '../src/vocal/types.ts';
import {createProject,makeNote,noteStart,noteDuration} from '../src/music/model.ts';
import {AudioRepository} from '../src/storage/audio-repository.ts';
import {encodeAudioBundle,decodeAudioBundle} from '../src/storage/audio-bundle.ts';
import {RecordingSession} from '../src/recording/session.ts';import {AudioEngine} from '../src/audio/engine.ts';import {ProjectStore} from '../src/storage/store.ts';
import {chooseTake,restoreBeforeTake} from '../src/recording/takes.ts';import {validateProject} from '../src/storage/migrations.ts';
Object.assign(globalThis,{location:{hash:'',pathname:'/'},history:{replaceState(){}}});
const frame=(time:number,midi:number|null,rms=.15,confidence=.99):PitchFrame=>({time,midi,hz:midi===null?null:440*2**((midi-69)/12),voiced:midi!==null,rms,confidence,wave:[]});
function feed(s:VocalSegmenter,from:number,to:number,midi:number|null,rms=.15,vibrato=0){for(let t=from;t<to-1e-8;t+=.01)s.push(frame(t,midi===null?null:midi+vibrato*Math.sin(t*2*Math.PI*5),rms));}
test('McLeod detector identifies synthetic low/middle/high monophonic harmonics, rejects noise/silence and preserves chromatic pitch',()=>{const detector=new LocalPitchDetector();let seed=2467;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296*2-1;};for(const midi of [36,48,61,69,84,96]){const hz=440*2**((midi-69)/12),samples=Float32Array.from({length:2048},(_,i)=>.18*Math.sin(i*2*Math.PI*hz/24000)+.08*Math.sin(i*4*Math.PI*hz/24000)+.02*rnd());const result=detector.analyze(samples,24000,3,vocalSettings());assert.equal(result.voiced,true,'MIDI '+midi);assert.ok(Math.abs(result.midi!-midi)*100<12,'pitch error '+midi+' '+result.midi);assert.equal(result.time,3);}assert.equal(detector.analyze(new Float32Array(2048),24000,0).voiced,false);assert.equal(detector.analyze(Float32Array.from({length:2048},rnd),24000,0).voiced,false);});
test('Segmentation retains one long vibrato note, repeated same pitch after silence and chromatic notes',()=>{const out:VocalSegment[]=[];const s=new VocalSegmenter(n=>out.push(n));feed(s,0,1.1,61,.15,.18);feed(s,1.1,1.25,null);feed(s,1.25,1.8,61);feed(s,1.8,2.1,64);s.flush(2.1);assert.deepEqual(out.map(n=>n.pitch),[61,61,64]);assert.ok(Math.abs(out[0].startTime)<.02);assert.ok(Math.abs(out[0].endTime-1.1)<.02);assert.equal(out[0].uncertain,false);});
test('Glissandi avoid note floods and a voiced amplitude valley identifies a new same-pitch attack',()=>{const out:VocalSegment[]=[];const s=new VocalSegmenter(n=>out.push(n));feed(s,0,.5,60);for(let t=.5;t<1.5;t+=.01)s.push(frame(t,60+(t-.5)*7));feed(s,1.5,2,67);s.flush(2);assert.ok(out.length<=3);assert.equal(out.at(-1)!.pitch,67);const repeated:VocalSegment[]=[];const r=new VocalSegmenter(n=>repeated.push(n));feed(r,0,.5,65);feed(r,.5,.56,65,.03);feed(r,.56,1,65);r.flush(1);assert.deepEqual(repeated.map(n=>n.pitch),[65,65]);});
test('Minimum note duration discards clicks; uncertain pitches stay available for manual review',()=>{const out:VocalSegment[]=[];const s=new VocalSegmenter(n=>out.push(n),vocalSettings({minimumMs:150,pitchMode:'musical'}),'C');feed(s,0,.1,64);feed(s,.1,.3,null);for(let t=.3;t<.9;t+=.01)s.push(frame(t,61,.15,.85));s.flush(.9);assert.equal(out.length,1);assert.equal(out[0].pitch,61);assert.equal(out[0].uncertain,true);assert.equal(out[0].suggestedPitch,undefined);const ambiguous:VocalSegment[]=[];const assist=new VocalSegmenter(n=>ambiguous.push(n),vocalSettings({pitchMode:'musical'}),'C');feed(assist,0,.5,61.45);assist.flush(.5);assert.equal(ambiguous[0].pitch,61);assert.equal(ambiguous[0].suggestedPitch,62);assert.equal(ambiguous[0].uncertain,true);assert.throws(()=>validateVocal(vocalSettings({maxMidi:20})));});
function controlled(p:ReturnType<typeof createProject>,projects:ProjectStore){const engine=new AudioEngine(),inside=engine as any;inside.context={currentTime:10};inside.project=p;engine.init=async()=>engine.context!;engine.allNotesOff=()=>{};engine.noteOn=()=>{};engine.noteOff=()=>{};engine.record=async(from,_count,options)=>{inside.recordOptions=options;inside.originTime=10;inside.originBeat=from;inside.startBeat=from;inside.playbackStart=from;inside.mode='recording';inside.recordCycle=0;engine.onRecordingStart();};const session=new RecordingSession(engine,projects);return {engine,inside,session};}
const segment=(pitch:number,startTime:number,endTime:number):VocalSegment=>({pitch,startTime,endTime,confidence:.98,meanMidi:pitch+.03,spread:.12,uncertain:false});
test('Delayed vocal notes split at their audio timestamps across loop cycles using the same Recorder and quantizer',async()=>{const projects=new ProjectStore(),p=createProject({tempo:120,timeSignature:'4/4'});p.settings.inputSource='vocal';p.settings.loopRecording=true;p.settings.loopStart=4;p.settings.loopEnd=8;p.settings.quantization='none';p.tracks[1].events=[makeNote('alto',55,4,4,120)];await projects.add(p);const {engine,inside,session}=controlled(p,projects);await session.record(0);inside.context.currentTime=12.5;engine.synchronizeInput();const preview=session.provisional({pitch:61,startTime:11.75,lastTime:12.4,confidence:.99});assert.equal(preview!.originalStart,4);assert.ok(preview!.originalDuration>0&&preview!.originalDuration<1);session.captureVocal(segment(61,11.75,12.25));const takes=projects.getSnapshot().project!.takes;assert.equal(takes.length,2);assert.equal(takes[0].events[0].originalStart,7.5);assert.equal(takes[0].events[0].originalDuration,.5);assert.equal(takes[1].events[0].originalStart,4);assert.equal(takes[1].events[0].originalDuration,.5);assert.equal(takes[1].events[0].startTime,0);assert.equal(takes[1].events[0].vocal!.audioStartTime,12);engine.onStop();const saved=projects.getSnapshot().project!;assert.equal(saved.tracks[1].events[0].midiPitch,55);assert.equal(saved.takes[0].selected,true);validateProject(saved);projects.undo();assert.deepEqual(projects.getSnapshot().project!.tracks,p.tracks);await projects.flush();});
test('Vocal Punch clips the gate, retains raw/corrected/quantized data and Restore recovers previous music',async()=>{const projects=new ProjectStore(),p=createProject({tempo:120,timeSignature:'4/4'});p.settings.inputSource='vocal';p.settings.punchEnabled=true;p.settings.punchStart=4;p.settings.punchEnd=8;p.settings.recordMode='replace';p.settings.quantization='1/8';p.settings.latencyCompensationMs=-50;p.tracks[0].events=[makeNote('soprano',60,3,6,120),makeNote('soprano',64,10,1,120)];p.lyrics=[{id:'verse',trackId:'soprano',text:'Ry',syllables:[{id:'syl',text:'Ry',noteId:p.tracks[0].events[0].id,noteIds:[p.tracks[0].events[0].id]}]}];p.links=[{id:'phrase',kind:'phrase',trackId:'soprano',noteIds:p.tracks[0].events.map(n=>n.id)}];await projects.add(p);const {engine,inside,session}=controlled(p,projects);await session.record(0);inside.context.currentTime=12;session.captureVocal(segment(63,9.8,12.2));engine.onStop();let result=projects.getSnapshot().project!;assert.equal(result.takes.length,1);const n=result.takes[0].events[0];assert.equal(n.midiPitch,63);assert.equal(n.compensationMs,-50);assert.equal(n.rawStartBeat,4);assert.ok(n.originalStart>=4&&n.originalStart+n.originalDuration<=8);assert.ok(noteStart(n)>=4&&noteStart(n)+noteDuration(n)<=8);assert.equal(n.vocal!.confidence,.98);projects.update(p=>restoreBeforeTake(p,result.takes[0].id));result=projects.getSnapshot().project!;assert.deepEqual(result.tracks[0].events.sort((a,b)=>noteStart(a)-noteStart(b)),p.tracks[0].events);assert.equal(result.lyrics[0].syllables[0].noteId,p.tracks[0].events[0].id);assert.deepEqual(result.links,p.links);projects.update(p=>chooseTake(p,result.takes[0].id));assert.ok(projects.getSnapshot().project!.tracks[0].events.some(n=>n.midiPitch===63));await projects.flush();});
test('Local audio survives repository reopen; portable bundles validate audio hashes and preserve score compatibility',async()=>{const repo=new AudioRepository(),p=createProject(),row=await repo.put(p.id,new Blob(['test audio original'],{type:'audio/webm'}),1);p.takes=[{id:'take',name:'Vocal',trackId:'soprano',startBeat:0,endBeat:2,selected:false,events:[],createdAt:p.createdAt,audio:{id:row.id,mime:row.mime,bytes:row.bytes,duration:1,offset:0,length:1,capturedAt:row.createdAt}}];await repo.close();const restored=await repo.get(row.id);assert.equal(await restored!.blob.text(),'test audio original');const bundle=await encodeAudioBundle(p,[row]);const imported=await decodeAudioBundle(bundle);assert.deepEqual(imported.project,p);assert.equal(await imported.audios[0].blob.text(),'test audio original');const corrupted=bundle.slice();const text=new TextEncoder().encode('test audio original');let at=-1;for(let i=0;i<corrupted.length-text.length;i++)if(text.every((b,j)=>corrupted[i+j]===b)){at=i;break;}assert.ok(at>=0);corrupted[at]^=1;await assert.rejects(()=>decodeAudioBundle(corrupted),/checksum|invalid|CRC/i);await repo.delete(row.id);assert.equal(await repo.get(row.id),undefined);await repo.close();});
