import { useEffect,useRef,useState } from 'react';
import { audio } from '../audio/engine';
import { clickVoice } from '../audio/synth';
import { estimateLatency,type CalibrationResult } from '../recording/calibration';
import type { Project } from '../music/model';
export function Calibration({project,update,notice}:{project:Project;update:(fn:(p:Project)=>void)=>void;notice:(s:string)=>void}){
  const [running,setRunning]=useState(false),[count,setCount]=useState(0),[result,setResult]=useState<CalibrationResult|null>(null);const clicks=useRef<number[]>([]),samples=useRef<number[]>([]),used=useRef(new Set<number>()),timer=useRef<ReturnType<typeof setTimeout>|null>(null),voices=useRef<OscillatorNode[]>([]);
  function cleanup(){if(timer.current)clearTimeout(timer.current);voices.current.forEach(v=>{try{v.stop();}catch{}});voices.current=[];}
  useEffect(()=>()=>cleanup(),[]);
  function tap(){if(!running||!audio.context)return;const now=audio.now;let index=-1,distance=Infinity;clicks.current.forEach((time,i)=>{if(Math.abs(now-time)<distance){distance=Math.abs(now-time);index=i;}});if(index<0||distance>.4||used.current.has(index))return;used.current.add(index);samples.current.push((now-clicks.current[index])*1000);setCount(samples.current.length);}
  useEffect(()=>{if(!running)return;const key=(e:KeyboardEvent)=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();tap();}};window.addEventListener('keydown',key,true);return ()=>window.removeEventListener('keydown',key,true);},[running]);
  async function start(){try{audio.stop();await audio.init();cleanup();samples.current=[];used.current.clear();setCount(0);setResult(null);setRunning(true);const context=audio.context!;clicks.current=Array.from({length:12},(_,i)=>context.currentTime+.8+i*.6);voices.current=clicks.current.map((time,i)=>clickVoice(context,context.destination,time,i%4===0?2:0,.7));timer.current=setTimeout(()=>{setRunning(false);setResult(estimateLatency(samples.current));},8400);}catch(e){notice(e instanceof Error?e.message:'Calibration audio indisponible.');}}
  return <section className="calibration"><h3>Calibration de l’enregistrement</h3><p>Écoutez douze clics, puis frappez Espace ou le bouton en rythme. Les deux premières frappes servent d’échauffement. L’estimation inclut le matériel, le navigateur et votre réaction.</p><div className="calibration-actions"><button className="secondary-button" disabled={running} onClick={()=>void start()}>Lancer les clics</button><button className="primary-button" disabled={!running} onPointerDown={e=>{e.preventDefault();tap();}}>Frapper · {count} / 12</button></div>{result&&<><p>Décalage : <strong>{result.offsetMs>0?'+':''}{result.offsetMs} ms</strong> · dispersion {result.spreadMs} ms · {result.accepted} frappes retenues</p><p>{result.reason}</p><button disabled={!result.valid} onClick={()=>update(p=>{p.settings.latencyCompensationMs=result.compensationMs;})}>Appliquer {result.compensationMs} ms</button></>}<label>Compensation manuelle (ms)<input type="number" min={-250} max={250} value={project.settings.latencyCompensationMs} onChange={e=>{const val=+e.target.value;if(Number.isFinite(val)&&Math.abs(val)<=250)update(p=>{p.settings.latencyCompensationMs=val;});}}/></label><button onClick={()=>update(p=>{p.settings.latencyCompensationMs=0;})}>Réinitialiser</button><small>Une compensation négative avance la musique enregistrée. Les timestamps bruts restent conservés.</small></section>;
}
