import { useRef } from 'react';
import { ChevronLeft, ChevronRight, Keyboard } from 'lucide-react';
import { noteName } from '../music/model';
export const PC_KEYS:Record<string,number>={KeyA:0,KeyW:1,KeyS:2,KeyE:3,KeyD:4,KeyF:5,KeyT:6,KeyG:7,KeyY:8,KeyH:9,KeyU:10,KeyJ:11,KeyK:12,KeyO:13,KeyL:14,KeyP:15,Semicolon:16};
const LABELS:Record<number,string>={0:'A',1:'W',2:'S',3:'E',4:'D',5:'F',6:'T',7:'G',8:'Y',9:'H',10:'U',11:'J',12:'K',13:'O',14:'L',15:'P',16:';'};
interface Props {octave:number;setOctave:(n:number)=>void;active:number[];on:(key:string,pitch:number,velocity?:number)=>void;off:(key:string)=>void;color:string}
export function Piano({octave,setOctave,active,on,off,color}:Props){
  const pointers=useRef(new Map<number,number>());const base=(octave+1)*12;const notes=Array.from({length:25},(_,i)=>base+i);const white=notes.filter(n=>![1,3,6,8,10].includes(n%12));
  function press(e:React.PointerEvent<HTMLButtonElement>,pitch:number){e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,pitch);on('pointer:'+e.pointerId,pitch,Math.round(70+Math.min(1,Math.max(0,(e.clientY-e.currentTarget.getBoundingClientRect().top)/e.currentTarget.clientHeight))*40));}
  function release(e:React.PointerEvent<HTMLButtonElement>){if(pointers.current.has(e.pointerId)){off('pointer:'+e.pointerId);pointers.current.delete(e.pointerId);}}
  return <section className="piano-panel" aria-label="Clavier piano"><div className="piano-top"><span><Keyboard size={15}/> CLAVIER</span><div className="octave-control"><button aria-label="Octave inférieure" onClick={()=>setOctave(Math.max(1,octave-1))}><ChevronLeft size={16}/></button><span>C{octave} — C{octave+2}</span><button aria-label="Octave supérieure" onClick={()=>setOctave(Math.min(6,octave+1))}><ChevronRight size={16}/></button></div><span className="keyboard-hint">A W S E D… · Z / X : octave</span></div><div className="piano-scroll"><div className="piano-keybed" style={{'--key-color':color} as React.CSSProperties}>{white.map(pitch=><button key={pitch} aria-label={'Jouer '+noteName(pitch)} className={'piano-white '+(active.includes(pitch)?'pressed':'')} onPointerDown={e=>press(e,pitch)} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release}><span className="key-pc">{LABELS[pitch-base]||''}</span><span className="key-note">{noteName(pitch)}</span></button>)}{notes.filter(n=>[1,3,6,8,10].includes(n%12)).map(pitch=>{const prior=white.filter(n=>n<pitch).length;return <button key={pitch} aria-label={'Jouer '+noteName(pitch)} className={'piano-black '+(active.includes(pitch)?'pressed':'')} style={{left:`${(prior/white.length)*100}%`}} onPointerDown={e=>press(e,pitch)} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release}><span className="key-pc">{LABELS[pitch-base]||''}</span><span className="key-note">{noteName(pitch)}</span></button>;})}</div></div></section>;
}
