import { useEffect, useRef, useState } from 'react';
import { Minus, Plus, Pencil } from 'lucide-react';
import { makeNote, noteDuration, noteName, noteStart, projectEnd, signatureInfo, type NoteEvent, type Project, type TrackId } from '../music/model';
import { midiToSolfa } from '../solfa/converter';
import { gridStep } from '../quantization/quantizer';
export interface NoteSelection {trackId:TrackId;id:string}
interface Props {project:Project;trackId:TrackId;beat:number;running:boolean;loop:boolean;selected:NoteSelection|null;select:(s:NoteSelection|null)=>void;update:(fn:(p:Project)=>void)=>void;seek:(beat:number)=>void;locked:boolean}
const MIN=21,MAX=108,GUTTER=48,RULER=30;
export function PianoRoll({project,trackId,beat,running,loop,selected,select,update,seek,locked}:Props){
  const [zoom,setZoom]=useState(64),[height,setHeight]=useState(20),[draw,setDraw]=useState(false);const [drag,setDrag]=useState<{track:TrackId;id:string;start:number;duration:number;pitch:number;kind:'move'|'resize';x:number;y:number;current:NoteEvent}|null>(null);
  const scroll=useRef<HTMLDivElement>(null);const svg=useRef<SVGSVGElement>(null);const info=signatureInfo(project.timeSignature);const bars=Math.max(8,Math.ceil((Math.max(projectEnd(project),beat+info.barBeats*2))/info.barBeats));const beats=bars*info.barBeats;const width=GUTTER+beats*zoom+40,totalHeight=RULER+(MAX-MIN+1)*height;const currentTrack=project.tracks.find(t=>t.id===trackId)!;const step=gridStep(project.settings.quantization,currentTrack.events)||.125;
  useEffect(()=>{if(scroll.current)scroll.current.scrollTop=(MAX-(trackId==='bass'?55:trackId==='tenor'?60:67))*height-70;},[trackId,height]);
  useEffect(()=>{if(running&&scroll.current){const x=GUTTER+beat*zoom;const el=scroll.current;if(x>el.scrollLeft+el.clientWidth-80||x<el.scrollLeft+GUTTER)el.scrollLeft=Math.max(0,x-GUTTER-80);}},[beat,running,zoom]);
  function add(e:React.MouseEvent<SVGSVGElement>){if(locked)return;const r=svg.current!.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(x<GUTTER||y<RULER)return;const pitch=MAX-Math.floor((y-RULER)/height),start=Math.max(0,Math.round(((x-GUTTER)/zoom)/step)*step);update(p=>p.tracks.find(t=>t.id===trackId)!.events.push(makeNote(trackId,Math.max(MIN,Math.min(MAX,pitch)),start,step,p.tempo)));}
  function startDrag(e:React.PointerEvent<SVGGElement>,track:TrackId,n:NoteEvent){e.stopPropagation();if(locked)return;select({trackId:track,id:n.id});const resize=(e.target as Element).getAttribute('data-resize')==='true';e.currentTarget.setPointerCapture(e.pointerId);setDrag({track,id:n.id,start:noteStart(n),duration:noteDuration(n),pitch:n.midiPitch,kind:resize?'resize':'move',x:e.clientX,y:e.clientY,current:n});}
  function move(e:React.PointerEvent<SVGSVGElement>){if(!drag)return;const dx=(e.clientX-drag.x)/zoom;const snap=(n:number)=>Math.round(n/step)*step;const current={...drag.current};if(drag.kind==='resize')current.quantizedDuration=Math.max(step,snap(drag.duration+dx));else{current.quantizedStart=Math.max(0,snap(drag.start+dx));current.midiPitch=Math.max(MIN,Math.min(MAX,drag.pitch-Math.round((e.clientY-drag.y)/height)));}setDrag({...drag,current});}
  function end(){if(!drag)return;const {current,track,id}=drag;const changed=noteStart(current)!==drag.start||noteDuration(current)!==drag.duration||current.midiPitch!==drag.pitch;if(changed)update(p=>{const t=p.tracks.find(t=>t.id===track)!;t.events=t.events.map(n=>n.id===id?current:n);});setDrag(null);}
  return <section className="roll-panel"><div className="panel-bar"><div><span className="panel-eyebrow">PIANO ROLL</span><span className="track-caption" style={{color:currentTrack.color}}>{currentTrack.name}</span></div><div className="roll-tools"><button title="Dessiner des notes" aria-label="Dessiner des notes" aria-pressed={draw} className={draw?'active':''} onClick={()=>setDraw(!draw)} disabled={locked}><Pencil size={15}/></button><span className="tool-divider"/><button aria-label="Réduire le zoom horizontal" onClick={()=>setZoom(Math.max(24,zoom-16))}><Minus size={14}/></button><span>{Math.round(zoom/64*100)} %</span><button aria-label="Augmenter le zoom horizontal" onClick={()=>setZoom(Math.min(192,zoom+16))}><Plus size={14}/></button><select aria-label="Zoom vertical" value={height} onChange={e=>setHeight(+e.target.value)}><option value={16}>Fin</option><option value={20}>Normal</option><option value={28}>Large</option></select></div></div><div className="roll-viewport" ref={scroll}><svg ref={svg} width={width} height={totalHeight} role="img" aria-label={'Piano Roll '+currentTrack.name} onDoubleClick={add} onClick={e=>{if(draw&&e.target===svg.current)add(e);}} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>setDrag(null)} className={draw?'draw-mode':''}>
    {Array.from({length:MAX-MIN+1},(_,i)=>{const pitch=MAX-i,y=RULER+i*height;const black=[1,3,6,8,10].includes(pitch%12);return <g key={pitch}><rect x={GUTTER} y={y} width={width-GUTTER} height={height} className={black?'roll-row black-row':'roll-row'}/><line x1={GUTTER} x2={width} y1={y} y2={y} className="roll-horizontal"/><rect y={y} width={GUTTER-1} height={height} className={black?'row-key black-key':'row-key'}/><text x={GUTTER-8} y={y+height*.68} textAnchor="end" className={'row-note '+(pitch%12===0?'root-note':'')}>{noteName(pitch)}</text></g>;})}
    {Array.from({length:Math.ceil(beats/step)+1},(_,i)=>{const b=i*step;if(b>beats)return null;const bar=Math.abs(b/info.barBeats-Math.round(b/info.barBeats))<.0001;const pulse=Math.abs(b/info.pulse-Math.round(b/info.pulse))<.0001;const middle=info.compound&&Math.abs((b%info.barBeats)-1.5)<.0001;return <line key={i} x1={GUTTER+b*zoom} x2={GUTTER+b*zoom} y1={RULER} y2={totalHeight} className={bar?'grid-bar':middle?'grid-group':pulse?'grid-pulse':'grid-subdivision'}/>;})}
    {loop&&<rect x={GUTTER+project.settings.loopStart*zoom} y={RULER} width={(project.settings.loopEnd-project.settings.loopStart)*zoom} height={totalHeight-RULER} className="loop-region" pointerEvents="none"/>}
    {project.tracks.slice().sort((a,b)=>a.id===trackId?1:b.id===trackId?-1:0).flatMap(t=>t.events.map(original=>{const n=drag?.id===original.id?drag.current:original;if(n.midiPitch<MIN||n.midiPitch>MAX)return null;const x=GUTTER+noteStart(n)*zoom,y=RULER+(MAX-n.midiPitch)*height+2,w=Math.max(8,noteDuration(n)*zoom),chosen=selected?.id===n.id;return <g key={n.id} data-note-id={n.id} data-pitch={n.midiPitch} className={'roll-event '+(t.id===trackId?'':'ghost-event ')+(chosen?'selected-note':'')} onPointerDown={e=>startDrag(e,t.id,n)} onDoubleClick={e=>e.stopPropagation()} style={{'--note-color':t.color} as React.CSSProperties}><rect x={x} y={y} width={w} height={height-4} rx={3} className="note-block"/><text x={x+6} y={y+(height-4)*.72} className="note-label" pointerEvents="none">{w>28?midiToSolfa(n.midiPitch,project.tonic):''}</text><rect data-resize="true" x={x+Math.max(0,w-12)} y={y} width={Math.min(16,w)} height={height-4} className="note-handle"/><title>{t.name} · {noteName(n.midiPitch)} · {midiToSolfa(n.midiPitch,project.tonic)} · {noteDuration(n).toFixed(3)} temps</title></g>;}))}
    <rect x={0} y={0} width={width} height={RULER} className="ruler-background"/>{Array.from({length:bars},(_,i)=><g key={i} onClick={()=>!locked&&seek(i*info.barBeats)} className="ruler-marker"><text x={GUTTER+i*info.barBeats*zoom+8} y={20} className="bar-number">{String(i+1).padStart(2,'0')}</text>{Array.from({length:info.numerator-1},(_,j)=><text key={j} x={GUTTER+(i*info.barBeats+(j+1)*info.pulse)*zoom+3} y={20} className="pulse-number">{j+2}</text>)}</g>)}
    <line x1={GUTTER+beat*zoom} x2={GUTTER+beat*zoom} y1={0} y2={totalHeight} className="playhead" pointerEvents="none"/><path d={`M${GUTTER+beat*zoom-5},0 h10 l-5,7 z`} className="playhead-cap"/>
  </svg></div><div className="roll-help"><span>{draw?'Cliquez dans la grille pour ajouter une note.':'Double-clic : ajouter · Glisser : déplacer · Bord droit : durée'}</span><span>{bars} mesures · {info.compound?'3 + 3 croches':'grille en temps'}</span></div></section>;
}
