import { memo,useEffect,useMemo,useRef,useState } from 'react';
import { Music2,Minus,Plus } from 'lucide-react';
import type { NoteEvent,Project } from '../music/model';
import { engraveProject,pageSVG,type ScoreDocument } from '../score/engraving';
import { beatToScoreX } from '../score/layout';
import { measureForBeat } from '../music/timeline';
interface Props {project:Project;beat:number;running:boolean;compact?:boolean;document?:ScoreDocument;onNoteClick?:(note:NoteEvent)=>void}
const Paper=memo(function Paper({html,width,height}:{html:string;width:number;height:number}){return <div className="engraved-content" style={{width,height}} dangerouslySetInnerHTML={{__html:html}}/>;});
export function SolfaScore({project,beat,running,compact,document:provided,onNoteClick}:Props){const ref=useRef<HTMLDivElement>(null),[zoom,setZoom]=useState(compact?.8:1);const result=useMemo(()=>{try{return {doc:provided??engraveProject(project),error:''};}catch(e){return {doc:null,error:e instanceof Error?e.message:'Rendu indisponible.'};}},[project,provided]);const doc=result.doc,current=measureForBeat(project,beat).number,system=doc?.systems.find(s=>s.first<=current&&s.last>=current),position=system?.measures.find(m=>m.number===current);const pages=useMemo(()=>doc?.pages.map(p=>pageSVG(p))??[],[doc]);
  useEffect(()=>{if(running&&system&&ref.current){const page=ref.current.querySelector('[data-page="'+system.page+'"]') as HTMLElement|null;if(page)ref.current.scrollTop=page.offsetTop+system.y*zoom-40;}},[current,running,system?.page,zoom]);
  return <section className={'score-panel '+(compact?'compact-score':'')}><div className="panel-bar"><span className="panel-eyebrow"><Music2 size={15}/> PARTITION SOLFA</span><div className="score-zoom"><button aria-label="Réduire la partition" onClick={()=>setZoom(z=>Math.max(.35,z-.1))}><Minus size={14}/></button><span>{Math.round(zoom*100)} %</span><button aria-label="Agrandir la partition" onClick={()=>setZoom(z=>Math.min(1.8,z+.1))}><Plus size={14}/></button><span className="score-key">Do = {project.tonic}</span></div></div><div className="score-viewport engraved-viewport" ref={ref}>{result.error&&<p role="alert" className="score-error">{result.error}</p>}{doc?.pages.map((page,index)=><div className="engraved-page" data-page={index} key={index} style={{width:page.width*zoom,height:page.height*zoom}} onClick={e=>{const key=(e.target as Element).closest('[data-note-id]')?.getAttribute('data-note-id');if(key){const note=project.tracks.flatMap(t=>t.events).find(n=>n.id===key);if(note)onNoteClick?.(note);}}}><div className="engraved-scale" style={{width:page.width,height:page.height,transform:'scale('+zoom+')'}}><Paper html={pages[index]} width={page.width} height={page.height}/>{running&&system?.page===index&&position&&<svg className="score-cursor" width={page.width} height={page.height} aria-hidden="true"><rect x={position.x} y={position.y-4} width={position.width} height={position.height+8} fill="#ab94e617"/><line x1={position.x+position.inset+beatToScoreX(position.geometry,beat)*position.scale} x2={position.x+position.inset+beatToScoreX(position.geometry,beat)*position.scale} y1={position.y-4} y2={position.y+position.height+4} stroke="#a184dc" strokeWidth={2}/></svg>}</div></div>)}</div></section>;
}
