import { useEffect, useMemo, useRef } from 'react';
import { Music2 } from 'lucide-react';
import { noteDuration,noteStart, projectEnd,signatureInfo,type Project } from '../music/model';
import { beatToScoreX,layoutMeasure,measureGeometry } from '../score/layout';
interface Props {project:Project;beat:number;running:boolean;compact?:boolean}
const LEFT=54,BAR=234,ROW=37,SYSTEM=208,TOP=24;
export function SolfaScore({project,beat,running,compact}:Props){const ROW=compact?27:37,SYSTEM=compact?170:208,TOP=compact?16:24;const ref=useRef<HTMLDivElement>(null);const info=signatureInfo(project.timeSignature);const bars=Math.max(4,Math.ceil(projectEnd(project)/info.barBeats));const perSystem=4,systems=Math.ceil(bars/perSystem),height=TOP+systems*SYSTEM+10;const measures=useMemo(()=>Array.from({length:bars},(_,bar)=>{const geometry=measureGeometry(project,bar,BAR-16);return {geometry,cells:project.tracks.map((_,ti)=>layoutMeasure(project,ti,bar,BAR-16,geometry))};}),[project,bars]);const offsets=measures.map((_,bar)=>measures.slice(Math.floor(bar/perSystem)*perSystem,bar).reduce((sum,m)=>sum+m.geometry.width+16,LEFT));const width=Math.max(...measures.map((m,i)=>offsets[i]+m.geometry.width+36));const activeBar=Math.floor(beat/info.barBeats);useEffect(()=>{if(running&&ref.current&&!compact)ref.current.scrollTop=Math.floor(activeBar/perSystem)*SYSTEM;},[activeBar,running,compact]);
  return <section className={'score-panel '+(compact?'compact-score':'')}><div className="panel-bar"><span className="panel-eyebrow"><Music2 size={15}/> PARTITION SOLFA</span><span className="score-key">Do = {project.tonic} · {project.timeSignature}</span></div><div className="score-viewport" ref={ref}><div className="score-paper" style={{width:width+48,minWidth:width+48}}><header className="score-heading"><div><h2>{project.title}</h2><span>Do = {project.tonic} &nbsp; {project.timeSignature} &nbsp; ♩ = {project.tempo}</span></div><div>{project.author&&<span>{project.author}</span>}{project.composer&&<span>Composition : {project.composer}</span>}</div></header><svg width={width} height={height} role="img" aria-label={'Partition Solfa '+project.title}>
    {Array.from({length:systems},(_,system)=>{const y=TOP+system*SYSTEM;return <g key={system}>{project.tracks.map((t,ti)=><text key={t.id} x={10} y={y+ti*ROW+21} className="score-voice">{t.shortName}</text>)}{Array.from({length:perSystem},(_,bi)=>{const bar=system*perSystem+bi;if(bar>=bars)return null;const x=offsets[bar],{geometry,cells}=measures[bar];return <g key={bar}><text x={x+3} y={y-7} className="score-bar-number">{bar+1}</text><line x1={x} x2={x} y1={y} y2={y+ROW*4-4} className="score-barline"/>{info.compound&&<line x1={x+beatToScoreX(geometry,geometry.begin+1.5)+8} x2={x+beatToScoreX(geometry,geometry.begin+1.5)+8} y1={y} y2={y+ROW*4-4} className="score-group-line"/>}{cells.map((line,ti)=>line.map((cell,ci)=><g key={ti+':'+ci} data-score-beat={cell.beat}><text x={x+cell.x+10} y={y+ti*ROW+24} className={'score-symbol '+(cell.kind==='rest'?'score-rest':'')+(running&&cell.noteIds.some(id=>project.tracks[ti].events.some(n=>n.id===id&&noteStart(n)<=beat&&noteStart(n)+noteDuration(n)>beat))?' score-active':'')} data-solfa={cell.symbols.join('+')}>{cell.symbols.join('/')}</text>{ci<line.length-1&&line[ci+1].x-cell.x>24&&<text x={x+line[ci+1].x-7} y={y+ti*ROW+23} className="score-colon">:</text>}</g>))}<line x1={x+geometry.width+16} x2={x+geometry.width+16} y1={y} y2={y+ROW*4-4} className="score-barline"/></g>;})}{running&&activeBar<bars&&Math.floor(activeBar/perSystem)===system&&<line x1={offsets[activeBar]+beatToScoreX(measures[activeBar].geometry,beat)+9} x2={offsets[activeBar]+beatToScoreX(measures[activeBar].geometry,beat)+9} y1={y-3} y2={y+ROW*4+2} className="score-playhead"/>}{project.lyrics.filter(l=>l.text.trim()).map((line,i)=><text key={line.id} x={LEFT+9} y={y+ROW*4+20+i*19} className="score-lyrics">{system===0?line.text:''}</text>)}</g>;})}
  </svg><footer className="score-legend">0 silence · – tenue · ' octave supérieure · , octave inférieure · di / fi… altérations</footer></div></div></section>;
}
