import {FloatingMenu} from './FloatingMenu';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {Project} from '../music/model';
import {TapTempoEstimator,internalTapTempo,applyTapTempo,type TapResult} from '../music/tap-tempo';
import {measureForBeat,tempoLabel} from '../music/timeline';
export function TapTempo({project:p,beat,locked,update,notice}:{project:Project;beat:number;locked:boolean;update:(fn:(p:Project)=>void)=>boolean;notice:(s:string)=>void}){
 const estimator=useRef(new TapTempoEstimator(p.settings.tapLimits)),button=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null),[result,setResult]=useState<TapResult|null>(null),[open,setOpen]=useState(false),[position,setPosition]=useState({left:0,top:0}),[pending,setPending]=useState<{projectId:string;tempo:number;scope:'project'|'measure';measure:number}|null>(null);
 const tap=()=>{setResult(estimator.current.tap(performance.now()));const rect=button.current?.getBoundingClientRect();if(rect)setPosition({left:Math.max(8,Math.min(window.innerWidth-308,rect.left)),top:Math.min(rect.bottom+8,window.innerHeight-260)});setOpen(true);};
 const latest=useRef(tap);latest.current=tap;
 useEffect(()=>{estimator.current=new TapTempoEstimator(p.settings.tapLimits);setResult(null);},[p.id,p.settings.tapLimits?.minBpm,p.settings.tapLimits?.maxBpm]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(e.code==='KeyB'&&!e.repeat&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!document.querySelector('dialog[open]')&&!target.matches('input,textarea,select')&&!target.isContentEditable){e.preventDefault();latest.current();}if(e.code==='Escape')setOpen(false);};const outside=(e:PointerEvent)=>{if(!panel.current?.contains(e.target as Node)&&!button.current?.contains(e.target as Node))setOpen(false);};window.addEventListener('keydown',down);window.addEventListener('pointerdown',outside);return ()=>{window.removeEventListener('keydown',down);window.removeEventListener('pointerdown',outside);};},[]);
 useEffect(()=>{if(!locked&&pending){const action=pending;setPending(null);if(action.projectId===p.id&&update(p=>applyTapTempo(p,action.tempo,action.scope,action.measure)))notice('Tempo Tap appliqué après la prise.');}},[locked,pending,p.id]);
 function apply(scope:'project'|'measure'){if(!result)return;try{const tempo=internalTapTempo(result.bpm,p.settings.tempoUnit),measure=measureForBeat(p,beat).number;if(locked){setPending({projectId:p.id,tempo,scope,measure});notice('Le tempo sera appliqué après l’arrêt de cette prise.');}else if(update(p=>applyTapTempo(p,tempo,scope,measure)))notice('Tempo Tap appliqué.');setOpen(false);}catch(e){notice(e instanceof Error?e.message:'Tempo invalide.');}}
 return <><button ref={button} className="tap-button" aria-label="Tap Tempo" title="Frappes régulières · raccourci B" onClick={tap}>TAP{result&&<small>{Math.round(result.bpm)}</small>}</button>{open&&createPortal(<FloatingMenu menuRef={panel} className="tap-panel" role="group" label="Réglage Tap Tempo" x={position.left} y={position.top}><header><strong>Tap Tempo · {tempoLabel(p.settings.tempoUnit)}</strong><button aria-label="Fermer Tap Tempo" onClick={()=>setOpen(false)}>×</button></header><output aria-live="polite">{result?(result.stable?'Tempo stabilisé : ':'Estimation : ')+result.bpm+' BPM':'Au moins trois frappes régulières'}</output><small>Le tempo interne reste exprimé à la noire.</small><button disabled={!result} onClick={()=>apply('project')}>{locked?'Appliquer après la prise':'Appliquer au projet'}</button><button disabled={!result} onClick={()=>apply('measure')}>{locked?'Changement après la prise':'Changement à la mesure '+measureForBeat(p,beat).number}</button><button onClick={()=>{estimator.current.reset();setResult(null);}}>Recommencer le Tap</button><details><summary>Plage et pulsation</summary><div className="form-grid"><label>BPM minimum<input aria-label="Minimum Tap BPM" type="number" min={20} max={(p.settings.tapLimits?.maxBpm??240)-1} value={p.settings.tapLimits?.minBpm??30} disabled={locked} onChange={e=>{const min=+e.target.value,max=p.settings.tapLimits?.maxBpm??240;if(min>=20&&min<max)update(p=>{p.settings.tapLimits={minBpm:min,maxBpm:max};});}}/></label><label>BPM maximum<input aria-label="Maximum Tap BPM" type="number" min={(p.settings.tapLimits?.minBpm??30)+1} max={300} value={p.settings.tapLimits?.maxBpm??240} disabled={locked} onChange={e=>{const max=+e.target.value,min=p.settings.tapLimits?.minBpm??30;if(max>min&&max<=300)update(p=>{p.settings.tapLimits={minBpm:min,maxBpm:max};});}}/></label></div><label className="checkbox-label"><input type="checkbox" checked={p.settings.metronomePulse==='tempo'} disabled={locked} onChange={e=>update(p=>{p.settings.metronomePulse=e.target.checked?'tempo':'subdivision';})}/>Métronome à l’unité de tempo choisie</label></details>{pending&&<button onClick={()=>setPending(null)}>Annuler le tempo en attente</button>}</FloatingMenu>,document.body)}</>;
}
