import { id,noteDuration,noteStart,signatureInfo,type NoteEvent,type Project,type TrackId } from './model.ts';
import { measureAt,measureCount,tempoAt,invalidateTimeline } from './timeline.ts';
import { validateRepeats } from './repeats.ts';
import { quantize } from '../quantization/quantizer.ts';
export type EditScope=TrackId|'all';
export type MeasureAction='insert-before'|'insert-after'|'delete'|'duplicate'|'clear'|'quantize'|'transpose'|'move';
export interface MusicBlock {duration:number;measureLength:number;tracks:{id:string;events:NoteEvent[]}[];lyrics:Project['lyrics'];sourceStart:number;signatures:Project['signatureMap'];tempos:Project['tempoMap'];markers:Project['markers'];indications:Project['indications'];repeats:Project['repeats'];takes:Project['takes'];hasPickup:boolean}
export function placeNote(n:NoteEvent,start:number,duration=noteDuration(n)):NoteEvent {const copy={...n,editStart:start,editDuration:duration};if(copy.quantizedStart!==undefined)copy.quantizedStart=start;if(copy.quantizedDuration!==undefined)copy.quantizedDuration=duration;return copy;}
export function cleanLyrics(p:Project){const notes=new Map(p.tracks.flatMap(t=>t.events.map(n=>[n.id,n] as const)));for(const line of p.lyrics)for(const syllable of line.syllables){const ids=(syllable.noteIds??(syllable.noteId?[syllable.noteId]:[])).filter(key=>notes.has(key));syllable.noteIds=ids;syllable.noteId=ids[0];if(ids.length){syllable.startBeat=Math.min(...ids.map(key=>noteStart(notes.get(key)!)));syllable.endBeat=Math.max(...ids.map(key=>noteStart(notes.get(key)!)+noteDuration(notes.get(key)!)));}else{delete syllable.startBeat;delete syllable.endBeat;}}}
function chosen(p:Project,scope:EditScope){return p.tracks.filter(t=>scope==='all'||t.id===scope);}
export function removeRange(events:NoteEvent[],start:number,end:number):NoteEvent[]{return events.flatMap(n=>{const on=noteStart(n),off=on+noteDuration(n);if(on>=end||off<=start)return [n];const fragments:NoteEvent[]=[];if(on<start)fragments.push(placeNote(n,on,start-on));if(off>end)fragments.push(placeNote({...n,id:fragments.length?id():n.id},end,off-end));return fragments;});}
export function copyMeasures(p:Project,first:number,last:number,scope:EditScope):MusicBlock{const start=measureAt(p,first).start,end=measureAt(p,last).end;const ids=new Set<string>();const tracks=chosen(p,scope).map(t=>({id:t.id,events:t.events.flatMap(n=>{const on=noteStart(n),off=on+noteDuration(n);if(on>=end||off<=start)return [];ids.add(n.id);return [placeNote(structuredClone(n),Math.max(start,on)-start,Math.min(end,off)-Math.max(start,on))];})}));const lyrics=p.lyrics.filter(l=>tracks.some(t=>t.id===l.trackId)).map(l=>({...structuredClone(l),syllables:l.syllables.filter(s=>(s.noteIds??(s.noteId?[s.noteId]:[])).some(key=>ids.has(key)))}));const firstBar=measureAt(p,first);return {duration:end-start,measureLength:last-first+1,tracks,lyrics,sourceStart:start,
 signatures:[{measure:1,signature:firstBar.signature,groups:firstBar.groups},...p.signatureMap.filter(m=>m.measure>first&&m.measure<=last).map(m=>({...structuredClone(m),measure:m.measure-first+1}))],
 tempos:[{measure:1,bpm:tempoAt(p,start)},...p.tempoMap.filter(m=>m.measure>first&&m.measure<=last).map(m=>({...m,measure:m.measure-first+1}))],
 markers:p.markers.filter(m=>m.measure>=first&&m.measure<=last).map(m=>({...m,measure:m.measure-first+1})),
 indications:p.indications.filter(m=>m.measure>=first&&m.measure<=last&&(scope==='all'||m.trackId===scope)).map(m=>({...m,measure:m.measure-first+1})),
 repeats:p.repeats.filter(r=>r.startMeasure>=first&&(r.secondEndingEnd??r.endMeasure)<=last).map(r=>({...r,startMeasure:r.startMeasure-first+1,endMeasure:r.endMeasure-first+1,firstEndingStart:r.firstEndingStart===undefined?undefined:r.firstEndingStart-first+1,secondEndingEnd:r.secondEndingEnd===undefined?undefined:r.secondEndingEnd-first+1})),
 takes:p.takes.filter(t=>(scope==='all'||t.trackId===scope)&&t.startBeat>=start&&t.endBeat<=end).map(t=>({...structuredClone(t),startBeat:t.startBeat-start,endBeat:t.endBeat-start,events:t.events.map(n=>placeNote(structuredClone(n),noteStart(n)-start))})),
 hasPickup:first===1&&p.settings.pickupBeats>0&&firstBar.barBeats<signatureInfo(firstBar.signature).barBeats};}
function shift(p:Project,boundary:number,delta:number,scope:EditScope){
 const transform=(n:NoteEvent)=>{const start=noteStart(n),duration=noteDuration(n);return start>=boundary?placeNote(n,start+delta):start+duration>boundary?placeNote(n,start,Math.max(.03125,duration+delta)):n;};
 for(const t of chosen(p,scope))t.events=t.events.map(transform);
 for(const take of p.takes.filter(t=>scope==='all'||t.trackId===scope)){take.events=take.events.map(transform);take.startBeat=take.startBeat>=boundary?take.startBeat+delta:take.startBeat;take.endBeat=take.endBeat>boundary?take.endBeat+delta:take.endBeat;}
 if(scope==='all')for(const key of ['loop','punch'] as const){const start=p.settings[key==='loop'?'loopStart':'punchStart'],end=p.settings[key==='loop'?'loopEnd':'punchEnd'];p.settings[key==='loop'?'loopStart':'punchStart']=start>=boundary?Math.max(0,start+delta):start;p.settings[key==='loop'?'loopEnd':'punchEnd']=end>boundary?Math.max(0,end+delta):end;}
}
function shiftStructure(p:Project,first:number,count:number){const adjust=(number:number)=>number>=first?Math.max(first,number+count):number;p.markers.forEach(m=>m.measure=adjust(m.measure));p.tempoMap.forEach(m=>m.measure=adjust(m.measure));p.signatureMap.forEach(m=>m.measure=adjust(m.measure));p.indications.forEach(m=>m.measure=adjust(m.measure));p.repeats.forEach(r=>{r.startMeasure=adjust(r.startMeasure);r.endMeasure=Math.max(r.startMeasure,adjust(r.endMeasure));if(r.firstEndingStart!==undefined)r.firstEndingStart=adjust(r.firstEndingStart);if(r.secondEndingEnd!==undefined)r.secondEndingEnd=adjust(r.secondEndingEnd);});p.layout.systemBreaks=p.layout.systemBreaks.map(adjust);invalidateTimeline(p);}
function ensureNormalBlock(p:Project,block:MusicBlock,afterMeasure:number,scope:EditScope){if(scope==='all'&&(block.hasPickup||afterMeasure===0&&p.settings.pickupBeats>0))throw new Error('La levée reste au début du morceau. Déplacez ou dupliquez les mesures complètes après elle.');}
function repairRegions(p:Project){for(const kind of ['loop','punch'] as const){const startKey=kind==='loop'?'loopStart':'punchStart',endKey=kind==='loop'?'loopEnd':'punchEnd';if(p.settings[endKey]<=p.settings[startKey])p.settings[endKey]=p.settings[startKey]+measureAt(p,1).barBeats;}p.takes=p.takes.filter(t=>t.endBeat>t.startBeat);}
export function pasteBlock(p:Project,block:MusicBlock,afterMeasure:number,scope:EditScope,insert=true){if(insert)ensureNormalBlock(p,block,afterMeasure,scope);const following=measureAt(p,afterMeasure+1),target=afterMeasure===0?0:measureAt(p,afterMeasure).end,oldCount=measureCount(p),followingTempo=tempoAt(p,target);if(insert){shift(p,target,block.duration,scope);if(scope==='all'){shiftStructure(p,afterMeasure+1,block.measureLength);const end=afterMeasure+block.measureLength+1;p.signatureMap=p.signatureMap.filter(m=>m.measure!==end);p.tempoMap=p.tempoMap.filter(m=>m.measure!==end);p.signatureMap.push(...block.signatures.map(m=>({...structuredClone(m),measure:m.measure+afterMeasure})),{measure:end,signature:following.signature,groups:following.groups});p.tempoMap.push(...block.tempos.map(m=>({...m,measure:m.measure+afterMeasure})),{measure:end,bpm:followingTempo});p.settings.measureCount=oldCount+block.measureLength;invalidateTimeline(p);}}
  const noteMap=new Map<string,string>();for(const source of block.tracks){const destination=scope==='all'?p.tracks.find(t=>t.id===source.id):p.tracks.find(t=>t.id===scope);if(!destination)continue;for(const n of source.events){const key=id();noteMap.set(n.id,key);destination.events.push(placeNote({...structuredClone(n),id:key,trackId:destination.id,tieFrom:undefined,tieTo:undefined},target+noteStart(n)));}}
  for(const source of block.lyrics){const trackId=scope==='all'?source.trackId:scope;const syllables=source.syllables.map(s=>({...s,id:id(),noteIds:(s.noteIds??(s.noteId?[s.noteId]:[])).map(key=>noteMap.get(key)).filter((key):key is string=>!!key)})).filter(s=>s.noteIds.length);if(!syllables.length)continue;const line=p.lyrics.find(l=>l.trackId===trackId&&l.verse===source.verse&&l.kind===source.kind);if(line)line.syllables.push(...syllables);else p.lyrics.push({...source,id:id(),trackId,syllables});}
  if(scope==='all'){p.markers.push(...block.markers.map(m=>({...m,id:id(),measure:m.measure+afterMeasure})));p.indications.push(...block.indications.map(m=>({...m,id:id(),measure:m.measure+afterMeasure})));p.repeats.push(...block.repeats.map(r=>({...r,id:id(),startMeasure:r.startMeasure+afterMeasure,endMeasure:r.endMeasure+afterMeasure,firstEndingStart:r.firstEndingStart===undefined?undefined:r.firstEndingStart+afterMeasure,secondEndingEnd:r.secondEndingEnd===undefined?undefined:r.secondEndingEnd+afterMeasure})));validateRepeats(p.repeats);}
  for(const take of block.takes){const trackId=scope==='all'?take.trackId:scope;p.takes.push({...structuredClone(take),id:id(),trackId,startBeat:target+take.startBeat,endBeat:target+take.endBeat,events:take.events.map(n=>placeNote({...n,id:noteMap.get(n.id)??id(),trackId},target+noteStart(n)))});}
  repairRegions(p);invalidateTimeline(p);cleanLyrics(p);
}
export function transpose(p:Project,semitones:number,scope:EditScope='all',first?:number,last?:number){if(!Number.isInteger(semitones)||Math.abs(semitones)>48)throw new Error('Transposition invalide.');const start=first?measureAt(p,first).start:0,end=last?measureAt(p,last).end:Infinity;const notes=chosen(p,scope).flatMap(t=>t.events).filter(n=>noteStart(n)>=start&&noteStart(n)<end);if(notes.some(n=>n.midiPitch+semitones<0||n.midiPitch+semitones>127))throw new Error('La transposition dépasserait les hauteurs MIDI 0–127.');for(const n of notes)n.midiPitch+=semitones;}
export function editMeasures(p:Project,action:MeasureAction,first:number,last:number,scope:EditScope='all',target=last,amount=0){if(!Number.isInteger(first)||!Number.isInteger(last)||first<1||last<first||last>10000)throw new Error('Sélection de mesures invalide.');const start=measureAt(p,first).start,end=measureAt(p,last).end,duration=end-start,count=last-first+1,oldCount=measureCount(p);
  if(action==='transpose'){transpose(p,amount,scope,first,last);return;}
  if(action==='quantize'){for(const t of chosen(p,scope)){const region=t.events.filter(n=>noteStart(n)>=start&&noteStart(n)<end),quantized=new Map(quantize(region,p.settings.quantization,p.settings.quantizationStrength).map(n=>[n.id,n]));t.events=t.events.map(n=>quantized.get(n.id)??n);}return;}
  if(action==='duplicate'){pasteBlock(p,copyMeasures(p,first,last,scope),target,scope);return;}
  if(action==='move'){if(target>=first-1&&target<=last)throw new Error('La destination doit être en dehors de la sélection.');const block=copyMeasures(p,first,last,scope);ensureNormalBlock(p,block,target,scope);editMeasures(p,'delete',first,last,scope);pasteBlock(p,block,target>last?target-count:target,scope);return;}
  if(action==='insert-before'||action==='insert-after'){const block=copyMeasures(p,first,last,scope);block.tracks=block.tracks.map(t=>({...t,events:[]}));block.lyrics=[];block.markers=[];block.indications=[];block.repeats=[];block.takes=[];pasteBlock(p,block,action==='insert-before'?first-1:last,scope);return;}
  const fragments=new Map<string,NoteEvent[]>();const clip=(n:NoteEvent)=>{if(!fragments.has(n.id))fragments.set(n.id,removeRange([n],start,end));return structuredClone(fragments.get(n.id)!);};
  for(const t of chosen(p,scope))t.events=t.events.flatMap(clip);
  for(const take of p.takes.filter(t=>scope==='all'||t.trackId===scope)){take.events=take.events.flatMap(clip);if(action==='delete'){take.startBeat=take.startBeat>=start&&take.startBeat<end?start:take.startBeat;take.endBeat=take.endBeat>start&&take.endBeat<=end?start:take.endBeat;}}
  if(action==='delete'){
    if(scope==='all'){
      const following=measureAt(p,last+1),followingTempo=tempoAt(p,end);
      p.markers=p.markers.filter(m=>m.measure<first||m.measure>last);p.indications=p.indications.filter(m=>m.measure<first||m.measure>last);p.signatureMap=p.signatureMap.filter(m=>m.measure<first||m.measure>last);p.tempoMap=p.tempoMap.filter(m=>m.measure<first||m.measure>last);
      p.repeats=p.repeats.filter(r=>r.startMeasure<first||(r.secondEndingEnd??r.endMeasure)>last).map(r=>({...r,startMeasure:r.startMeasure>=first&&r.startMeasure<=last?last+1:r.startMeasure,endMeasure:r.endMeasure>=first&&r.endMeasure<=last?first-1:r.endMeasure,firstEndingStart:r.firstEndingStart!==undefined&&r.firstEndingStart>=first&&r.firstEndingStart<=last?last+1:r.firstEndingStart,secondEndingEnd:r.secondEndingEnd!==undefined&&r.secondEndingEnd>=first&&r.secondEndingEnd<=last?first-1:r.secondEndingEnd})).filter(r=>r.endMeasure>=r.startMeasure);
      p.layout.systemBreaks=p.layout.systemBreaks.filter(n=>n<first||n>last);shiftStructure(p,last+1,-count);p.signatureMap=p.signatureMap.filter(m=>m.measure!==first);p.tempoMap=p.tempoMap.filter(m=>m.measure!==first);p.signatureMap.push({measure:first,signature:following.signature,groups:following.groups});p.tempoMap.push({measure:first,bpm:followingTempo});if(first===1)p.settings.pickupBeats=0;
      for(const r of p.repeats)if(r.firstEndingStart!==undefined&&(r.firstEndingStart>r.endMeasure||r.secondEndingEnd!==undefined&&r.secondEndingEnd<=r.endMeasure)){delete r.firstEndingStart;delete r.secondEndingEnd;}
      p.settings.measureCount=Math.max(1,oldCount-count);invalidateTimeline(p);
    }
    if(scope==='all')for(const kind of ['loop','punch'] as const){const startKey=kind==='loop'?'loopStart':'punchStart',endKey=kind==='loop'?'loopEnd':'punchEnd';if(p.settings[startKey]>=start&&p.settings[startKey]<end)p.settings[startKey]=start;if(p.settings[endKey]>start&&p.settings[endKey]<=end)p.settings[endKey]=start;}
    shift(p,end,-duration,scope);
  }
  repairRegions(p);invalidateTimeline(p);validateRepeats(p.repeats);
  cleanLyrics(p);
}
