import type { Project,RepeatSection } from './model.ts';
import { measureAt,measureCount,secondsBetween,beatAfterSeconds } from './timeline.ts';
export interface PlaybackChunk {songStart:number;songEnd:number;rawStart:number;rawEnd:number;secondsStart:number;secondsEnd:number}
const cache=new WeakMap<Project,PlaybackChunk[]>();
export function validateRepeats(repeats:RepeatSection[]){const sorted=repeats.slice().sort((a,b)=>a.startMeasure-b.startMeasure);for(let i=0;i<sorted.length;i++){const r=sorted[i];if(r.firstEndingStart!==undefined&&(!Number.isInteger(r.firstEndingStart)||r.firstEndingStart<r.startMeasure||r.firstEndingStart>r.endMeasure))throw new Error('Première fin invalide.');if(r.secondEndingEnd!==undefined&&(!Number.isInteger(r.secondEndingEnd)||r.secondEndingEnd<=r.endMeasure||r.firstEndingStart===undefined))throw new Error('Deuxième fin invalide.');if(i&&r.startMeasure<=(sorted[i-1].secondEndingEnd??sorted[i-1].endMeasure))throw new Error('Les reprises ne peuvent pas se chevaucher dans cette version.');}}
export function playbackMeasureOrder(p:Project):number[]{validateRepeats(p.repeats);const count=measureCount(p),order:number[]=[];for(let measure=1;measure<=count;measure++){const repeat=p.repeats.find(r=>r.startMeasure===measure);if(!repeat){order.push(measure);continue;}for(let pass=1;pass<=repeat.times;pass++){for(let n=repeat.startMeasure;n<=repeat.endMeasure;n++){if(pass===repeat.times&&repeat.firstEndingStart!==undefined&&n>=repeat.firstEndingStart)continue;order.push(n);}if(pass===repeat.times&&repeat.secondEndingEnd!==undefined)for(let n=repeat.endMeasure+1;n<=repeat.secondEndingEnd;n++)order.push(n);}measure=repeat.secondEndingEnd??repeat.endMeasure;if(order.length>100000)throw new Error('La lecture développée dépasse 100 000 mesures.');}return order;}
export function playbackChunks(p:Project):PlaybackChunk[]{let result=cache.get(p);if(result)return result;result=[];let raw=0,seconds=0;for(const number of playbackMeasureOrder(p)){const m=measureAt(p,number),duration=secondsBetween(p,m.start,m.end),previous=result.at(-1);if(previous&&Math.abs(previous.songEnd-m.start)<1e-8){previous.songEnd=m.end;previous.rawEnd+=m.barBeats;previous.secondsEnd+=duration;}else result.push({songStart:m.start,songEnd:m.end,rawStart:raw,rawEnd:raw+m.barBeats,secondsStart:seconds,secondsEnd:seconds+duration});raw+=m.barBeats;seconds+=duration;}cache.set(p,result);return result;}
export function playbackSongBeat(p:Project,raw:number){const chunks=playbackChunks(p),chunk=chunks.find(c=>raw>=c.rawStart&&raw<c.rawEnd)??chunks.at(-1)!;return chunk.songStart+(raw-chunk.rawStart);}
export function songToPlaybackBeat(p:Project,song:number){const chunk=playbackChunks(p).find(c=>song>=c.songStart&&song<c.songEnd)??playbackChunks(p).at(-1)!;return chunk.rawStart+song-chunk.songStart;}
function secondsAt(p:Project,raw:number){const chunk=playbackChunks(p).find(c=>raw>=c.rawStart&&raw<c.rawEnd)??playbackChunks(p).at(-1)!;return chunk.secondsStart+secondsBetween(p,chunk.songStart,chunk.songStart+raw-chunk.rawStart);}
export function playbackSeconds(p:Project,from:number,to:number){return secondsAt(p,to)-secondsAt(p,from);}
export function playbackBeat(p:Project,from:number,seconds:number){const absolute=secondsAt(p,from)+seconds,chunk=playbackChunks(p).find(c=>absolute>=c.secondsStart&&absolute<c.secondsEnd)??playbackChunks(p).at(-1)!;return chunk.rawStart+beatAfterSeconds(p,chunk.songStart,absolute-chunk.secondsStart)-chunk.songStart;}
