import { audibleTracks,noteDuration,noteStart,signatureInfo,type NoteEvent,type Project,type TrackId } from '../music/model.ts';
import { mapLoopBeat,measureForBeat,musicEnd,tempoAt,transportBeat,transportSeconds,type LoopRegion } from '../music/timeline.ts';
import { playbackBeat,playbackChunks,playbackSeconds,playbackSongBeat,songToPlaybackBeat } from '../music/repeats.ts';
import { rehearsalVolumes } from '../music/rehearsal.ts';
import { clickVoice,pianoVoice,type Voice } from './synth.ts';
export type TransportMode='idle'|'playing'|'paused'|'countin'|'preroll'|'recording';
export interface TransportState {mode:TransportMode;beat:number;rawBeat:number;countRemaining:number;meter:number[];activePitches:number[]}
export interface RecordOptions {start:number;end:number;preRollStart:number;loop:boolean;trackId:TrackId}
export class AudioEngine {
  context:AudioContext|null=null;private master:GainNode|null=null;private clickOutput:GainNode|null=null;private gains=new Map<TrackId,GainNode>();private pans=new Map<TrackId,StereoPannerNode>();
  private project:Project|null=null;private mode:TransportMode='idle';private originTime=0;private originBeat=0;private cursor=0;private startBeat=0;private playbackStart=0;private pausedBeat=0;
  private timer:ReturnType<typeof setInterval>|undefined;private frame=0;private lastEmit=0;private nextClick=0;private scheduled=new Map<string,number>();private scheduledVoices=new Set<Voice>();private clicks=new Set<OscillatorNode>();private live=new Map<string,{pitch:number;voice:Voice}>();private listeners=new Set<(state:TransportState)=>void>();
  private recordOptions:RecordOptions|null=null;private recordCycle=0;private audition:Project|null=null;private auditionRehearsal=false;
  metronome=false;metronomeVolume=.6;loop=false;rehearsal=false;latency:'auto'|'low'|'stable'='auto';
  onRecordingStart:()=>void=()=>{};onRecordLoop:(rawBeat:number,time:number)=>void=()=>{};onStop:()=>void=()=>{};onEnded:()=>void=()=>{};
  subscribe(fn:(s:TransportState)=>void){this.listeners.add(fn);return ()=>this.listeners.delete(fn);}
  async init(){if(!this.context){this.context=new AudioContext({latencyHint:this.latency==='stable'?'playback':'interactive'});this.master=this.context.createGain();this.master.gain.value=.72;const limiter=this.context.createDynamicsCompressor();limiter.threshold.value=-10;limiter.knee.value=10;limiter.ratio.value=6;this.master.connect(limiter).connect(this.context.destination);this.clickOutput=this.context.createGain();this.clickOutput.connect(this.master);if(this.project)this.applyMixer(this.project);}if(this.context.state!=='running')await this.context.resume();return this.context;}
  setProject(project:Project){if(this.audition)this.stop();const old=this.project;if(old&&old.id!==project.id)this.stop();const running=this.mode==='playing',beat=this.rawBeat();this.project=project;this.applyMixer(project);if(running&&old&&(old.tempo!==project.tempo||old.timeSignature!==project.timeSignature||JSON.stringify(old.tempoMap)!==JSON.stringify(project.tempoMap)||JSON.stringify(old.signatureMap)!==JSON.stringify(project.signatureMap)||old.settings.rehearsalSpeed!==project.settings.rehearsalSpeed)){this.cancelScheduled();this.originTime=this.now+.02;this.originBeat=beat;this.cursor=beat;this.nextClick=beat;this.scheduleHeldNotes(this.position());}}
  private applyMixer(p:Project){if(!this.context||!this.master)return;const volumes=rehearsalVolumes(p,this.rehearsal);for(const [key,gain] of this.gains)if(!p.tracks.some(t=>t.id===key)){gain.disconnect();this.pans.get(key)?.disconnect();this.gains.delete(key);this.pans.delete(key);}this.master.gain.setTargetAtTime(p.settings.masterVolume,this.now,.015);for(const t of p.tracks){if(!this.gains.has(t.id)){const gain=this.context.createGain(),pan=this.context.createStereoPanner();gain.connect(pan).connect(this.master);this.gains.set(t.id,gain);this.pans.set(t.id,pan);}const volume=volumes.get(t.id)??0;this.gains.get(t.id)!.gain.setTargetAtTime(volume,this.now,.015);this.pans.get(t.id)?.pan.setTargetAtTime(t.pan??0,this.now,.015);}}
  refreshMixer(){if(this.project)this.applyMixer(this.project);}
  get now(){return this.context?.currentTime??0;}get status(){return this.mode;}
  private get speed(){return this.rehearsal&&this.mode!=='recording'&&this.mode!=='countin'&&this.mode!=='preroll'?(this.project?.settings.rehearsalSpeed??100)/100:1;}
  private loopRegion():LoopRegion|undefined{if(this.recordOptions?.loop)return {start:this.recordOptions.start,end:this.recordOptions.end};if((this.loop||this.audition)&&this.mode==='playing'&&this.project)return {start:this.project.settings.loopStart,end:this.project.settings.loopEnd};}
  get recordingOriginTime(){return this.project?this.originTime+transportSeconds(this.project,this.originBeat,this.startBeat)/this.speed:this.originTime;}
  private repeated(){return !!this.project?.repeats.length&&this.mode==='playing'&&!this.loop&&!this.audition;}
  private clockBeat(start:number,seconds:number){return this.repeated()?playbackBeat(this.project!,start,seconds):transportBeat(this.project!,start,seconds,this.loopRegion());}
  private clockSeconds(start:number,end:number){return this.repeated()?playbackSeconds(this.project!,start,end):transportSeconds(this.project!,start,end,this.loopRegion());}
  rawBeat(){if(this.mode==='idle'||this.mode==='paused')return this.pausedBeat;if(!this.context||!this.project)return 0;return Math.max(this.originBeat,this.clockBeat(this.originBeat,Math.max(0,this.context.currentTime-this.originTime)*this.speed));}
  position(){return Math.max(0,this.repeated()?playbackSongBeat(this.project!,this.rawBeat()):mapLoopBeat(this.rawBeat(),this.loopRegion()));}
  private timeAt(raw:number){return this.originTime+this.clockSeconds(this.originBeat,raw)/this.speed;}
  async play(from?:number){await this.init();if(!this.project)return;this.stopInternal();this.recordOptions=null;const start=from??this.pausedBeat;this.originBeat=(this.loop||this.audition)?Math.max(this.project.settings.loopStart,Math.min(start,this.project.settings.loopEnd-.001)):start;this.pausedBeat=this.originBeat;if(this.project.repeats.length&&!this.loop&&!this.audition)this.originBeat=songToPlaybackBeat(this.project,this.originBeat);this.originTime=this.now+.04;this.startBeat=this.playbackStart=this.originBeat;this.cursor=this.originBeat;this.mode='playing';this.startScheduler();this.scheduleHeldNotes(this.position());}
  async record(from:number,countIn:number,options?:RecordOptions){await this.init();if(!this.project)return;this.stopInternal();this.recordOptions=options??{start:from,end:Infinity,preRollStart:from,loop:false,trackId:this.project.tracks[0].id};this.recordCycle=countIn?-1:0;const bars=signatureInfo(measureForBeat(this.project,this.recordOptions.preRollStart).signature).barBeats;this.playbackStart=this.recordOptions.preRollStart;this.originBeat=this.playbackStart-countIn*bars;this.startBeat=this.recordOptions.start;this.originTime=this.now+(countIn?.06:.04);this.cursor=this.originBeat;this.mode=countIn?'countin':this.playbackStart<this.startBeat?'preroll':'recording';if(this.mode==='recording')this.onRecordingStart();this.startScheduler();}
  pause(){if(this.mode!=='playing')return;this.pausedBeat=this.position();this.mode='paused';this.stopInternal();this.emit();}
  stop(){this.synchronizeInput();this.onStop();this.mode='idle';this.pausedBeat=0;this.recordOptions=null;this.stopInternal();if(this.audition){this.project=this.audition;this.audition=null;this.rehearsal=this.auditionRehearsal;this.applyMixer(this.project);}this.emit();}
  seek(beat:number){if(this.mode==='playing'){void this.play(beat);return;}if(this.mode==='idle'||this.mode==='paused'){this.pausedBeat=Math.max(0,beat);this.emit();}}
  async auditionTake(project:Project,trackId:string,events:NoteEvent[],start:number,end:number){this.stop();this.audition=project;this.auditionRehearsal=this.rehearsal;this.rehearsal=false;this.project={...project,tracks:project.tracks.map(t=>({...t,mute:t.id!==trackId,solo:false,events:t.id===trackId?events:t.events})),settings:{...project.settings,loopStart:start,loopEnd:end,loopRepeats:1}};this.applyMixer(this.project);await this.play(start);}
  private startScheduler(){this.scheduled.clear();const m=measureForBeat(this.project!,Math.max(0,this.cursor));this.nextClick=this.cursor<0?Math.ceil(this.cursor/m.pulse)*m.pulse:m.start+Math.ceil((this.cursor-m.start)/m.pulse)*m.pulse;this.tick();this.timer=setInterval(()=>this.tick(),25);const render=(time:number)=>{if(time-this.lastEmit>32){this.lastEmit=time;this.emit();}if(this.mode!=='idle'&&this.mode!=='paused')this.frame=requestAnimationFrame(render);};this.frame=requestAnimationFrame(render);}
  private stopInternal(){if(this.timer)clearInterval(this.timer);this.timer=undefined;cancelAnimationFrame(this.frame);this.cancelScheduled();this.allNotesOff();}
  private cancelScheduled(){for(const voice of this.scheduledVoices)voice.stop();this.scheduledVoices.clear();for(const click of this.clicks){try{click.stop();}catch{}}this.clicks.clear();this.scheduled.clear();}
  private tick(){if(!this.context||!this.project)return;const p=this.project,now=this.now,raw=this.rawBeat();
    this.synchronizeInput();if(this.recordOptions&&this.mode==='recording'&&!this.recordOptions.loop&&raw>=this.recordOptions.end){this.stop();return;}
    const hi=Math.max(this.cursor,this.clockBeat(this.originBeat,Math.max(0,now+.12-this.originTime)*this.speed)),lo=Math.max(this.cursor,this.originBeat),loop=this.loopRegion(),len=loop?loop.end-loop.start:0;
    if(this.metronome||this.mode==='countin'||this.mode==='preroll'||this.mode==='recording'){
      while(this.nextClick<hi){const beat=this.nextClick,song=this.repeated()?playbackSongBeat(p,beat):mapLoopBeat(beat,loop),m=measureForBeat(p,Math.max(0,song));const index=beat<0?((Math.round(beat/m.pulse)%m.numerator)+m.numerator)%m.numerator:Math.round((song-m.start)/m.pulse);const groupStarts=m.groups.slice(0,-1).reduce<number[]>((result,n)=>[...result,(result.at(-1)??0)+n],[]);const accent:2|1|0=index===0?2:groupStarts.includes(index)?1:0,at=this.timeAt(beat);
        if(at>=now-.02){const click=clickVoice(this.context,this.clickOutput!,Math.max(at,now),accent,this.metronomeVolume);this.clicks.add(click);const cleanup=click.onended;click.onended=e=>{cleanup?.call(click,e);this.clicks.delete(click);};}
        const remaining=m.end-song;this.nextClick+=beat<0?m.pulse:Math.min(m.pulse,remaining>1e-7?remaining:m.pulse);
      }
    }else this.nextClick=hi;
    if(this.repeated()){
      for(const chunk of playbackChunks(p)){if(chunk.rawEnd<=lo||chunk.rawStart>=hi)continue;for(const track of p.tracks)for(const n of track.events){const on=noteStart(n),off=on+noteDuration(n);if(on>=chunk.songEnd||off<=chunk.songStart)continue;const start=Math.max(on,chunk.songStart),end=Math.min(off,chunk.songEnd);this.scheduleNote(n.id+':repeat:'+chunk.rawStart,track.id,n.midiPitch,n.velocity,chunk.rawStart+start-chunk.songStart,end-start,lo,hi);}}
    }else
    for(const track of p.tracks)for(const n of track.events){const start=noteStart(n);if(loop&&len>0){if(start<loop.start||start>=loop.end){if(this.recordOptions&&start>=this.playbackStart&&start<loop.start)this.scheduleNote(n.id,track.id,n.midiPitch,n.velocity,start,noteDuration(n),lo,hi);continue;}const first=Math.max(0,Math.floor((lo-loop.start)/len)),last=Math.floor((hi-loop.start)/len);for(let cycle=first;cycle<=last;cycle++)this.scheduleNote(n.id+':'+cycle,track.id,n.midiPitch,n.velocity,start+cycle*len,Math.min(noteDuration(n),loop.end-start),lo,hi);}else if(start>=this.playbackStart)this.scheduleNote(n.id,track.id,n.midiPitch,n.velocity,start,noteDuration(n),lo,hi);}
    this.cursor=hi;for(const [key,beat] of this.scheduled)if(beat<raw-8)this.scheduled.delete(key);
    if(this.mode==='playing'){if(loop&&p.settings.loopRepeats>0&&raw>=loop.end+(p.settings.loopRepeats-1)*len){this.stop();this.onEnded();}else if(!loop&&raw>=(this.repeated()?playbackChunks(p).at(-1)!.rawEnd:musicEnd(p))+.12){this.stop();this.onEnded();}}
  }
  /** Advance gates before input as well as scheduler ticks, so a NOTE OFF near a loop edge belongs to the correct take. */
  synchronizeInput(){if(!this.project||!this.recordOptions)return;const raw=this.rawBeat();
    if(this.mode==='countin'&&raw>=this.playbackStart){this.mode=this.playbackStart<this.startBeat?'preroll':'recording';if(this.mode==='preroll')this.recordCycle=0;}
    if(this.mode==='preroll'&&raw>=this.startBeat){this.mode='recording';this.onRecordingStart();}else if(this.mode==='recording'&&this.recordCycle===0&&this.recordOptions&&raw>=this.startBeat&&this.startBeat===this.playbackStart){/* already started by record */}
    // The count-in can enter recording directly without pre-roll.
    if(this.mode==='recording'&&this.recordOptions&&this.recordCycle===-1){this.recordCycle=0;this.onRecordingStart();}
    if(this.recordOptions&&this.mode==='recording'){
      const r=this.recordOptions;if(r.loop){const length=r.end-r.start,cycle=Math.floor(Math.max(0,raw-r.start)/length);while(this.recordCycle<cycle){const boundary=r.end+this.recordCycle*length;this.onRecordLoop(boundary,this.timeAt(boundary));this.recordCycle++;}}
    }
  }
  private scheduleNote(key:string,track:TrackId,pitch:number,velocity:number,beat:number,duration:number,lo:number,hi:number){if(beat<lo-1e-7||beat>=hi||this.scheduled.has(key)||!this.context||!this.project)return;const time=this.timeAt(beat),endTime=this.timeAt(beat+duration);this.scheduled.set(key,beat);if(time<this.now-.04)return;const output=this.gains.get(track);if(!output)return;const voice=pianoVoice(this.context,output,pitch,velocity,Math.max(this.now,time),Math.max(.025,endTime-time),this.project.settings.instrument);this.scheduledVoices.add(voice);setTimeout(()=>this.scheduledVoices.delete(voice),(Math.max(0,endTime-this.now)+.3)*1000);}
  private scheduleHeldNotes(beat:number){if(!this.project||!this.context)return;const loop=this.loopRegion();for(const track of this.project.tracks)for(const n of track.events){const start=noteStart(n);if(loop&&(start<loop.start||start>=loop.end))continue;const chunkEnd=this.repeated()?playbackChunks(this.project).find(c=>this.rawBeat()>=c.rawStart&&this.rawBeat()<c.rawEnd)?.songEnd:undefined;const end=Math.min(start+noteDuration(n),loop?.end??Infinity,chunkEnd??Infinity);if(start<beat&&end>beat){const duration=transportSeconds(this.project,beat,end)/this.speed;const output=this.gains.get(track.id);if(!output)continue;const voice=pianoVoice(this.context,output,n.midiPitch,n.velocity,this.originTime,duration,this.project.settings.instrument);this.scheduledVoices.add(voice);setTimeout(()=>this.scheduledVoices.delete(voice),(Math.max(0,this.originTime-this.now)+duration+.3)*1000);}}}
  noteOn(key:string,pitch:number,velocity:number,track:TrackId){if(!this.context||this.live.has(key))return;const gain=this.gains.get(track);if(!gain)return;const voice=pianoVoice(this.context,gain,pitch,velocity,this.now,undefined,this.project?.settings.instrument);this.live.set(key,{pitch,voice});this.emit();}
  noteOff(key:string){this.live.get(key)?.voice.release();this.live.delete(key);this.emit();}
  allNotesOff(){this.live.forEach(v=>v.voice.stop());this.live.clear();}
  private emit(){const beat=this.position(),p=this.project;const active=p?.tracks.map(t=>{const audible=audibleTracks(p.tracks).some(x=>x.id===t.id);return audible&&this.mode!=='idle'&&this.mode!=='paused'&&this.mode!=='countin'&&t.events.some(n=>noteStart(n)<=beat&&noteStart(n)+noteDuration(n)>beat)?t.volume:0;})??[];const pulse=p?measureForBeat(p,beat).pulse:1;this.listeners.forEach(fn=>fn({mode:this.mode,beat,rawBeat:this.rawBeat(),countRemaining:this.mode==='countin'?Math.max(1,Math.ceil((this.playbackStart-this.rawBeat())/pulse)):0,meter:active,activePitches:[...this.live.values()].map(v=>v.pitch)}));}
  get latencyMs(){return this.context?Math.round(((this.context.baseLatency||0)+(this.context.outputLatency||0))*1000):null;}
  dispose(){this.stop();void this.context?.close();this.listeners.clear();}
}
export const audio=new AudioEngine();
