import { audibleTracks, noteDuration, noteStart, projectEnd, signatureInfo, type Project, type TrackId } from '../music/model.ts';
import { clickVoice, pianoVoice, type Voice } from './synth.ts';
export type TransportMode='idle'|'playing'|'paused'|'countin'|'recording';
export interface TransportState {mode:TransportMode;beat:number;rawBeat:number;countRemaining:number;meter:number[];activePitches:number[]}
export class AudioEngine {
  context:AudioContext|null=null;private master:GainNode|null=null;private clickOutput:GainNode|null=null;private gains=new Map<TrackId,GainNode>();
  private project:Project|null=null;private mode:TransportMode='idle';private originTime=0;private originBeat=0;private cursor=0;private startBeat=0;private pausedBeat=0;
  private timer:ReturnType<typeof setInterval>|undefined;private frame=0;private lastEmit=0;private nextClick=0;private scheduled=new Set<string>();private scheduledVoices=new Set<Voice>();private clicks=new Set<OscillatorNode>();private live=new Map<string,{pitch:number;voice:Voice}>();private listeners=new Set<(state:TransportState)=>void>();
  metronome=false;metronomeVolume=.6;loop=false;latency:'auto'|'low'|'stable'='auto';
  onRecordingStart:()=>void=()=>{};onStop:()=>void=()=>{};onEnded:()=>void=()=>{};
  subscribe(fn:(s:TransportState)=>void){this.listeners.add(fn);return ()=>this.listeners.delete(fn);}
  async init(){if(!this.context){this.context=new AudioContext({latencyHint:this.latency==='stable'?'playback':'interactive'});this.master=this.context.createGain();this.master.gain.value=.72;const limiter=this.context.createDynamicsCompressor();limiter.threshold.value=-10;limiter.knee.value=10;limiter.ratio.value=6;this.master.connect(limiter).connect(this.context.destination);this.clickOutput=this.context.createGain();this.clickOutput.connect(this.master);for(const id of ['soprano','alto','tenor','bass'] as TrackId[]){const gain=this.context.createGain();gain.connect(this.master);this.gains.set(id,gain);}if(this.project)this.applyMixer(this.project);}if(this.context.state!=='running')await this.context.resume();return this.context;}
  setProject(project:Project){const old=this.project;const running=this.mode==='playing';const beat=this.rawBeat();this.project=project;this.applyMixer(project);if(running&&old&&(old.tempo!==project.tempo||old.timeSignature!==project.timeSignature)){this.cancelScheduled();this.originTime=this.context!.currentTime+.02;this.originBeat=beat;this.cursor=beat;this.nextClick=Math.ceil(beat/signatureInfo(project.timeSignature).pulse)*signatureInfo(project.timeSignature).pulse;this.scheduled.clear();this.scheduleHeldNotes(this.position());}}
  private applyMixer(p:Project){if(!this.context)return;const audible=new Set(audibleTracks(p.tracks).map(t=>t.id));p.tracks.forEach(t=>this.gains.get(t.id)?.gain.setTargetAtTime(audible.has(t.id)?t.volume:0,this.context!.currentTime,.015));}
  get now(){return this.context?.currentTime??0;}
  get status(){return this.mode;}
  get recordingOriginTime(){return this.originTime+(this.startBeat-this.originBeat)*60/(this.project?.tempo??72);}
  rawBeat(){if(['idle','paused'].includes(this.mode))return this.pausedBeat;if(!this.context||!this.project)return 0;return Math.max(this.originBeat,this.originBeat+(this.context.currentTime-this.originTime)*this.project.tempo/60);}
  position(){const beat=this.rawBeat();const p=this.project;if(p&&this.loop&&this.mode==='playing'&&beat>=p.settings.loopEnd){const len=p.settings.loopEnd-p.settings.loopStart;return len>0?p.settings.loopStart+((beat-p.settings.loopStart)%len):beat;}return Math.max(0,beat);}
  async play(from?:number){await this.init();if(!this.project)return;this.stopInternal();const start=from??(this.mode==='paused'?this.pausedBeat:this.pausedBeat);this.originBeat=this.loop?Math.max(this.project.settings.loopStart,Math.min(start,this.project.settings.loopEnd-.001)):start;this.pausedBeat=this.originBeat;this.originTime=this.now+.04;this.startBeat=this.originBeat;this.cursor=this.originBeat;this.mode='playing';this.startScheduler();this.scheduleHeldNotes(this.originBeat);}
  async record(from:number,countIn:number){await this.init();if(!this.project)return;this.stopInternal();const bars=signatureInfo(this.project.timeSignature).barBeats;this.originBeat=from-countIn*bars;this.startBeat=from;this.originTime=this.now+(countIn?.06:0);this.cursor=this.originBeat;this.mode=countIn?'countin':'recording';this.startScheduler();if(!countIn)this.onRecordingStart();}
  pause(){if(this.mode!=='playing')return;this.pausedBeat=this.position();this.mode='paused';this.stopInternal();this.emit();}
  stop(){this.onStop();this.mode='idle';this.pausedBeat=0;this.stopInternal();this.emit();}
  seek(beat:number){if(this.mode==='playing'){void this.play(beat);return;}if(this.mode==='idle'||this.mode==='paused'){this.pausedBeat=Math.max(0,beat);this.emit();}}
  private startScheduler(){this.scheduled.clear();const pulse=signatureInfo(this.project!.timeSignature).pulse;this.nextClick=Math.ceil(this.cursor/pulse)*pulse;this.tick();this.timer=setInterval(()=>this.tick(),25);const render=(time:number)=>{if(time-this.lastEmit>32){this.lastEmit=time;this.emit();}if(this.mode!=='idle'&&this.mode!=='paused')this.frame=requestAnimationFrame(render);};this.frame=requestAnimationFrame(render);}
  private stopInternal(){if(this.timer)clearInterval(this.timer);this.timer=undefined;cancelAnimationFrame(this.frame);this.cancelScheduled();this.allNotesOff();}
  private cancelScheduled(){for(const voice of this.scheduledVoices)voice.stop();this.scheduledVoices.clear();for(const click of this.clicks){try{click.stop();}catch{}}this.clicks.clear();this.scheduled.clear();}
  private tick(){if(!this.context||!this.project)return;const p=this.project;const now=this.now;const raw=this.rawBeat();if(this.mode==='countin'&&raw>=this.startBeat){this.mode='recording';this.onRecordingStart();}
    const end=this.originBeat+(now+.12-this.originTime)*p.tempo/60;
    const lo=Math.max(this.cursor,this.originBeat);const hi=Math.max(lo,end);const info=signatureInfo(p.timeSignature);
    if(this.metronome||this.mode==='countin'||this.mode==='recording'){
      while(this.nextClick<hi){const beat=this.nextClick;const at=this.originTime+(beat-this.originBeat)*60/p.tempo;const index=((Math.round(beat/info.pulse)%info.numerator)+info.numerator)%info.numerator;const accent=index===0?2:info.compound&&index===3?1:0;if(at>=now-.02){const click=clickVoice(this.context,this.clickOutput!,Math.max(at,now),accent,this.metronomeVolume);this.clicks.add(click);const cleanup=click.onended;click.onended=e=>{cleanup?.call(click,e);this.clicks.delete(click);};}this.nextClick+=info.pulse;}
    }else this.nextClick=Math.ceil(hi/info.pulse)*info.pulse;
    const loop=this.loop&&this.mode==='playing';const len=p.settings.loopEnd-p.settings.loopStart;
    for(const track of p.tracks){for(const n of track.events){const start=noteStart(n);if(loop&&len>0){if(start<p.settings.loopStart||start>=p.settings.loopEnd)continue;const first=Math.max(0,Math.floor((lo-p.settings.loopStart)/len));const last=Math.floor((hi-p.settings.loopStart)/len);for(let cycle=first;cycle<=last;cycle++)this.scheduleNote(n.id+':'+cycle,track.id,n.midiPitch,n.velocity,start+cycle*len,Math.min(noteDuration(n),p.settings.loopEnd-start),lo,hi);}else if(start>=this.startBeat)this.scheduleNote(n.id,track.id,n.midiPitch,n.velocity,start,noteDuration(n),lo,hi);}}
    this.cursor=hi;
    if(this.mode==='playing'&&!loop&&raw>=projectEnd(p)+.12){this.stop();this.onEnded();}
  }
  private scheduleNote(key:string,track:TrackId,pitch:number,velocity:number,beat:number,duration:number,lo:number,hi:number){if(beat<lo-1e-7||beat>=hi||this.scheduled.has(key)||!this.context||!this.project)return;const time=this.originTime+(beat-this.originBeat)*60/this.project.tempo;this.scheduled.add(key);if(time<this.now-.04)return;const voice=pianoVoice(this.context,this.gains.get(track)!,pitch,velocity,Math.max(this.now,time),duration*60/this.project.tempo);this.scheduledVoices.add(voice);setTimeout(()=>this.scheduledVoices.delete(voice),(Math.max(0,time-this.now)+duration*60/this.project.tempo+.3)*1000);}
  private scheduleHeldNotes(beat:number){if(!this.project||!this.context)return;const p=this.project;for(const track of p.tracks)for(const n of track.events){const start=noteStart(n);if(this.loop&&(start<p.settings.loopStart||start>=p.settings.loopEnd))continue;const end=this.loop?Math.min(start+noteDuration(n),p.settings.loopEnd):start+noteDuration(n);if(start<beat&&end>beat){const duration=(end-beat)*60/p.tempo;const voice=pianoVoice(this.context,this.gains.get(track.id)!,n.midiPitch,n.velocity,this.originTime,duration);this.scheduledVoices.add(voice);setTimeout(()=>this.scheduledVoices.delete(voice),(Math.max(0,this.originTime-this.now)+duration+.3)*1000);}}}
  noteOn(key:string,pitch:number,velocity:number,track:TrackId){if(!this.context||this.live.has(key))return;const voice=pianoVoice(this.context,this.gains.get(track)!,pitch,velocity,this.now);this.live.set(key,{pitch,voice});this.emit();}
  noteOff(key:string){const item=this.live.get(key);item?.voice.release();this.live.delete(key);this.emit();}
  allNotesOff(){this.live.forEach(v=>v.voice.release());this.live.clear();}
  private emit(){const beat=this.position();const p=this.project;const active=p?.tracks.map(t=>{const audible=audibleTracks(p.tracks).some(x=>x.id===t.id);return audible&&this.mode!=='idle'&&this.mode!=='paused'&&this.mode!=='countin'&&t.events.some(n=>noteStart(n)<=beat&&noteStart(n)+noteDuration(n)>beat)?t.volume:0;})??[0,0,0,0];const pulse=p?signatureInfo(p.timeSignature).pulse:1;this.listeners.forEach(fn=>fn({mode:this.mode,beat,rawBeat:this.rawBeat(),countRemaining:this.mode==='countin'?Math.max(1,Math.ceil((this.startBeat-this.rawBeat())/pulse)):0,meter:active,activePitches:[...this.live.values()].map(v=>v.pitch)}));}
  get latencyMs(){return this.context?Math.round(((this.context.baseLatency||0)+(this.context.outputLatency||0))*1000):null;}
  dispose(){this.stop();void this.context?.close();this.listeners.clear();}
}
export const audio=new AudioEngine();
