import {noteStart,noteDuration,type Project} from '../music/model.ts';
import {measureAt,measureCount,measureForBeat} from '../music/timeline.ts';
import {navigationProblems} from '../music/navigation.ts';
import {compatibleLyricAlignment} from '../lyrics/shared.ts';
import {validateRepeats} from '../music/repeats.ts';
import {engraveProject,type ScoreDocument} from './engraving.ts';
import {textWidth} from './font-metrics.ts';
import {decorationWidth} from './decorations.ts';
export interface ScoreIssue {id:string;severity:'error'|'warning'|'info';measure:number;trackId?:string;message:string;recommendation:string;objectId?:string}
export function checkScore(p:Project,document?:ScoreDocument):ScoreIssue[]{
 const issues:ScoreIssue[]=[],add=(severity:ScoreIssue['severity'],measure:number,message:string,recommendation:string,trackId?:string,objectId?:string)=>issues.push({id:[severity,measure,trackId,objectId,message].join(':'),severity,measure,message,recommendation,trackId,objectId});
 for(const problem of navigationProblems(p))add('error',problem.measure,problem.message,'Ajoutez ou sélectionnez une destination valide dans les symboles.',undefined,problem.id);
 try{validateRepeats(p.repeats);}catch(e){add('error',1,String(e instanceof Error?e.message:e),'Corrigez les bornes des reprises et des fins.');}
 const count=measureCount(p),notes=new Map(p.tracks.flatMap(t=>t.events.map(n=>[n.id,n] as const)));
 for(const t of p.tracks){const ordered=[...t.events].sort((a,b)=>noteStart(a)-noteStart(b));for(const [i,n] of ordered.entries()){const m=measureForBeat(p,noteStart(n));if(noteStart(n)+noteDuration(n)>m.end+1e-5&&!p.links?.some(l=>l.kind==='tie'&&l.noteIds.includes(n.id)))add('info',m.number,'Note prolongée au-delà de la barre.','Vérifiez la continuation ; ajoutez une liaison de durée si nécessaire.',t.id,n.id);if(noteDuration(n)<1/32)add('warning',m.number,'Durée inférieure à un trente-deuxième de temps.','Vérifiez la quantification ou la durée de la note.',t.id,n.id);if(i&&noteStart(ordered[i-1])+noteDuration(ordered[i-1])>noteStart(n)+1e-5&&Math.abs(noteStart(ordered[i-1])-noteStart(n))>1e-5)add('warning',m.number,'Chevauchement de notes dans cette voix.','Vérifiez les débuts et fins dans l’inspecteur.',t.id,n.id);}
 for(let number=1;number<=count;number++){const m=measureAt(p,number),region=ordered.filter(n=>noteStart(n)<m.end&&noteStart(n)+noteDuration(n)>m.start);if(!region.length)continue;let covered=0,end=m.start;for(const n of region){const start=Math.max(m.start,noteStart(n)),off=Math.min(m.end,noteStart(n)+noteDuration(n));covered+=Math.max(0,off-Math.max(start,end));end=Math.max(end,off);}if(covered<m.barBeats-1e-4)add('info',number,'Mesure avec silences implicites.','Affichez les silences pour vérifier les temps non chantés.',t.id);const total=region.reduce((s,n)=>s+Math.min(m.end,noteStart(n)+noteDuration(n))-Math.max(m.start,noteStart(n)),0);if(total>m.barBeats+1e-4)add('warning',number,'Durées superposées dépassant la mesure.','Vérifiez si l’accord ou le chevauchement est volontaire.',t.id);}}
 for(const l of p.lyrics)for(const s of l.syllables){const ids=s.noteIds??(s.noteId?[s.noteId]:[]);if(ids.some(key=>!notes.has(key)||notes.get(key)!.trackId!==l.trackId))add('error',1,'Lien de paroles vers une note absente ou une autre voix.','Reliez cette syllabe aux notes de sa voix.',l.trackId,l.id);else if(!ids.length&&s.text)add('warning',1,'Syllabe sans note : '+s.text,'Alignez les paroles ou liez cette syllabe à une note.',l.trackId,l.id);}
 for(const s of p.sharedLyrics??[]){const lines=p.lyrics.filter(l=>l.sharedTextId===s.id);if(!compatibleLyricAlignment(p,lines))add('info',1,'Paroles communes avec rythmes différents : '+s.name,'Les liens propres à chaque voix restent affichés sur des lignes distinctes.',undefined,s.id);}
 for(const link of p.links??[]){const linked=link.noteIds.map(key=>notes.get(key));if(linked.some(n=>!n||n.trackId!==link.trackId))add('error',1,'Liaison vers une note absente.','Recréez la liaison sur une sélection valide.',link.trackId,link.id);else if(link.kind==='tie'){const sorted=linked.filter(n=>!!n).sort((a,b)=>noteStart(a)-noteStart(b));if(sorted.some((n,i)=>n.midiPitch!==sorted[0].midiPitch||i&&Math.abs(noteStart(n)-noteStart(sorted[i-1])-noteDuration(sorted[i-1]))>1e-4))add('error',measureForBeat(p,noteStart(sorted[0])).number,'Liaison de durée non contiguë ou de hauteurs différentes.','Corrigez les notes ou remplacez-la par une liaison de phrasé.',link.trackId,link.id);}}
 for(const i of p.indications){const m=measureAt(p,i.measure);if((i.beat??0)>=m.barBeats)add('error',i.measure,'Symbole placé après la fin de la mesure.','Réduisez sa position dans la mesure.',i.trackId,i.id);if(i.kind==='tempo'||i.kind==='fermata'||i.kind==='dynamic'||i.kind==='crescendo'||i.kind==='diminuendo')add('info',i.measure,'Indication imprimée sans interprétation audio : '+(i.text||i.kind),'Utilisez les changements de tempo ou le mixeur pour modifier la lecture.',i.trackId,i.id);}
 let doc=document;try{doc??=engraveProject(p);}catch(e){add('error',1,e instanceof Error?e.message:'Gravure impossible.','Réduisez les tailles, les marges ou le nombre de mesures par ligne.');return issues;}
 const margin=p.layout.margin*96/25.4;
 for(const system of doc.systems){const requested=p.layout.systemCounts?.[system.first]??p.layout.measuresPerSystem;if(requested>0&&system.last<doc.measureCount&&system.last-system.first+1<requested&&!p.layout.systemBreaks.includes(system.last)&&!p.layout.pageBreaks?.includes(system.last))add('warning',system.first,'Ligne trop dense pour '+requested+' mesures : répartition sur le système suivant.','Réduisez le nombre de mesures, les tailles, ou choisissez le paysage.');}
 for(const page of doc.pages){for(const op of page.ops){const width=op.kind==='text'?(op.font?decorationWidth(op.text,op.size,op.font):textWidth(op.text,op.size)):op.kind==='image'?op.width:0;if(op.x<margin-1||op.x+width>page.width-margin+1||op.y<margin-1||op.y>page.height-margin+1)add('warning',op.measure??1,'Objet proche ou au-delà des marges de la page '+(page.index+1)+'.','Vérifiez l’aperçu et ajustez la taille ou l’espacement.',op.trackId,op.objectId);}
 const rows=page.ops.filter(op=>op.kind==='text'&&(op.role==='note'||op.role==='lyric'||op.role==='header'||op.role==='footer'));
 for(let i=0;i<rows.length;i++){const a=rows[i];if(a.kind!=='text')continue;for(let j=i+1;j<rows.length;j++){const b=rows[j];if(b.kind!=='text'||Math.abs(a.y-b.y)>2||a.role!==b.role)continue;const left=Math.max(a.x,b.x),right=Math.min(a.x+(a.font?decorationWidth(a.text,a.size,a.font):textWidth(a.text,a.size)),b.x+(b.font?decorationWidth(b.text,b.size,b.font):textWidth(b.text,b.size)));if(right-left>1)add('warning',a.measure??b.measure??1,'Collision de '+(a.role==='lyric'?'paroles':a.role==='header'||a.role==='footer'?'champs de page':'notes')+'.','Augmentez la largeur de mesure ou choisissez moins de mesures par ligne.',a.trackId,a.objectId);}}
 }
 return [...new Map(issues.map(i=>[i.id,i])).values()];
}
