import type { ScoreDocument } from './engraving.ts';
import type { Project } from '../music/model.ts';
export async function pdfBytes(doc:ScoreDocument,fontBase64:string,project:Project):Promise<ArrayBuffer>{
  const {jsPDF}=await import('jspdf');const first=doc.pages[0];const pdf=new jsPDF({unit:'mm',format:[first.widthMm,first.heightMm],orientation:first.widthMm>first.heightMm?'landscape':'portrait',compress:true,putOnlyUsedFonts:true,floatPrecision:4});
  pdf.addFileToVFS('Soratro.ttf',fontBase64);pdf.addFont('Soratro.ttf','Soratro','normal');pdf.setFont('Soratro');pdf.setProperties({title:project.title,author:project.author,creator:'SORATRO',subject:'Partition Solfa · '+project.tonic});const mm=25.4/96;
  for(const page of doc.pages){if(page.index)pdf.addPage([page.widthMm,page.heightMm],page.widthMm>page.heightMm?'landscape':'portrait');for(const op of page.ops){if(op.kind==='text'){pdf.setFontSize(op.size*.75);pdf.setTextColor(op.color??'#26232d');pdf.text(op.text,op.x*mm,op.y*mm,{baseline:'alphabetic'});}else if(op.kind==='line'){pdf.setDrawColor(op.color??'#37333e');pdf.setLineWidth(op.width*mm);pdf.line(op.x*mm,op.y*mm,op.x2*mm,op.y2*mm);}else{pdf.setFillColor(op.color??'#37333e');pdf.circle(op.x*mm,op.y*mm,op.radius*mm,'F');}}}
  return pdf.output('arraybuffer');
}
let fontPromise:Promise<string>|null=null;
export function scoreFontBase64(){return fontPromise??=fetch(new URL('../assets/ScoreFont.ttf',import.meta.url)).then(async response=>{if(!response.ok)throw new Error('La police d’impression locale est indisponible.');const bytes=new Uint8Array(await response.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);});}
export async function svgPNG(svg:string,scale=3):Promise<Blob>{const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('Impossible de dessiner la page SVG.'));});const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const context=canvas.getContext('2d');if(!context)throw new Error('Export PNG indisponible.');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Export PNG impossible.')),'image/png'));}finally{URL.revokeObjectURL(url);}}
export async function printPages(doc:ScoreDocument,font:string){const {pageSVG}=await import('./engraving.ts');const frame=document.createElement('iframe');frame.className='print-frame';frame.setAttribute('aria-hidden','true');const p=doc.pages[0];const ready=new Promise<void>(resolve=>{frame.onload=()=>resolve();});frame.srcdoc='<!doctype html><html><head><meta charset="utf-8"><title>SORATRO</title><style>@page{size:'+p.widthMm+'mm '+p.heightMm+'mm;margin:0}html,body{margin:0;background:#fff}.page{width:'+p.widthMm+'mm;height:'+p.heightMm+'mm;break-after:page}.page:last-child{break-after:auto}svg{width:100%;height:100%;display:block}</style></head><body>'+doc.pages.map(p=>'<div class="page">'+pageSVG(p,font)+'</div>').join('')+'</body></html>';document.body.append(frame);await ready;await frame.contentDocument?.fonts.ready;const target=frame.contentWindow;if(!target){frame.remove();throw new Error('Impression indisponible.');}target.addEventListener('afterprint',()=>frame.remove(),{once:true});target.focus();target.print();setTimeout(()=>frame.remove(),120000);}
