import {pageSVG,type ScoreDocument} from './engraving.ts';
import type { Project } from '../music/model.ts';
import {PRINT_FONT_URLS} from './decorations.ts';
import {textWidth} from './font-metrics.ts';
import type {ScoreFonts} from './engraving.ts';
const fontCache=new Map<string,Promise<string>>();
async function loadFont(url:URL):Promise<string>{const key=url.href;if(!fontCache.has(key))fontCache.set(key,(async()=>{let bytes:Uint8Array;if(typeof window==='undefined'){const moduleName='node:fs/promises';const fs=await import(/* @vite-ignore */ moduleName);bytes=await fs.readFile(url);}else{const response=await fetch(url);if(!response.ok)throw new Error('La police d’impression locale est indisponible.');bytes=new Uint8Array(await response.arrayBuffer());}let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);})().catch(e=>{fontCache.delete(key);throw e;}));return fontCache.get(key)!;}
export function scoreFontBase64(){return loadFont(new URL('../assets/ScoreFont.ttf',import.meta.url));}
export async function scoreFonts(doc:ScoreDocument,music?:string):Promise<ScoreFonts>{const keys=[...new Set(doc.pages.flatMap(p=>p.ops.flatMap(op=>op.kind==='text'&&op.font?[op.font]:[])))];const entries=await Promise.all(keys.map(async key=>[key,await loadFont(PRINT_FONT_URLS[key])] as const));return {music:music??await scoreFontBase64(),...Object.fromEntries(entries)};}
export async function pdfBytes(doc:ScoreDocument,font:string|ScoreFonts,project:Project):Promise<ArrayBuffer>{
  const fonts=typeof font==='string'?await scoreFonts(doc,font):font,{jsPDF}=await import('jspdf'),first=doc.pages[0];const pdf=new jsPDF({unit:'mm',format:[first.widthMm,first.heightMm],orientation:first.widthMm>first.heightMm?'landscape':'portrait',compress:true,putOnlyUsedFonts:true,floatPrecision:4});
  for(const [key,data] of Object.entries(fonts)){const name='Soratro'+key.replace(/[^a-z]/gi,'');pdf.addFileToVFS(name+'.ttf',data);pdf.addFont(name+'.ttf',name,'normal');}const musicFont='Soratro'+ 'music';pdf.setProperties({title:project.title,author:project.author,creator:'SORATRO',subject:'Partition Solfa · '+project.tonic});const mm=25.4/96;
  for(const [index,page] of doc.pages.entries()){if(index)pdf.addPage([page.widthMm,page.heightMm],page.widthMm>page.heightMm?'landscape':'portrait');for(const op of page.ops){
    if(op.kind==='text'){pdf.setFont(op.font?'Soratro'+op.font.replace(/[^a-z]/gi,''):musicFont);pdf.setFontSize(op.size*.75);pdf.setTextColor(op.color??'#26232d');pdf.text(op.baseText??op.text,op.x*mm,op.y*mm,{baseline:'alphabetic'});if(op.octave){pdf.setFontSize(op.size*.7*.75);pdf.text((op.octave>0?"'":',').repeat(Math.abs(op.octave)),(op.x+textWidth(op.baseText??'',op.size))*mm,(op.y+(op.octave>0?-op.size*.38:op.size*.18))*mm,{baseline:'alphabetic'});}}
    else if(op.kind==='line'){pdf.setDrawColor(op.color??'#37333e');pdf.setLineWidth(op.width*mm);pdf.line(op.x*mm,op.y*mm,op.x2*mm,op.y2*mm);}
    else if(op.kind==='curve'){pdf.setDrawColor(op.color??'#37333e');pdf.setLineWidth(op.width*mm);pdf.path([{op:'m',c:[op.x*mm,op.y*mm]},{op:'c',c:[op.cx1*mm,op.cy1*mm,op.cx2*mm,op.cy2*mm,op.x2*mm,op.y2*mm]}]);pdf.stroke();}
    else if(op.kind==='image'){const properties=pdf.getImageProperties(op.src),ratio=properties.width/properties.height,h=Math.min(op.height,op.width/ratio),w=h*ratio;pdf.addImage(op.src,op.src.startsWith('data:image/png')?'PNG':'JPEG',(op.x+(op.width-w)/2)*mm,(op.y+(op.height-h)/2)*mm,w*mm,h*mm);}
    else{pdf.setFillColor(op.color??'#37333e');pdf.setDrawColor(op.color??'#37333e');pdf.setLineWidth(mm);pdf.circle(op.x*mm,op.y*mm,op.radius*mm,op.outline?'S':'F');}
  }}return pdf.output('arraybuffer');
}
export async function svgPNG(svg:string,scale=3):Promise<Blob>{const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('Impossible de dessiner la page SVG.'));});const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const context=canvas.getContext('2d');if(!context)throw new Error('Export PNG indisponible.');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Export PNG impossible.')),'image/png'));}finally{URL.revokeObjectURL(url);}}
export async function printPages(doc:ScoreDocument,font:string|ScoreFonts){const frame=document.createElement('iframe');frame.className='print-frame';frame.setAttribute('aria-hidden','true');const p=doc.pages[0];const ready=new Promise<void>(resolve=>{frame.onload=()=>resolve();});frame.srcdoc='<!doctype html><html><head><meta charset="utf-8"><title>SORATRO</title><style>@page{size:'+p.widthMm+'mm '+p.heightMm+'mm;margin:0}html,body{margin:0;background:#fff}.page{width:'+p.widthMm+'mm;height:'+p.heightMm+'mm;break-after:page}.page:last-child{break-after:auto}svg{width:100%;height:100%;display:block}</style></head><body>'+doc.pages.map(p=>'<div class="page">'+pageSVG(p,font)+'</div>').join('')+'</body></html>';document.body.append(frame);await ready;await frame.contentDocument?.fonts.ready;const target=frame.contentWindow;if(!target){frame.remove();throw new Error('Impression indisponible.');}target.addEventListener('afterprint',()=>frame.remove(),{once:true});target.focus();target.print();setTimeout(()=>frame.remove(),120000);}
