import type {Project} from '../music/model.ts';
import {CREDIT_ROLES} from './credits.ts';
export function validatePresentation(p:Project){
 const fail=(s:string):never=>{throw new Error(s+' invalide.');},num=(n:number,min:number,max:number,label:string,integer=false)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max||integer&&!Number.isInteger(n))fail(label);},str=(s:string,max:number,label:string)=>{if(typeof s!=='string'||s.length>max)fail(label);};
 if(!Number.isInteger(p.layout.measuresPerSystem))fail('Nombre de mesures par ligne');
 const modes=['full','natural','center','auto'];if(p.layout.systemAlignment!==undefined&&!modes.includes(p.layout.systemAlignment))fail('Justification du système');
 if(p.layout.systemAlignments!==undefined){if(!p.layout.systemAlignments||Array.isArray(p.layout.systemAlignments)||typeof p.layout.systemAlignments!=='object')fail('Justifications locales');for(const [bar,mode] of Object.entries(p.layout.systemAlignments)){if(!/^[1-9]\d*$/.test(bar)||!modes.includes(mode))fail('Justification locale');}}
 const n=p.layout.numbering;if(n!==undefined){if(!n||typeof n!=='object'||!['measure','system','page','none'].includes(n.mode)||!['above','below','left'].includes(n.position))fail('Numérotation');num(n.size,6,24,'Taille des numéros');num(n.gap,0,40,'Espace des numéros');num(n.start,0,100000,'Premier numéro',true);str(n.prefix,40,'Préfixe de morceau');if(!/^#[0-9a-f]{6}$/i.test(n.color)||typeof n.pickupZero!=='boolean')fail('Présentation des numéros');}
 const limits=p.settings.tapLimits;if(limits!==undefined){if(!limits||typeof limits!=='object')fail('Plage Tap');num(limits.minBpm,20,299,'Minimum Tap');num(limits.maxBpm,21,300,'Maximum Tap');if(limits.maxBpm<=limits.minBpm)fail('Plage Tap');}if(p.settings.metronomePulse!==undefined&&!['subdivision','tempo'].includes(p.settings.metronomePulse))fail('Pulsation du métronome');
 const c=p.credits;if(c!==undefined){if(!c||typeof c!=='object'||!['fr','mg','custom'].includes(c.language)||!['fr','mg','short','custom'].includes(c.preset)||typeof c.grouped!=='boolean'||!c.labels||typeof c.labels!=='object'||Array.isArray(c.labels)||!Array.isArray(c.contributors)||c.contributors.length>100)fail('Crédits');for(const [role,label] of Object.entries(c.labels)){if(!CREDIT_ROLES.includes(role as never))fail('Rôle de crédit');str(label,100,'Libellé');}const ids=new Set<string>();for(const person of c.contributors){if(!person||typeof person!=='object')fail('Contributeur');str(person.id,200,'Identifiant');str(person.name,200,'Nom');str(person.label,100,'Libellé');if(!person.id||ids.has(person.id)||!CREDIT_ROLES.includes(person.role)||typeof person.visible!=='boolean')fail('Contributeur');ids.add(person.id);num(person.order,0,100,'Ordre',true);}}
}
