import { validateRepeats } from '../music/repeats.ts';
import { createProject, SCHEMA_VERSION, TONICS, type Project } from '../music/model.ts';
export class ProjectFormatError extends Error {}
function object(value:unknown,label:string):Record<string,unknown> {if(!value||typeof value!=='object'||Array.isArray(value))throw new ProjectFormatError(label+' invalide.');return value as Record<string,unknown>;}
function finite(value:unknown,min:number,max:number,label:string) {if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)throw new ProjectFormatError(label+' invalide.');}
function text(value:unknown,label:string,max=100000) {if(typeof value!=='string'||value.length>max)throw new ProjectFormatError(label+' invalide.');}
function array(value:unknown,label:string,max=100000):unknown[] {if(!Array.isArray(value)||value.length>max)throw new ProjectFormatError(label+' invalide.');return value;}
export function validSignature(value:unknown) {if(typeof value!=='string'||!/^\d{1,2}\/(1|2|4|8|16|32)$/.test(value))return false;const n=Number(value.split('/')[0]);return n>=1&&n<=32;}
/** Add defaults without changing legacy notes, tempo semantics or diagnostic timestamps. */
export function migrateProject(input:unknown):Project {
  const source=object(input,'Projet');const version=source.schemaVersion;
  if(typeof version!=='number'||!Number.isInteger(version)||version<1)throw new ProjectFormatError('Version de schéma absente ou invalide.');
  if(version>SCHEMA_VERSION)throw new ProjectFormatError('Projet créé avec une version plus récente. Mettez SORATRO à jour.');
  const migrated=structuredClone(source) as unknown as Project;
  if(version===1){const defaults=createProject();Object.assign(migrated,{schemaVersion:2,markers:[],takes:[],tempoMap:[],signatureMap:[],repeats:[],indications:[],layout:defaults.layout});migrated.settings={...defaults.settings,...object(source.settings,'Préférences musicales')};migrated.settings.tempoUnit='quarter';}
  validateProject(migrated);return migrated;
}
export function validateProject(value:Project):void {
  const p=object(value,'Projet');text(p.id,'Identifiant',200);if(!value.id)throw new ProjectFormatError('Identifiant du projet vide.');
  for(const key of ['title','author','composer','createdAt','updatedAt'] as const)text(p[key],key,2000);
  if(!Number.isFinite(Date.parse(value.createdAt))||!Number.isFinite(Date.parse(value.updatedAt)))throw new ProjectFormatError('Dates du projet invalides.');
  if(!TONICS.includes(value.tonic)||!validSignature(value.timeSignature))throw new ProjectFormatError('Tonalité ou signature incompatible.');finite(value.tempo,10,600,'Tempo');
  const tracks=array(value.tracks,'Voix',64);if(!tracks.length)throw new ProjectFormatError('Le projet doit contenir au moins une voix.');const trackIds=new Set<string>(),noteIds=new Set<string>();
  function notes(events:unknown,trackId:string,ids:Set<string>) {for(const raw of array(events,'Notes',200000)){const n=object(raw,'Note');text(n.id,'Identifiant de note',200);if(!n.id||ids.has(String(n.id)))throw new ProjectFormatError('Identifiants de notes en double.');ids.add(String(n.id));if(n.trackId!==trackId)throw new ProjectFormatError('Une note appartient à une voix inexistante.');finite(n.midiPitch,0,127,'Hauteur MIDI');if(!Number.isInteger(n.midiPitch))throw new ProjectFormatError('Hauteur MIDI non entière.');finite(n.velocity,0,127,'Vélocité');finite(n.originalStart,0,1000000,'Début musical');finite(n.originalDuration,.00001,1000000,'Durée musicale');finite(n.startTime,-86400,10000000,'NOTE ON');finite(n.endTime,-86400,10000000,'NOTE OFF');finite(n.duration,0,10000000,'Durée brute');finite(n.recordedTempo,10,600,'Tempo enregistré');if(Number(n.endTime)<Number(n.startTime))throw new ProjectFormatError('NOTE OFF antérieur à NOTE ON.');if(n.editStart!==undefined)finite(n.editStart,0,1000000,'Début édité');if(n.editDuration!==undefined)finite(n.editDuration,.00001,1000000,'Durée éditée');if(n.quantizedStart!==undefined)finite(n.quantizedStart,0,1000000,'Début quantifié');if(n.quantizedDuration!==undefined)finite(n.quantizedDuration,.00001,1000000,'Durée quantifiée');if(n.rawStartBeat!==undefined)finite(n.rawStartBeat,-1000000,1000000,'Début brut');if(n.rawDurationBeats!==undefined)finite(n.rawDurationBeats,0,1000000,'Durée brute en beats');if(n.compensationMs!==undefined)finite(n.compensationMs,-500,500,'Compensation');}}
  for(const raw of tracks){const t=object(raw,'Voix');text(t.id,'Identifiant de voix',200);text(t.name,'Nom de voix',200);text(t.shortName,'Abréviation',30);text(t.color,'Couleur',30);if(!/^#[0-9a-f]{6}$/i.test(String(t.color)))throw new ProjectFormatError('Couleur de voix invalide.');if(!t.id||trackIds.has(String(t.id)))throw new ProjectFormatError('Identifiants de voix en double.');trackIds.add(String(t.id));finite(t.volume,0,1,'Volume');if(typeof t.mute!=='boolean'||typeof t.solo!=='boolean')throw new ProjectFormatError('Mixeur invalide.');if(t.pan!==undefined)finite(t.pan,-1,1,'Panoramique');if(t.locked!==undefined&&typeof t.locked!=='boolean')throw new ProjectFormatError('Verrouillage de voix invalide.');notes(t.events,String(t.id),noteIds);}
  for(const raw of array(value.lyrics,'Paroles',2000)){const l=object(raw,'Paroles');text(l.id,'Identifiant de paroles',200);text(l.text,'Texte');if(!trackIds.has(String(l.trackId)))throw new ProjectFormatError('Voix des paroles absente.');for(const syllable of array(l.syllables,'Syllabes',200000)){const s=object(syllable,'Syllabe');text(s.text,'Syllabe',2000);const links=s.noteIds??(s.noteId?[s.noteId]:[]);for(const noteId of array(links,'Liens de paroles',20000))if(typeof noteId!=='string'||!noteIds.has(noteId))throw new ProjectFormatError('Une syllabe référence une note absente.');}}
  const settings=object(value.settings,'Préférences');if(!['Solo','Unisson','SA','SAB','SATB','SSA','SSAA','TTB','TTBB','Personnalisé'].includes(value.settings.choirTemplate))throw new ProjectFormatError('Formation incompatible.');if(!trackIds.has(String(settings.rehearsalVoice)))throw new ProjectFormatError('Voix de répétition absente.');if(settings.measureCount!==undefined)finite(settings.measureCount,1,100000,'Nombre de mesures');for(const [key,min,max] of [['quantizationStrength',0,100],['loopStart',0,1000000],['loopEnd',0,1000000],['punchStart',0,1000000],['punchEnd',0,1000000],['latencyCompensationMs',-500,500],['pickupBeats',0,128],['masterVolume',0,1],['rehearsalSpeed',25,200],['loopRepeats',0,100]] as const)finite(settings[key],min,max,key);
  if(![0,1,2,4].includes(value.settings.countIn)||![0,1,2,4].includes(value.settings.preRoll))throw new ProjectFormatError('Décompte invalide.');if(!['quarter','dotted-quarter','eighth'].includes(value.settings.tempoUnit)||!['overdub','replace'].includes(value.settings.recordMode)||!['none','1/2','1/4','1/8','1/16','1/32','triplet-quarter','triplet-eighth','triplet-sixteenth','compound','auto'].includes(value.settings.quantization))throw new ProjectFormatError('Préférences musicales incompatibles.');for(const key of ['punchEnabled','loopRecording','snap'] as const)if(typeof settings[key]!=='boolean')throw new ProjectFormatError(key+' invalide.');if(value.settings.loopEnd<=value.settings.loopStart||value.settings.punchEnd<=value.settings.punchStart)throw new ProjectFormatError('Zone de boucle ou de Punch invalide.');if(!['piano','soft-piano','organ','vocal'].includes(value.settings.instrument)||!['ensemble','solo','dominant'].includes(value.settings.rehearsalMix))throw new ProjectFormatError('Préférences audio invalides.');array(settings.beatGroups,'Groupements',32).forEach(n=>finite(n,1,32,'Groupement'));
  for(const m of array(value.markers,'Marqueurs',10000)){const x=object(m,'Marqueur');text(x.id,'Identifiant',200);text(x.label,'Repère',200);finite(x.measure,1,100000,'Mesure');}
  for(const m of array(value.tempoMap,'Changements de tempo',10000)){const x=object(m,'Tempo');finite(x.measure,1,100000,'Mesure');finite(x.bpm,10,600,'Tempo');}
  for(const m of array(value.signatureMap,'Changements de mesure',10000)){const x=object(m,'Signature');finite(x.measure,1,100000,'Mesure');if(!validSignature(x.signature))throw new ProjectFormatError('Changement de signature invalide.');if(x.groups!==undefined)array(x.groups,'Groupements',32).forEach(n=>finite(n,1,32,'Groupement'));}
  for(const m of array(value.repeats,'Reprises',10000)){const x=object(m,'Reprise');text(x.id,'Identifiant',200);finite(x.startMeasure,1,100000,'Mesure');finite(x.endMeasure,Number(x.startMeasure),100000,'Mesure');finite(x.times,2,16,'Nombre de reprises');}
  for(const m of array(value.indications,'Indications',10000)){const x=object(m,'Indication');text(x.id,'Identifiant',200);text(x.text,'Texte',2000);finite(x.measure,1,100000,'Mesure');if(!['dynamic','text','fermata','breath','crescendo','diminuendo'].includes(String(x.kind)))throw new ProjectFormatError('Indication incompatible.');}
  for(const raw of array(value.takes,'Prises',500)){const t=object(raw,'Prise');text(t.id,'Identifiant',200);text(t.name,'Nom de prise',200);text(t.createdAt,'Date',100);if(!trackIds.has(String(t.trackId)))throw new ProjectFormatError('Voix de prise absente.');finite(t.startBeat,0,1000000,'Début de prise');finite(t.endBeat,Number(t.startBeat),1000000,'Fin de prise');if(t.mode!==undefined&&!['overdub','replace'].includes(String(t.mode)))throw new ProjectFormatError('Mode de prise invalide.');if(typeof t.selected!=='boolean')throw new ProjectFormatError('État de prise invalide.');notes(t.events,String(t.trackId),new Set());}
  for(const collection of [value.markers,value.tempoMap,value.signatureMap,value.indications])for(const item of collection)if(!Number.isInteger(item.measure))throw new ProjectFormatError('Numéro de mesure non entier.');
  for(const repeat of value.repeats)if(![repeat.startMeasure,repeat.endMeasure,repeat.times].every(Number.isInteger))throw new ProjectFormatError('Reprise non entière.');
  try{validateRepeats(value.repeats);}catch(e){throw new ProjectFormatError(e instanceof Error?e.message:'Reprises invalides.');}
  for(const raw of value.lyrics){if(raw.verse!==undefined&&(!Number.isInteger(raw.verse)||raw.verse<1||raw.verse>100))throw new ProjectFormatError('Numéro de couplet invalide.');if(raw.kind!==undefined&&!['verse','refrain','common'].includes(raw.kind))throw new ProjectFormatError('Type de paroles invalide.');for(const syllable of raw.syllables)for(const key of syllable.noteIds??(syllable.noteId?[syllable.noteId]:[]))if(!value.tracks.find(t=>t.id===raw.trackId)!.events.some(n=>n.id===key))throw new ProjectFormatError('Une syllabe référence une autre voix.');}
  const layout=object(value.layout,'Mise en page');if(!['A4','A5','Letter'].includes(value.layout.paper)||!['portrait','landscape'].includes(value.layout.orientation))throw new ProjectFormatError('Format de page invalide.');for(const [key,min,max] of [['margin',5,50],['measuresPerSystem',0,12],['noteSize',10,32],['lyricSize',8,24],['voiceGap',20,70],['systemGap',8,80],['titleSize',14,48]] as const)finite(layout[key],min,max,key);if(typeof layout.pageNumbers!=='boolean')throw new ProjectFormatError('Pagination invalide.');array(layout.systemBreaks,'Sauts de système',10000).forEach(n=>finite(n,1,100000,'Saut de système'));
}
