import {validateVocal} from '../vocal/types.ts';
import { validateRepeats } from '../music/repeats.ts';
import { NAVIGATION_LABELS } from '../music/navigation.ts';
import { createProject, SCHEMA_VERSION, TONICS, type Project } from '../music/model.ts';
import {validatePresentation} from '../score/presentation-validation.ts';
export class ProjectFormatError extends Error {}
function object(value:unknown,label:string):Record<string,unknown> {if(!value||typeof value!=='object'||Array.isArray(value))throw new ProjectFormatError(label+' invalide.');return value as Record<string,unknown>;}
function finite(value:unknown,min:number,max:number,label:string) {if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)throw new ProjectFormatError(label+' invalide.');}
function text(value:unknown,label:string,max=100000) {if(typeof value!=='string'||value.length>max)throw new ProjectFormatError(label+' invalide.');}
function array(value:unknown,label:string,max=100000):unknown[] {if(!Array.isArray(value)||value.length>max)throw new ProjectFormatError(label+' invalide.');return value;}
export function validSignature(value:unknown) {if(typeof value!=='string'||!/^\d{1,2}\/(1|2|4|8|16|32)$/.test(value))return false;const n=Number(value.split('/')[0]);return n>=1&&n<=32;}
/** Add defaults without changing legacy notes, tempo semantics or diagnostic timestamps. */
export function migrateProject(input:unknown):Project {
  const source=object(input,'Projet');const version=source.schemaVersion;
  if(typeof version!=='number'||!Number.isInteger(version)||version<1)throw new ProjectFormatError('Version de schéma absente ou invalide.');
  if(version>SCHEMA_VERSION)throw new ProjectFormatError('Projet créé avec une version plus récente. Mettez SORATRO à jour.');
  const migrated=structuredClone(source) as unknown as Project;
  if(version===1){const defaults=createProject();delete defaults.layout.numbering;delete defaults.layout.systemAlignment;Object.assign(migrated,{schemaVersion:2,markers:[],takes:[],tempoMap:[],signatureMap:[],repeats:[],indications:[],layout:defaults.layout});migrated.settings={...defaults.settings,...object(source.settings,'Préférences musicales')};migrated.settings.tempoUnit='quarter';}
  validateProject(migrated);return migrated;
}
export function validateProject(value:Project):void {
  try{validatePresentation(value);}catch(e){throw new ProjectFormatError(e instanceof Error?e.message:'Présentation invalide.');}
  const p=object(value,'Projet');text(p.id,'Identifiant',200);if(!value.id)throw new ProjectFormatError('Identifiant du projet vide.');
  for(const key of ['title','author','composer','createdAt','updatedAt'] as const)text(p[key],key,2000);
  if(!Number.isFinite(Date.parse(value.createdAt))||!Number.isFinite(Date.parse(value.updatedAt)))throw new ProjectFormatError('Dates du projet invalides.');
  if(!TONICS.includes(value.tonic)||!validSignature(value.timeSignature))throw new ProjectFormatError('Tonalité ou signature incompatible.');finite(value.tempo,10,600,'Tempo');
  const tracks=array(value.tracks,'Voix',64);if(!tracks.length)throw new ProjectFormatError('Le projet doit contenir au moins une voix.');const trackIds=new Set<string>(),noteIds=new Set<string>();
  function notes(events:unknown,trackId:string,ids:Set<string>) {for(const raw of array(events,'Notes',200000)){const n=object(raw,'Note');text(n.id,'Identifiant de note',200);if(!n.id||ids.has(String(n.id)))throw new ProjectFormatError('Identifiants de notes en double.');ids.add(String(n.id));if(n.trackId!==trackId)throw new ProjectFormatError('Une note appartient à une voix inexistante.');finite(n.midiPitch,0,127,'Hauteur MIDI');if(!Number.isInteger(n.midiPitch))throw new ProjectFormatError('Hauteur MIDI non entière.');finite(n.velocity,0,127,'Vélocité');finite(n.originalStart,0,1000000,'Début musical');finite(n.originalDuration,.00001,1000000,'Durée musicale');finite(n.startTime,-86400,10000000,'NOTE ON');finite(n.endTime,-86400,10000000,'NOTE OFF');finite(n.duration,0,10000000,'Durée brute');finite(n.recordedTempo,10,600,'Tempo enregistré');if(Number(n.endTime)<Number(n.startTime))throw new ProjectFormatError('NOTE OFF antérieur à NOTE ON.');if(n.editStart!==undefined)finite(n.editStart,0,1000000,'Début édité');if(n.editDuration!==undefined)finite(n.editDuration,.00001,1000000,'Durée éditée');if(n.quantizedStart!==undefined)finite(n.quantizedStart,0,1000000,'Début quantifié');if(n.quantizedDuration!==undefined)finite(n.quantizedDuration,.00001,1000000,'Durée quantifiée');if(n.rawStartBeat!==undefined)finite(n.rawStartBeat,-1000000,1000000,'Début brut');if(n.rawDurationBeats!==undefined)finite(n.rawDurationBeats,0,1000000,'Durée brute en beats');if(n.compensationMs!==undefined)finite(n.compensationMs,-500,500,'Compensation');if(n.vocal!==undefined){const v=object(n.vocal,'Diagnostic vocal');if(v.source!=='vocal'||typeof v.uncertain!=='boolean')throw new ProjectFormatError('Diagnostic vocal invalide.');finite(v.confidence,0,1,'Confiance vocale');finite(v.meanMidi,-.5,127.5,'Hauteur détectée');finite(v.spread,0,128,'Variation vocale');finite(v.audioStartTime,0,1e7,'Début audio');finite(v.audioEndTime,Number(v.audioStartTime),1e7,'Fin audio');if(v.suggestedPitch!==undefined){finite(v.suggestedPitch,0,127,'Suggestion de hauteur');if(!Number.isInteger(v.suggestedPitch))throw new ProjectFormatError('Suggestion de hauteur non entière.');}if(v.reviewed!==undefined&&typeof v.reviewed!=='boolean')throw new ProjectFormatError('État de correction vocale invalide.');}}}
  for(const raw of tracks){const t=object(raw,'Voix');text(t.id,'Identifiant de voix',200);text(t.name,'Nom de voix',200);text(t.shortName,'Abréviation',30);text(t.color,'Couleur',30);if(!/^#[0-9a-f]{6}$/i.test(String(t.color)))throw new ProjectFormatError('Couleur de voix invalide.');if(!t.id||trackIds.has(String(t.id)))throw new ProjectFormatError('Identifiants de voix en double.');trackIds.add(String(t.id));finite(t.volume,0,1,'Volume');if(typeof t.mute!=='boolean'||typeof t.solo!=='boolean')throw new ProjectFormatError('Mixeur invalide.');if(t.pan!==undefined)finite(t.pan,-1,1,'Panoramique');if(t.locked!==undefined&&typeof t.locked!=='boolean')throw new ProjectFormatError('Verrouillage de voix invalide.');notes(t.events,String(t.id),noteIds);}
  for(const raw of array(value.lyrics,'Paroles',2000)){const l=object(raw,'Paroles');text(l.id,'Identifiant de paroles',200);text(l.text,'Texte');if(!trackIds.has(String(l.trackId)))throw new ProjectFormatError('Voix des paroles absente.');for(const syllable of array(l.syllables,'Syllabes',200000)){const s=object(syllable,'Syllabe');text(s.text,'Syllabe',2000);const links=s.noteIds??(s.noteId?[s.noteId]:[]);for(const noteId of array(links,'Liens de paroles',20000))if(typeof noteId!=='string'||!noteIds.has(noteId))throw new ProjectFormatError('Une syllabe référence une note absente.');}}
  const settings=object(value.settings,'Préférences');if(!['Solo','Unisson','SA','SAB','SATB','SSA','SSAA','TTB','TTBB','Personnalisé'].includes(value.settings.choirTemplate))throw new ProjectFormatError('Formation incompatible.');if(!trackIds.has(String(settings.rehearsalVoice)))throw new ProjectFormatError('Voix de répétition absente.');if(settings.measureCount!==undefined)finite(settings.measureCount,1,100000,'Nombre de mesures');for(const [key,min,max] of [['quantizationStrength',0,100],['loopStart',0,1000000],['loopEnd',0,1000000],['punchStart',0,1000000],['punchEnd',0,1000000],['latencyCompensationMs',-500,500],['pickupBeats',0,128],['masterVolume',0,1],['rehearsalSpeed',25,200],['loopRepeats',0,100]] as const)finite(settings[key],min,max,key);
  if(value.settings.inputSource!==undefined&&!['keyboard','midi','vocal'].includes(value.settings.inputSource))throw new ProjectFormatError('Source d’entrée invalide.');if(value.settings.vocal){try{validateVocal(value.settings.vocal);}catch(e){throw new ProjectFormatError((e as Error).message);}}
  if(![0,1,2,4].includes(value.settings.countIn)||![0,1,2,4].includes(value.settings.preRoll))throw new ProjectFormatError('Décompte invalide.');if(!['quarter','dotted-quarter','eighth'].includes(value.settings.tempoUnit)||!['overdub','replace'].includes(value.settings.recordMode)||!['none','1/2','1/4','1/8','1/16','1/32','triplet-quarter','triplet-eighth','triplet-sixteenth','compound','auto'].includes(value.settings.quantization))throw new ProjectFormatError('Préférences musicales incompatibles.');for(const key of ['punchEnabled','loopRecording','snap'] as const)if(typeof settings[key]!=='boolean')throw new ProjectFormatError(key+' invalide.');if(value.settings.loopEnd<=value.settings.loopStart||value.settings.punchEnd<=value.settings.punchStart)throw new ProjectFormatError('Zone de boucle ou de Punch invalide.');if(!['piano','soft-piano','organ','vocal'].includes(value.settings.instrument)||!['ensemble','solo','dominant'].includes(value.settings.rehearsalMix))throw new ProjectFormatError('Préférences audio invalides.');array(settings.beatGroups,'Groupements',32).forEach(n=>finite(n,1,32,'Groupement'));
  for(const m of array(value.markers,'Marqueurs',10000)){const x=object(m,'Marqueur');text(x.id,'Identifiant',200);text(x.label,'Repère',200);finite(x.measure,1,100000,'Mesure');}
  for(const m of array(value.tempoMap,'Changements de tempo',10000)){const x=object(m,'Tempo');finite(x.measure,1,100000,'Mesure');finite(x.bpm,10,600,'Tempo');}
  for(const m of array(value.signatureMap,'Changements de mesure',10000)){const x=object(m,'Signature');finite(x.measure,1,100000,'Mesure');if(!validSignature(x.signature))throw new ProjectFormatError('Changement de signature invalide.');if(x.groups!==undefined)array(x.groups,'Groupements',32).forEach(n=>finite(n,1,32,'Groupement'));}
  for(const m of array(value.repeats,'Reprises',10000)){const x=object(m,'Reprise');text(x.id,'Identifiant',200);finite(x.startMeasure,1,100000,'Mesure');finite(x.endMeasure,Number(x.startMeasure),100000,'Mesure');finite(x.times,2,16,'Nombre de reprises');}
  const indicationIds=new Set<string>();for(const m of array(value.indications,'Indications',10000)){const x=object(m,'Indication');text(x.id,'Identifiant',200);if(indicationIds.has(String(x.id)))throw new ProjectFormatError('Indication en double.');indicationIds.add(String(x.id));text(x.text,'Texte',2000);finite(x.measure,1,100000,'Mesure');if(!['dynamic','text','fermata','breath','crescendo','diminuendo','navigation','tempo','accent','tenuto','final'].includes(String(x.kind)))throw new ProjectFormatError('Indication incompatible.');if(x.trackId!==undefined&&!trackIds.has(String(x.trackId)))throw new ProjectFormatError('Voix de l’indication absente.');if(x.trackIds!==undefined)for(const key of array(x.trackIds,'Voix de l’indication',64))if(!trackIds.has(String(key)))throw new ProjectFormatError('Voix de l’indication absente.');if(x.beat!==undefined)finite(x.beat,0,128,'Position de l’indication');if(x.endBeat!==undefined)finite(x.endBeat,0,1000000,'Fin de l’indication');if(x.symbol!==undefined&&!Object.hasOwn(NAVIGATION_LABELS,String(x.symbol)))throw new ProjectFormatError('Signe de navigation invalide.');if(x.targetId!==undefined)text(x.targetId,'Destination',200);}
  for(const raw of array(value.takes,'Prises',500)){const t=object(raw,'Prise');text(t.id,'Identifiant',200);text(t.name,'Nom de prise',200);text(t.createdAt,'Date',100);if(!trackIds.has(String(t.trackId)))throw new ProjectFormatError('Voix de prise absente.');finite(t.startBeat,0,1000000,'Début de prise');finite(t.endBeat,Number(t.startBeat),1000000,'Fin de prise');if(t.mode!==undefined&&!['overdub','replace'].includes(String(t.mode)))throw new ProjectFormatError('Mode de prise invalide.');if(typeof t.selected!=='boolean')throw new ProjectFormatError('État de prise invalide.');notes(t.events,String(t.trackId),new Set());if(t.replacedEvents!==undefined)notes(t.replacedEvents,String(t.trackId),new Set());if(t.source!==undefined&&!['keyboard','midi','vocal'].includes(String(t.source)))throw new ProjectFormatError('Source de prise invalide.');if(t.audio!==undefined){const a=object(t.audio,'Audio original');text(a.id,'Identifiant audio',200);text(a.mime,'Type audio',120);text(a.capturedAt,'Date audio',100);finite(a.bytes,1,80*1024*1024,'Taille audio');finite(a.duration,0,3600,'Durée audio');finite(a.offset,0,3600,'Début dans l’audio');finite(a.length,0,3600,'Passage audio');}}
  for(const collection of [value.markers,value.tempoMap,value.signatureMap,value.indications])for(const item of collection)if(!Number.isInteger(item.measure))throw new ProjectFormatError('Numéro de mesure non entier.');
  for(const repeat of value.repeats)if(![repeat.startMeasure,repeat.endMeasure,repeat.times].every(Number.isInteger))throw new ProjectFormatError('Reprise non entière.');
  try{validateRepeats(value.repeats);}catch(e){throw new ProjectFormatError(e instanceof Error?e.message:'Reprises invalides.');}
  for(const raw of value.lyrics){if(raw.verse!==undefined&&(!Number.isInteger(raw.verse)||raw.verse<1||raw.verse>100))throw new ProjectFormatError('Numéro de couplet invalide.');if(raw.kind!==undefined&&!['verse','refrain','common'].includes(raw.kind))throw new ProjectFormatError('Type de paroles invalide.');for(const syllable of raw.syllables)for(const key of syllable.noteIds??(syllable.noteId?[syllable.noteId]:[]))if(!value.tracks.find(t=>t.id===raw.trackId)!.events.some(n=>n.id===key))throw new ProjectFormatError('Une syllabe référence une autre voix.');}
  const layout=object(value.layout,'Mise en page');if(!['A4','A5','Letter'].includes(value.layout.paper)||!['portrait','landscape'].includes(value.layout.orientation))throw new ProjectFormatError('Format de page invalide.');for(const [key,min,max] of [['margin',5,50],['measuresPerSystem',0,12],['noteSize',10,32],['lyricSize',8,24],['voiceGap',20,70],['systemGap',8,80],['titleSize',14,48]] as const)finite(layout[key],min,max,key);if(typeof layout.pageNumbers!=='boolean')throw new ProjectFormatError('Pagination invalide.');array(layout.systemBreaks,'Sauts de système',10000).forEach(n=>finite(n,1,100000,'Saut de système'));
  const lyricIds=new Set(value.lyrics.map(l=>l.id));if(lyricIds.size!==value.lyrics.length)throw new ProjectFormatError('Identifiants de paroles en double.');
  const sharedIds=new Set<string>();for(const raw of array(value.sharedLyrics??[],'Textes communs',2000)){const s=object(raw,'Texte commun');text(s.id,'Identifiant',200);text(s.name,'Nom',200);text(s.text,'Texte commun');if(sharedIds.has(String(s.id)))throw new ProjectFormatError('Texte commun en double.');sharedIds.add(String(s.id));for(const key of array(s.trackIds,'Voix du texte commun',64))if(!trackIds.has(String(key)))throw new ProjectFormatError('Voix du texte commun absente.');for(const raw of array(s.syllables,'Syllabes communes',200000)){const syllable=object(raw,'Syllabe commune');text(syllable.text,'Syllabe',2000);if(syllable.noteId!==undefined||syllable.noteIds!==undefined)throw new ProjectFormatError('Le texte commun doit conserver ses liens dans chaque voix.');}}
  for(const line of value.lyrics)if(line.sharedTextId){const common=value.sharedLyrics?.find(s=>s.id===line.sharedTextId);if(!common||!common.trackIds.includes(line.trackId)||common.text!==line.text||JSON.stringify(common.syllables.map(s=>[s.id,s.text,s.hyphenAfter]))!==JSON.stringify(line.syllables.map(s=>[s.id,s.text,s.hyphenAfter])))throw new ProjectFormatError('Texte commun et paroles de la voix incohérents.');}
  const linkIds=new Set<string>();for(const raw of array(value.links??[],'Liaisons',10000)){const link=object(raw,'Liaison');text(link.id,'Identifiant',200);if(linkIds.has(String(link.id)))throw new ProjectFormatError('Liaison en double.');linkIds.add(String(link.id));if(!['tie','phrase','melisma'].includes(String(link.kind))||!trackIds.has(String(link.trackId)))throw new ProjectFormatError('Liaison incompatible.');const ids=array(link.noteIds,'Notes de liaison',20000);if(ids.length<2||new Set(ids).size!==ids.length)throw new ProjectFormatError('La liaison nécessite au moins deux notes distinctes.');for(const key of ids)if(!value.tracks.find(t=>t.id===link.trackId)!.events.some(n=>n.id===key))throw new ProjectFormatError('Une liaison référence une note absente de sa voix.');}
  for(const key of ['pageBreaks'] as const)if(layout[key]!==undefined)array(layout[key],key,10000).forEach(n=>{finite(n,1,100000,key);if(!Number.isInteger(n))throw new ProjectFormatError('Saut de page non entier.');});
  for(const [key,min,max] of [['systemCounts',1,12],['measureWidths',.5,3],['systemGaps',8,160]] as const)if(layout[key]!==undefined)for(const [bar,n] of Object.entries(object(layout[key],key))){if(!/^[1-9]\d*$/.test(bar))throw new ProjectFormatError('Mesure de réglage manuel invalide.');finite(n,min,max,key);if(key==='systemCounts'&&!Number.isInteger(n))throw new ProjectFormatError('Nombre de mesures non entier.');}
  for(const [key,choices] of [['justification',['regular','adaptive']],['voiceLabels',['first','page','always','never']],['lyricPlacement',['auto','common','group','voice']],['headerOn',['first','all','following','none']],['footerOn',['first','all','following','none']]] as const)if(layout[key]!==undefined&&!choices.includes(layout[key] as never))throw new ProjectFormatError(key+' incompatible.');
  if(layout.compoundPulse!==undefined&&typeof layout.compoundPulse!=='boolean')throw new ProjectFormatError('Pulsation composée invalide.');
  for(const key of ['headerGap','footerGap'] as const)if(layout[key]!==undefined)finite(layout[key],0,160,key);
  for(const key of ['header','footer'] as const)if(layout[key]!==undefined){const ids=new Set<string>();for(const raw of array(layout[key],key,100)){const d=object(raw,'Décoration');text(d.id,'Identifiant',200);if(ids.has(String(d.id)))throw new ProjectFormatError('Décoration en double.');ids.add(String(d.id));text(d.text,'Texte',2000);if(!['custom','title','author','composer','credits','tonic','tempo','signature','date','page','pages','logo'].includes(String(d.field))||!['left','center','right'].includes(String(d.align))||!['sans','serif','mono'].includes(String(d.font)))throw new ProjectFormatError('Décoration incompatible.');finite(d.size,6,48,'Taille de décoration');finite(d.row,0,20,'Ligne');finite(d.offsetX,-100,100,'Position horizontale');finite(d.offsetY,-60,60,'Position verticale');if(!Number.isInteger(d.row))throw new ProjectFormatError('Ligne de décoration non entière.');for(const k of ['bold','italic','visible'])if(typeof d[k]!=='boolean')throw new ProjectFormatError('Style de décoration invalide.');if(typeof d.color!=='string'||!/^#[0-9a-f]{6}$/i.test(d.color))throw new ProjectFormatError('Couleur de décoration invalide.');if(d.logo!==undefined){text(d.logo,'Logo',2000000);if(!/^data:image\/(png|jpeg);base64,[a-zA-Z0-9+/=]+$/.test(String(d.logo)))throw new ProjectFormatError('Le logo doit être une image PNG/JPEG incorporée.');}}}

}
